### ISSUE TITLE
Campaigns - DeliveryStatus is never set

### ISSUE THREAD

**Issue by linh-tran-mobosurvey** [brandonseydel/MailChimp.Net#100]
Is there a way to obtain the number of successful deliveries for a campaign? On the mailchimp website, the value is called "Successful deliveries". I would imagine this would be in campaignInstance.DeliveryStatus.EmailsSent.

However, this value is always 0 even though "Successful deliveries" is not 0.

Even if I have already sent emails for the campaigns and the recipients receive the emails, opened, and clicked.

When obaining campaignInstance.DeliveryStatus
The values are always:
 campaignInstance.DeliveryStatus.EmailsSent = 0
 campaignInstance.DeliveryStatus.Enabled = false
 campaignInstance.DeliveryStatus.Status = null

**Comment by brandonseydel** [comment]
There is an EmailsSent property on the campaign itself.  Is that not getting set either?

**Comment by linh-tran-mobosurvey** [comment]
I was able to obtain the data I needed by using the Reports class.
