### ISSUE TITLE
ListSegmentLogic:  AddMemberAsync not working

### ISSUE THREAD

**Issue by BDavidHolt** [brandonseydel/MailChimp.Net#103]
Get "unable to find the resource" error.

**Comment by brandonseydel** [comment]
public async Task Add_User_To_ListSegment()
        {
            try
            {
                await this.AddOrUpdate_User_To_List();
                var listSegment = await this._mailChimpManager.ListSegments.AddAsync(this.TestList.Id, new Core.Segment
                {
                    EmailAddresses = new List<string> { $"{this._ticks}@test.com" },
                    Name = "TEST"
                });

                await
                    this._mailChimpManager.ListSegments.AddMemberAsync(
                        this.TestList.Id,
                        listSegment.Id.ToString(),
                        new Member { EmailAddress = $"{this._ticks}@test.com", Status = Status.Subscribed }).ConfigureAwait(false);

                await this._mailChimpManager.ListSegments.DeleteAsync(this.TestList.Id, listSegment.Id.ToString());
            }
            catch(Exception ex)
            {

            }

        }

I just ran this and it worked correctly for me.  Make sure the user you are adding is subscribed and if a new member you add make sure StatusIfNew

**Comment by BDavidHolt** [comment]
This is working, but since the latest update,  the following code (which
used to work) now returns all listsegments beginning with the first ever
(it's ignoring the SinceCreatedAt)

public ListSegment GetGroup(string groupName)
{
    MailChimp.Net.Core.ListSegmentRequest req = new
MailChimp.Net.Core.ListSegmentRequest();
    req.SinceCreatedAt = Now.AddHours(-10);

    dynamic allLists = RunTask(cli.ListSegments.GetAllAsync(listID,
req)).Result.ToArray;
    return (from x in allListswhere x.Name == groupName).FirstOrDefault;

}

**Comment by BDavidHolt** [comment]
It also is ignoring the Offset and Limit - basically the whole
ListSegmentRequest object.
