### ISSUE TITLE
_links should not be in the request when creating a cart

### ISSUE THREAD

**Issue by Jetski5822** [brandonseydel/MailChimp.Net#105]
From Mailchimp support...

"The _links array should not be in the request body when making a POST or PATCH to this endpoint."

**Comment by brandonseydel** [comment]
Does the actually effect anything?  I would expect the deserailization on MailChimps side to ignore the property (or no deserializing if they have node webservice)

**Comment by Jetski5822** [comment]
Yes, it fails mailchimp side. When nulling Links out the call worked

**Comment by brandonseydel** [comment]
*face palm* noobs
