### ISSUE TITLE
API  call to download all campaign reports including combination results

### ISSUE THREAD

**Issue by SueTest** [brandonseydel/MailChimp.Net#106]
1. How do I get the campaign combination results via Campaigns.GetAllAsync? or is there other call I can use to request it?

3. In the MailChimps under report tab has a "Download all reports", how do I find the source code to get the reports? This report includes combination results.   #

**Comment by SueTest** [comment]
Add below example to show what is my need to get all campaign reports. Please help....
var reportRequestFilter = new ReportRequest { Offset = 0, Limit = int.MaxValue, SinceSendTime = DateTime.Now.AddMonths(-6) };
reportRequestFilter.Type = CampaignType.Absplit;

var awaitableTask = _mailChimpManager.Reports.GetAllReportsAsync(reportRequestFilter).ConfigureAwait(false);
var absplitCampaignReports = awaitableTask.GetAwaiter().GetResult();

This absplitCampaignReports did not return both group stats. Normally,  If this was an absplit or variate campaign, stats for the A and B groups will be returned - otherwise this is empty

**Comment by brandonseydel** [comment]
This was just checked in please check it out :). a93d448c526389ef29c1073f6a4f9103723bdd04
