### ISSUE TITLE
BatchRequest - Subscribe List [QUESTION]

### ISSUE THREAD

**Issue by fernicolosi** [brandonseydel/MailChimp.Net#107]
Hi,

I'm new to C# and have never worked before with IEnumerable types, I was hoping to get some advice from you guys. I have a list of new users and I'm trying to add them to a Mailchimp List that I have. When using the BatchRequest class I want to add new instances to the Operations property with all my new contacts information. I tried to do this as if they were regular c# Lists but obviously, it doesn't work this way. 

Do you have any example that I could have a look at for implementing BatchRequest to add multiple contacts to a Mailchimp list?

Don't have much of code done so far but just the bits to create the instance of the class.

Thank you
Fernando

**Comment by wiggisser** [comment]
This is how I do it:


    var chimpMembers = new List<Member();
    ///add members to your list ...
    
    
    var batchRequest = new BatchRequest
    {
        Operations = chimpMembers.Select(x => new Operation
        {
            Method = "PUT",
            Path = $"/lists/{ListID}/members/{manager.Members.Hash(x.EmailAddress.ToLower())}",
            Body = JsonConvert.SerializeObject(x, serializerSettings)
        })
    };

    var batch = manager.Batches.AddAsync(batchRequest).Result;

    //if you want to wait until the batch is finished 
    while (batch.Status != "finished")
    {
        System.Threading.Thread.Sleep(500);
        var batchId = batch.Id;
        batch = manager.Batches.GetBatchStatus(batchId).Result;
    }

**Comment by fernicolosi** [comment]
Thanks, Wiggisser! This vas VERY helpful

**Comment by jmoceri34** [comment]
Following up on @wiggisser response I was able to get it to work by replacing
```csharp
Body = JsonConvert.SerializeObject(x, serializerSettings)
```
with
```csharp
                    Body = JsonConvert.SerializeObject(
                        x, 
                        Formatting.None, 
                        new JsonSerializerSettings { NullValueHandling = NullValueHandling.Ignore })
```

without the serializer settings, empty properties were serialized with null causing the request(s) to fail.

**Comment by wiggisser** [comment]
@jmoceri34 Yes, that's what also my serializerSettings look like. FYI you can add the Formatting.None to the serializersettings

**Comment by sonal231** [comment]
@jmoceri34 Thanks for your comment.
It works for me :-)
