### ISSUE TITLE
Reports.GetEmailActivityAsync results in Error "Type provided must be an Enum"

### ISSUE THREAD

**Issue by linh-tran-mobosurvey** [brandonseydel/MailChimp.Net#108]
When making the following call, we get the error: "Type provided must be an Enum.
Parameter name: enumType" 

Appear there was a similar issue that was fixed in https://github.com/brandonseydel/MailChimp.Net/issues/66

```
var awaitable = _mailChimpManager.Reports.GetEmailActivityAsync(campaignId, recipient.EmailAddress).ConfigureAwait(false);
var results = awaitable.GetAwaiter().GetResult();
```

**Comment by rmonfort** [comment]
Only occurs when there happens to be activities associated with that email address.

**Comment by gdau** [comment]
See #119
