### ISSUE TITLE
MemberLogic::GetAllAsync() always clears out the MemberRequest

### ISSUE THREAD

**Issue by wiggisser** [brandonseydel/MailChimp.Net#110]
My list at MailChimp has about 5000 members, but the MailChimp API returns Error 500 (also in the browser) if i try to receive them all at once, so I tried to iterate in chunks of 500 as follows:

    while (true) {
        var r = new MemberRequest {
            Limit = 500,
            Offset = offset
        };

        var mmembers = manager.Members.GetAllAsync(Properties.Settings.Default.ListID, r).Result;                 
            result.AddRange(mmembers); offset += 500;
        if (mmembers.Count() < 500) break;
    }

But that didn't work either. I only got the first 10 members of the list (I did not initialize MailChimp with a global limit). Furthermore, if I run this query with different offsets, nonetheless I always get the same element. After a bit of debugging I found the following code in MemberLogic::GetResponseAsnyc()

    memberRequest = new MemberRequest
    {
        Limit = base._limit
    };

So the memberrequest I provide is always overwritten by a newly created memberrequest with default parameters.

**Comment by gdau** [comment]
+1 I have this issue too.

**Comment by wiggisser** [comment]
see also the respective pullrequest #113

**Comment by brandonseydel** [comment]
Closed with 9fe44ac16015c37a982beff79c6aa43fea964495
