### ISSUE TITLE
GetEmailActivitiesAsync unwraps response hiding TotalItems

### ISSUE THREAD

**Issue by gdau** [brandonseydel/MailChimp.Net#118]
I've just noticed that the GetEmailActivitiesAsync method in the ReportLogic class unwraps the result by returning emailActivityResponse.EmailActivities. Is it possible to create a counter-part that returns the EmailResponse object so I can gain access to the TotalItems properties of the base class.

Thanks!

g

**Comment by brandonseydel** [comment]
Yes you can put in a PR for this if you would like.  I am in the middle of closing a big contract and I haven't had much time to work on this project.
Thanks,Brandon

Date: Mon, 10 Oct 2016 07:04:50 -0700
