### ISSUE TITLE
Missing documentation for interests

### ISSUE THREAD

**Issue by marklonquist** [brandonseydel/MailChimp.Net#121]
Hi

How do I go about adding a member to a group (interest in this API)?

I see there is an "Member.Interests" where you can add to a dictionary with (string, bool).
What should I add to it to allow a member to be assigned to a group?

I've tried using the ID of the interest and set it to true, but it doesn't work.

For testing purposes I tried this:

    var mfields1 = mailChimpManager.InterestCategories.GetAllAsync(model.ListId);
    while (!mfields1.IsCompleted) { }

    var mfields = mailChimpManager.Interests.GetAllAsync(model.ListId, mfields1.Result.First(x => x.Title == "Frekvens").Id);
    while (!mfields.IsCompleted) { }

    var frequencyId = mfields.Result.First(x => x.Name == model.Frequency).Id;
    member.Interests.Add(frequencyId, true);

**Comment by dougvdotcom** [comment]
The key of the Dictionary is the group's MailChimp ID, which you can only get via the API; the Boolean is true to add the member to that group, false to remove him.

Consolidating what you have with a call to Member.AddOrUpdateAsync should achieve what you are after.

```
public async Task<Member> AddMemberInterestByInterestNameAsync(string email, string listId, string interestName)
{
	var interestId = await GetInterestIdByInterestNameAsync(listId, interestName);
	var member = new Member
	{
		EmailAddress = email,
		Interests = new Dictionary<string, bool>
		{
			{ interestId, true }
		}
	};

	var result = await Manager.Members.AddOrUpdateAsync(listId, member);
	return result;
}

public async Task<string> GetInterestIdByInterestNameAsync(string listId, string interestName) {
	var interestCats = await Manager.InterestCategories.GetAllAsync(listId);
	var interest = await Manager.Interests.GetAllAsync(listId, interestCats.First(x => x.Title == interestName).Id);
	
	return interest.Id;
}
```

**Comment by marklonquist** [comment]
Thank you, I made it work. Had to make som slight modifications, as the interest uses radio button layout.
