### ISSUE TITLE
AddOrUpdateAsync not returning

### ISSUE THREAD

**Issue by rdugre** [brandonseydel/MailChimp.Net#127]
I have the following code where I am trying to retrieve a list member, make some changes to the MergeFields, and then update their record on Mailchimp. I've simplified the code for readability.

```
var mailChimp = new MailChimpManager();
var listMember = mailChimp.Members.GetAsync(listId, email).Result;
listMember.MergeFields["MYFIELD"] = myFieldNewValue;
var transmitResult = mailChimp.Members.AddOrUpdateAsync(listId, listMember).Result;
return transmitResult;
```

When I call the AddOrUpdateAsync function and wait for the result, nothing ever comes back. It just sits on that line within the debugger. I'm assuming it will time-out after some point, but I've waited several minutes and it just sits there.

Any idea why that may be?

**Comment by brandonseydel** [comment]
It's probably deadlocked

**Comment by fgrootenboers** [comment]
Same problem here with following code:

```
var member = new Member
{
	EmailAddress = email,
	EmailType = "html"
};

var resultTask = mailChimpManager.Members.AddOrUpdateAsync(listId, member);

var result = resultTask.Result;
```

@rdugre : did you already managed to update the member or do you have a workaround?

**Comment by rdugre** [comment]
This is still a problem for me. I don't think its a deadlock issue, as I can't think of anything else that is going on that would cause that. The record does get updated for me, but the code hangs and eventually times out.

**Comment by soatley** [comment]
Having a similar issue subscribing a user to a MailChimp list.  The system works fine for retrieving campaigns and getting member info but once the AddOrUpdateAsync method is called, the system deadlocks.  As @rdugre  mentions, the update does actually contact MailChimp as I get a confirmation email from them.

**Comment by soatley** [comment]
The project I'm working on right now is in VB so that's what I'm posting.  I'm sure the C# equivalent would work fine too but I haven't tested it.  This code allows the AddOrUpdateAsync to work in my application:
` Dim result As Member = Task.Run(Function() api.Members.AddOrUpdateAsync(listID, mr)).Result`

I'm passing in the List ID (listID variable) and a MemberRequest (mr) variable. 

Hope this helps as a work around for anyone who's looking to use it.

**Comment by fgrootenboers** [comment]
Yes, that is working for me too.
The C# equivalent:
`Member result = Task.Run(() => api.Members.AddOrUpdateAsynclist(ID, mr)).Result;`

**Comment by wc-matteo** [comment]
I think the issue is that [this](https://github.com/brandonseydel/MailChimp.Net/blob/4e90d17217ceb83ce44f23742c24c3f748d5e5ea/MailChimp.Net/Core/HttpRequestExtensions.cs#L125) _awaited_ call inside `PutAsJsonAsync()` has no `.ConfigureAwait(false)` specified. This would cause a deadlock.

**Comment by brandonseydel** [comment]
Good find I altered them all..
