### ISSUE TITLE
MergeField.Options.DefaultCountry should be Int

### ISSUE THREAD

**Issue by manicfiddler** [brandonseydel/MailChimp.Net#13]
{"type":"http://developer.mailchimp.com/documentation/mailchimp/guides/error-glossary/","title":"Invalid Resource","status":400,"detail":"The resource submitted could not be validated. For field-specific details, see the 'errors' array.","instance":"","errors":[{"field":"options.default_country","message":"Schema describes integer, string found instead"}]}

**Comment by brandonseydel** [comment]
Thank you for this do you want me to fix or do you want to make a pull request?

**Comment by manicfiddler** [comment]
Happy to make a pull request if I knew how....not a git expert, we use TFS in house.

Found another issue as well which is BatchLogic.AddSync(BatchRequest request = null)....methinks a copy-paste error crept in here as the await client.PostAsJsonAsync also passes request = null which nulls out request before it is posted :).

For now I'm working with a local copy of your project but will look to put pull requests in for all the changes I am making (these 2 + various default values for properties in the model to reduce the amount of code a client needs to write)

Cheers

**Comment by manicfiddler** [comment]
Ah yeah, one more change I've made is to expose the Hash method through MemberLogic and IMemberLogic to allow batch creation of list members (you need the email address hash in this instance)

**Comment by brandonseydel** [comment]
Will you be submitting a PR soon?

**Comment by brandonseydel** [comment]
Im going to add these changes in for you since you are not familiar with GIT.

**Comment by brandonseydel** [comment]
@manicfiddler So you are wanting

internal string Hash 
to be made public so you can use it?
