### ISSUE TITLE
MailChimpManager.Reports.GetEmailActivityAsync throws Type provided must be an Enum.

### ISSUE THREAD

**Issue by mattthrower** [brandonseydel/MailChimp.Net#133]
I am trying to get the email activity report. When I run the following:

`var emailActivity = MailChimpManager.Reports.GetEmailActivitiesAsync("00a00a0000", new QueryableBaseRequest {Limit = 10}).Result;`

I get the error:

**_Type provided must be an Enum.
Parameter name: enumType_**

I have checked the campaignId is valid. How can I resolve?

**Comment by mattthrower** [comment]
I am using version 1.7.5.0

I am able to download information for members by using the following code:

`var contacts = MailChimpManager.Members.GetAllAsync("00a00a00aa", new MemberRequest {Limit = 10, Offset = 0}).Result.ToList();`

**Comment by strigi** [comment]
I encounter the same issue. V1.7.5.0
Same code used to work in previous versions.

**Comment by mattthrower** [comment]
Thanks strigi. Version 1.7.1.0 worked for me.

**Comment by strigi** [comment]
Any news on that?

**Comment by brandonseydel** [comment]
Can you pull latest and test for me or write a test case.  I believe I implemented a fix for this in EmailActivity
