### ISSUE TITLE
Any plan for supporting .Net Core? Question

### ISSUE THREAD

**Issue by vdangwal** [brandonseydel/MailChimp.Net#134]

**Comment by brandonseydel** [comment]
Yes I will hopefully have time this month.


________________________________

**Comment by vdangwal** [comment]
Thanks for your quick response 👍.

Get Outlook for iOS<https://aka.ms/o0ukef>




On Fri, Nov 4, 2016 at 9:53 AM -0400, "Brandon seydel" <notifications@github.com<mailto:notifications@github.com>> wrote:

Yes I will hopefully have time this month.


________________________________

**Comment by hmvs** [comment]
Looking forward to it. Any help needed?

**Comment by Brouilles** [comment]
Hello, Is there any news on ASP.NET Core support? Thank for you great job !

**Comment by brandonseydel** [comment]
Holidays and deadlines for companies are knocking me down.  I will be trying to get core in by the end of the year.

**Comment by david-lorenzo88** [comment]
Hello,
Any news about the porting to .NET Core? I can also help if you need.
Thanks for your effort
David

**Comment by brandonseydel** [comment]
I am waiting for .net standard 2 before making a full port.

Sent from my iPhone

On Dec 28, 2016, at 4:32 PM, David Lorenzo L?pez <notifications@github.com<mailto:notifications@github.com>> wrote:


Hello,
Any news about the porting to .NET Core? I can also help if you need.
Thanks for your effort
David

-

**Comment by ChristianHaase** [comment]
Any update on this?

**Comment by ChristianHaase** [comment]
Whoops, nevermind. Just saw issue #184
