### ISSUE TITLE
Using Members.AddOrUpdateAsync, how to get HTTP response status, errors, etc?

### ISSUE THREAD

**Issue by rvencu** [brandonseydel/MailChimp.Net#136]
Member result = Task.Run(() => mailmanager.Members.AddOrUpdateAsync("7038------", member)).Result;
will return a member and I can test his status for instance but how to treat errors in case the API returns something else than HTTP code 200 ?

API docs specify some more error information as type, etc that would be useful to record.

**Comment by brandonseydel** [comment]
try catching MailChimpException

**Comment by rvencu** [comment]
ok, thanks

**Comment by sharmavishalvk** [comment]
Try catch exception and you can see inner exception as mailchimpexception. Message got the error
