### ISSUE TITLE
await method exits unexpectedly

### ISSUE THREAD

**Issue by Alin-Dumitrescu** [brandonseydel/MailChimp.Net#137]
Hello,

I loaded the package and created some simple code. When debugging, stepping over the first line in the GetLists, the program exits without any error message. What could be wrong? How do i get the error?

class Program
    {

        static IMailChimpManager manager;

        static void Main(string[] args)
        {
            manager = new MailChimpManager();
            GetLists();
        }
public async static void GetLists()
        {
            IEnumerable<MailChimp.Net.Models.List> listCollection = await manager.Lists.GetAllAsync().ConfigureAwait(false);

            foreach(MailChimp.Net.Models.List list in listCollection)
            {
                Trace.WriteLine(list.Id);
            }
        }
}

**Comment by brandonseydel** [comment]
```
svm(string[] args)
{
  var getLists = GetLists();
  getLists.Wait();
}
```

--This is pseudo--

**Comment by Alin-Dumitrescu** [comment]
HI Brandon,
Thanks for the reply, I eventually figured it out ☺. It would be good to have a complete sample code (or links) on the main page – e.g. connect and get all root lists.

Thank you,
Alin Dumitrescu
TFS Hosting<http://www.praktikgroup.com/> and Consulting<http://www.praktikgroup.com/tfs-consulting> Services | PRAKTIK Group
phone (425) 279-3465 | www.praktikgroup.com<http://www.praktikgroup.com/>

**Comment by Alin-Dumitrescu** [comment]
Hi Brandon,

I performed an AddOrUpdateAsync on a Member that is VIP (only updated one Interest) and I noticed the VIP indicator turned off. Is that desired behavior or a code issue? If code issue, is that something on my side or in the API?.

Thank you,
Alin Dumitrescu
TFS Hosting<http://www.praktikgroup.com/> and Consulting<http://www.praktikgroup.com/tfs-consulting> Services | PRAKTIK Group
phone (425) 279-3465 | www.praktikgroup.com<http://www.praktikgroup.com/>
