### ISSUE TITLE
Getting List Interests 

### ISSUE THREAD

**Issue by tigerdi** [brandonseydel/MailChimp.Net#139]
I am trying to add a subscriber to a list and place them in a specific group. I know how to do that when I know the ID of the interest, but I was wondering if there was some way of calling a GET method which takes the ListID and returns all the interest IDs. I would then want to take that further by creating a function which returns the interestID when inputting the interest Name.

Any ideas?

**Comment by tigerdi** [comment]
Never mind - I managed to do what I was after. Didnt see that you could get the Interests and InterestCategories from the MailChimpManager

**Comment by StewSchrieff** [comment]
@tigerdi Could you provide code samples? I'm having similar issues
