### ISSUE TITLE
Nuget package dependencies doesn't list Newtonsoft.Json v7

### ISSUE THREAD

**Issue by oatsoda** [brandonseydel/MailChimp.Net#14]
https://www.nuget.org/packages/MailChimp.Net.V3/

Would be useful if you listed Newtonsoft.Json as a dependency on Nuget - more specifically the version :)

**Comment by brandonseydel** [comment]
Ok thanks will do

**Comment by brandonseydel** [comment]
Added dependency as well as updated newtonsoft to latest
#110420c4da2f4b186b25898b3a5d33a499da9593

**Comment by oatsoda** [comment]
That was quick! Thanks.

**Comment by brandonseydel** [comment]
@oatsoda I will usually merge and fix things within an hour if there is something that needs a fixin'
