### ISSUE TITLE
Offset is no longer working in requests

### ISSUE THREAD

**Issue by RichardBurns-Amico** [brandonseydel/MailChimp.Net#142]
We have 10 merge fields, when using version 1.7.5 the following returns 0 records:

`var iterationMergeFields = mailChimp.MergeFields.GetAllAsync(
          "LISTID", new MergeFieldRequest() { Limit = 100, Offset = 100 })
          .Result;
        if (iterationMergeFields.Count() == 0)
          break;`

But after updating to version 1.8 the code above returns 10 records no matter what the offset is.

**Comment by michaeldinsightly** [comment]
Neither is limits. In the ListLogic class, the ListRequest object being sent in is being completely ignored.

**Comment by michaeldinsightly** [comment]
Line 152 for your reference in ListLogic.cs
