### ISSUE TITLE
How do you query the state of a submitted batch?

### ISSUE THREAD

**Issue by manicfiddler** [brandonseydel/MailChimp.Net#15]
Both GetAllSync and GetResponseAsync take a QueryableBaseRequest as a parameter but this is an abstract class.  I cannot see a derived class that would be suitable here.

There also seem to be very little difference between these two methods....can you clarify their intended uses?

Cheers

**Comment by brandonseydel** [comment]
QueryableBaseRequest should not be abstract this needs to be fixed.
The getall and getresponse as you stated are very similary and getresponseasync was actually added later because i didn't want to restrict details, but i didn't want to break everyone either.
