### ISSUE TITLE
Lists GetAllAsync

### ISSUE THREAD

**Issue by yussenn** [brandonseydel/MailChimp.Net#151]
I want to download all lists using Lists.GetAllAsync, but I always get only 10 lists ,even though the Limit is 20. What could be my mistake? .I am using MailChimp.Net.V3 1.8.0 . Thank you
```cs 
IMailChimpManager manager = new MailChimpManager("xxxxxxxxxxxxxxxxxxxxx");
   var list = manager.Lists.GetAllAsync(new ListRequest{
              Limit = 20
   }).Result.ToList();
```

**Comment by brandonseydel** [comment]
I think there is a fix in place for this but may not be released yet to nuget.

**Comment by brandonseydel** [comment]
#142 closes this i will get a new version out to nuget asap

**Comment by sharmavishalvk** [comment]
Thanks @brandonseydel I was facing the same issue. Cheers.
