### ISSUE TITLE
Members.GetAllAsync MemberRequest.FieldsToInclude, MemberRequest.FieldsToExclude

### ISSUE THREAD

**Issue by vincejtl** [brandonseydel/MailChimp.Net#152]
First time posting a question. Could not see where I could post the issue as a question. Hopefully this is the right place.

Trying to pull members using FieldsToInclude or FieldsToExclude.
`var members = await manager.Members.GetAllAsync(listId, request).ConfigureAwait(false);`

Include fields does not return any results
`request.FieldsToInclude = "members.email_address";`

Exclude fields returns results but does not exclude the fields.
`request.FieldsToExclude = "members.merge_fields";`

I've tried different fields and even using a different prefixes "(M/m)ember.xxx" vs "(M|m)embers.xxx"

Any guidance would be appreciated.

**Comment by sharmavishalvk** [comment]
@vincejtl - I'm using MailChimp.Net from last couple of weeks and for me 'exclude_fields' as well as 'fields' are working as expected via Postman! Do you getting expected response from Postman? I would suggest check you list/members data. 
Thanks Vishal

**Comment by vincejtl** [comment]
@sharmavishalvk, In Postman the 'fields' and 'exclude_fields' work for pulling members from a list. Using mailchimp.net it does not. I see you mention in is working for you in Postman as well. Does it work for you using MailChimp.Net for Members?

@brandonseydel 
I noticed another issue the status is also not correct.
Looking at fiddler, the request sent by Mailchimp.Net has the following in the querystring.
https://us1.api.mailchimp.com/3.0/lists/xxxxxxxxx/members?vip_only=False&status=s,u,b,s,c,r,i,b,e,d&count=5&offset=0&fields=m,e,m,b,e,r,s,.,e,m,a,i,l,_,a,d,d,r,e,s,s

The fields and status parameter has comma's inserted between each letter.
Using the same querystring in postman replicates the empty returned results.
Removing the commas, returns the correct results.

It looks like the comma's is breaking the fetch by status and fields, exclude_fields.

**Comment by vincejtl** [comment]
Issues #145 and issues #143 may also be symptoms causes by the comma's.

I confirmed that an older version of MailChimp.net v1.5.0 the querystring parameters are correct
And it works as expected.

.../members?status=unsubscribed&count=5&offset=0&fields=members.email_address,members.status

**Comment by vincejtl** [comment]
Looks like there is a fix committed. And yet to be released on nuget.
f24b16a6115e0068b46d5d044899b9ad101226f7

**Comment by sharmavishalvk** [comment]
@vincejtl I faced this comma separated value issue for dates filter for List.GetAllAsync() thus committed the fix. pull#153.

**Comment by brandonseydel** [comment]
I am going to release a nuget tonight so be watching for it.

**Comment by brandonseydel** [comment]
This has been released as 1.8.5
