### ISSUE TITLE
segment condition returns error

### ISSUE THREAD

**Issue by ipenekli** [brandonseydel/MailChimp.Net#157]
hi all,

here is the code block of creating campaign which has recipient segment condition below;
I wanna create campaign and add recipient segment option including spesific segment condition. 

MailChimp.Net.Models.Condition sc = new Condition();
                sc.Type = ConditionType.Interests;
                sc.Operator = Operator.InterestContains;
                string intid = "884f002410";
                sc.Field = "interests-" + intid;
                sc.Value = mcGroupName;
                IEnumerable<Condition> cons = new Condition[] { sc };
                var con = (IEnumerable<Condition>)cons;
                MailChimp.Net.Models.SegmentOptions so = new SegmentOptions();
                so.Match="any";
                so.Conditions = con;
                MailChimp.Net.Models.Recipient r = new Recipient();
                r.ListId = mcListId;
                r.SegmentOptions = so;
                c.Recipients = r;
                c.Settings = s;
                c.Tracking = t;
                c.Type = MailChimp.Net.Core.CampaignType.Regular;
                c.ContentType = "html";
                //template
                if (!string.IsNullOrEmpty(templateid))
                {
                    int tid = int.Parse(templateid);
                    s.TemplateId = tid;
                    c.ContentType = "template";
                }
                //create campaign on mc
                Campaign createdcampaign = mailChimpManager.Campaigns.AddAsync(c).Result;

 When i run the code, i get errors as follows;
"Title: Invalid Resource
 Type: http://developer.mailchimp.com/documentation/mailchimp/guides/error-glossary/
 Status: 400
 + Detail: The resource submitted could not be validated. For field-specific details, see the 'errors' array.
Errors: recipients.segment_opts.conditions.item:0 Data did not match any of the schemas described in anyOf.A first chance exception of type 'System.AggregateException' occurred 

in mscorlib.dll"
do you have any idea? what is wrong?

**Comment by brandonseydel** [comment]
I need to check the description on the enum of the segment to make sure it aligns to what mail chimp is wanting.

**Comment by bevnetcraven** [comment]
@brandonseydel Did you ever resolve this issue? We, too, would like to use the segment functionality. Thanks.

**Comment by morsalyangoz** [comment]
I had same error message. I solved my problem by casting segment options values to Jarray. Hope it helps.
`con.Value = Newtonsoft.Json.Linq.JArray.FromObject(myStringArrayOfInterestIds);`
