### ISSUE TITLE
Operation is removing emails from lists rather than adding them?

### ISSUE THREAD

**Issue by scamplogic** [brandonseydel/MailChimp.Net#158]
I have the following code which is designed to add subscribers from a DataGridView:

        For Each User In Enabled.Rows

            Dim Member = New Global.MailChimp.Net.Models.Member() With {.EmailAddress = User(3).ToString, .StatusIfNew = Global.MailChimp.Net.Models.Status.Subscribed}
            Member.MergeFields.Add("FNAME", User(1).ToString)
            Member.MergeFields.Add("LNAME", User(2).ToString)
            Member.MergeFields.Add("COMPANY", User(4).ToString)

            MailChimp.Members.AddOrUpdateAsync(ID, Member)

        Next

        '=======================

        For Each User In Disabled.Rows

            Dim Member = New Global.MailChimp.Net.Models.Member() With {.EmailAddress = User(3).ToString, .StatusIfNew = Global.MailChimp.Net.Models.Status.Subscribed}
            Member.MergeFields.Add("FNAME", User(1).ToString)
            Member.MergeFields.Add("LNAME", User(2).ToString)
            Member.MergeFields.Add("COMPANY", User(4).ToString)

            MailChimp.Members.AddOrUpdateAsync(ID, Member)

        Next

But each time it runs, it appears to be deleting users from my mailing list rather than adding them... I have the right API key and list IDs.

**Comment by MatiasALopez** [comment]
Hi @scamplogic,

I believe this Issue is due to the Member's Status default value (set in the constructor) which is Pending. 
Make sure you're setting the right Status before calling AddOrUpdateAsync. If you don't want to update the member's status you should use the "Undefined" status.

Hope it helps!

**Comment by lxalln** [comment]
We have just been hit by this bug too, caused thousands of members to be 'removed' from the list. This should definitely be changed to be `Undefined` by default.

**Comment by brandonseydel** [comment]
I will set the status to undefined by default or a PR would be appreciated.

**Comment by lxalln** [comment]
@scamplogic to get this working for the time being, you just need to set `Status` to be Undefined.

Using undefined should ensure the status is not changed if the member already exists on the list.

Something like:
```vbnet
Dim Member = New Global.MailChimp.Net.Models.Member() 
                          With { .EmailAddress = User(3).ToString, 
                                 .Status = Global.MailChimp.Net.Models.Status.Undefined, 
                                 .StatusIfNew = Global.MailChimp.Net.Models.Status.Subscribed }
```

I'm not really familiar with VB, so please excuse the example if it's not exactly right.

**Comment by scamplogic** [comment]
Fantastic. Thanks very much. :)
