### ISSUE TITLE
Abusereports.getallsync needs listid but api reqires campaignid!

### ISSUE THREAD

**Issue by ipenekli** [brandonseydel/MailChimp.Net#161]
hi,
I wanna get abusereport details for a campaign. Abusereports.getallsync() method reqires listid, but API requires CampaignId as follows;
http://developer.mailchimp.com/documentation/mailchimp/reference/reports/abuse-reports/

![wrapper](https://cloud.githubusercontent.com/assets/4180296/21424041/a541a1ea-c859-11e6-83ed-39c57e5d0e73.png)

**Comment by brandonseydel** [comment]
This looks like missed implementation the abuse reports your looking are indeed for a list but you want them as a report based off a campaign

http://developer.mailchimp.com/documentation/mailchimp/reference/lists/abuse-reports/
