### ISSUE TITLE
Timeout on requesting

### ISSUE THREAD

**Issue by ghost** [brandonseydel/MailChimp.Net#170]
I get a timeout after 100 seconds is there any way there is a way around this.

**Comment by brandonseydel** [comment]
Yea let me add an option for timeout specification.

Sent from my iPhone

On Jan 13, 2017, at 6:55 AM, Corey Stokes <notifications@github.com<mailto:notifications@github.com>> wrote:


I get a timeout after 100 seconds is there any way there is a way around this.

-

**Comment by ryepup** [comment]
Maybe a `public static TimeSpan DefaultHttpTimeout` on `Mailchimp.Net.Common`?

Then could use that in `BaseLogic.CreateMailClient`?

**Comment by Alin-Dumitrescu** [comment]
Hi - I am running into the same issue - was this implemented? If yes, how do we set the option?
