### ISSUE TITLE
Added list member with Status = 'subscribed' is gets created with Status ='pending'

### ISSUE THREAD

**Issue by fpro123** [brandonseydel/MailChimp.Net#172]
Hi,

I'm following your example and try to create a member to an existing list. I would expect the member to become "subscribed" (and therefore not get confirmation mail from MailChimp).
But after creation, the member has status = 'pending' and receives a confirm subscription email.

var listId = "f0c37eec7e";
var member = new Member { EmailAddress = "dd@dd.test", Status = Status.Subscribed};
member.MergeFields.Add("FNAME", "Firstname");
member.MergeFields.Add("LNAME", "Lastname");
var memreturn = await mailChimpManager.Members.AddOrUpdateAsync(listId, member);

Am I missing something?

Regards

Francis

**Comment by brandonseydel** [comment]
There is a statusifnew you need to use.

Sent from my iPhone

On Jan 17, 2017, at 9:52 AM, fpro123 <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi,

I'm following your example and try to create a member to an existing list. I would expect the member to become "subscribed" (and therefore not get confirmation mail from MailChimp).
But after creation, the member has status = 'pending' and receives a confirm subscription email.

var listId = "f0c37eec7e";
var member = new Member { EmailAddress = "dd@dd.test<mailto:dd@dd.test>", Status = Status.Subscribed};
member.MergeFields.Add("FNAME", "Firstname");
member.MergeFields.Add("LNAME", "Lastname");
var memreturn = await mailChimpManager.Members.AddOrUpdateAsync(listId, member);

Am I missing something?

Regards

Francis

-

**Comment by fpro123** [comment]
Perfect.

Thanks for a great wrapper!

/Francis
