### ISSUE TITLE
QueryString Parameters on MailChimp Read calls

### ISSUE THREAD

**Issue by spyguyhi** [brandonseydel/MailChimp.Net#173]
Good morning,

I am just starting with this wrapper to replace a MailChimp API 2.0 wrapper we have been using for the past year.  In the call to mailchimpmanager.Members.GetAllAsync(listId).Result is there a way to add querystring parameters like "status" ="cleaned" or "unsubscribed"?  It seems to me that GetAllAsync will get all the members of the list and I would have to loop through the list of members returned to find all those that were "cleaned" or who had "unsubscribed".  Also the default value for "count" is 10 in the MailChimp API and in 2.0 the max was 100.  Does your function call bypass the count function to return all members?  Is there a way for me to set a count of the number of records I want returned?

Thanks

**Comment by brandonseydel** [comment]
var manager = new MailChimpManager(new MailChimpConfiguration
            {
                Limit = 1000
            });

            manager.Members.GetAllAsync("listId", new Core.MemberRequest
            {
                Status = Status.Subscribed
            });

**Comment by spyguyhi** [comment]
sweet :)

**Comment by spyguyhi** [comment]
I ended up with this:

var manager = new MailChimpManager(apikey);
manager.Configure(new MailChimpConfiguration { Limit = 100 });

This worked for me.
