### ISSUE TITLE
Update member of Members.AddOrUpdateAsync is not working

### ISSUE THREAD

**Issue by skltfz** [brandonseydel/MailChimp.Net#178]
This API doesn't work as expected for subscribed or unsubscribed member.

For subscribed member, i have tried to Members.GetAsync to get the existing member, information fetched correctly.

then I have tried to modify its email address and update it by calling Members.AddOrUpdateAsync, nothing happened  on MailChimp. 

Note that no error is returned also the return Member is shown the changed email address.

Note that even through adding new member (expected it should update the existing one), It is not always working, sometimes the request is executed but no new member is added or updated. The API call is not consistent returning the same result and kind of unpredictable.

**Comment by MatiasALopez** [comment]
Hi @skltfz, 

I believe this Issue is exposing the same problem on #158. I've added a comment there, please check on it.

Thanks!

**Comment by brandonseydel** [comment]
Are you setting the StatusIfNew Property now?
