### ISSUE TITLE
Passing Query string parameters in batch

### ISSUE THREAD

**Issue by Jafferwaffer** [brandonseydel/MailChimp.Net#179]
Hello! I am having some issue with passing query string parameters in batch operations.
I have tried the following for creating an `Operation` (where I add the `Operation` to list to pass to the `Operations` property in `BatchRequest`)

``` C#
operations.Add(new Operation
{
    Method =  "GET",
    Path = $"/lists/{listId}/members",
    Params = new {
        status = Status.Unsubscribed,
        since_last_changed = "2017-01-31",
        offset = 0,
        count = 20
    }
})
```

The response I get back from MC is `[]`. 
I also tried creating the `Params` object using the properties of `MemberRequest` as the Key but this gave me back all members.

After looking through `BatchLogic` I figured I should use `GetResponseAsync` as it uses a `QueryableBaseRequest `, however, the request passed in is immediately overwritten.

``` C#
public async Task<BatchResponse> GetResponseAsync(QueryableBaseRequest request = null)
{
    request = new QueryableBaseRequest
    {
        Limit = base._limit
    };

    using (var client = this.CreateMailClient("batches"))
    {
        var response =
            await
                client.GetAsync(request?.ToQueryString() ?? string.Empty)
                    .ConfigureAwait(false);
        await response.EnsureSuccessMailChimpAsync().ConfigureAwait(false);
        var batchResponse = await response.Content.ReadAsAsync<BatchResponse>().ConfigureAwait(false);
        return batchResponse;
    }
}
```

How can I preform a `GET` request with the following route?
```
/lists/{listID}/members?status=unsubscribed&since_last_changed={lastChangeDate}&offset=20&count=20
```
I have tested using Postman that this route works for my listID and returns data.

**Comment by brandonseydel** [comment]
`CSharp
request = request ?? new QueryableBaseRequest
    {
        Limit = base._limit
    };

`

**Comment by Jafferwaffer** [comment]
I was testing batches in postman and found that they aren't correctly running. I have spoken to Mailchimp support and am awaiting a response from their API team.

**Comment by brandonseydel** [comment]
OK let me know what they say.  The fix I suggested still needs to be implemented so I will leave this as a bug.

**Comment by Jafferwaffer** [comment]
Mailchimp never got back to me, but it looks like they did fix passing in parameters with batches. They expect this form:
``` JSON
{"operations":[ {
	"method": "GET",
	"path": "/lists/{listId}/members",
	"params" : {
		"status" : "unsubscribed",
                "since_last_changed" : "2017-01-31T00:00:00+00:00",
                "offset" : 0,
                "count" : 20
	  }
  }]
}
```

**Comment by brandonseydel** [comment]
Is this working currently then or no?

**Comment by Jafferwaffer** [comment]
Yes it is working, thank you. For anyone else having trouble make sure that the operation's parameter values are all strings. Like so:
``` C#
operations.Add(new Operation
{
    Method =  "GET",
    Path = $"/lists/{listId}/members",
    Params = new {
        status = "unsubscribed",
        since_last_changed = "2017-01-31",
        offset = 0,
        count = 20
    }
})
```
