### ISSUE TITLE
.NET Standard Package

### ISSUE THREAD

**Issue by follesoe** [brandonseydel/MailChimp.Net#184]
Are you working on a .NET Standard based version of the library? It looks like the Microsoft.AspNet.WebApi.Client dependency is an issue with .NET Core?

**Comment by brandonseydel** [comment]
I am waiting for the .net standard 2.0 since this will be a big change which should release with VS2017.

https://blogs.msdn.microsoft.com/dotnet/2016/09/26/introducing-net-standard/
https://www.infoq.com/news/2016/12/netcore2-spring2017

**Comment by Jetski5822** [comment]
ive ported it..... do you want me to do a PR?

**Comment by Jetski5822** [comment]
I lie... I got the mailchimp package building on netstandard 1.6. I need to port the tests too... I can do a PR for what I have done?

**Comment by brandonseydel** [comment]
Yes please that would be great.


________________________________

**Comment by Jetski5822** [comment]
Heres the PR, 4 failing tests... https://github.com/brandonseydel/MailChimp.Net/pull/203

**Comment by hmvs** [comment]
Would be cool to have it merged and pushed to nuget at least as a prerelease.

**Comment by brandonseydel** [comment]
I will work on that this week.

**Comment by karwalr** [comment]
Any more progress on the .NET standard / Core version?

**Comment by Jetski5822** [comment]
Works for me :) - I'll keep updating the PR as I find things.

**Comment by ctolkien** [comment]
This can probably be closed now @brandonseydel  ?
