### ISSUE TITLE
Campaigns.GetAsync(campaignId).Result

### ISSUE THREAD

**Issue by wdetter** [brandonseydel/MailChimp.Net#187]
Hi, 

I've just upgraded the NuGet-Package to the latest version (1.9.0.0). Im now receiving the following error if I try do get a campaign by the campaignId:

`Input string '1243.4361' is not a valid integer. Path 'report_summary.ecommerce.total_spent', line 1, position 1248.`

Thanks,
Werner

**Comment by wdetter** [comment]
Added pull request: https://github.com/brandonseydel/MailChimp.Net/pull/188

**Comment by brandonseydel** [comment]
Good find thank you!
