### ISSUE TITLE
Not compatible with .netcoreapp

### ISSUE THREAD

**Issue by stsomewheredesign** [brandonseydel/MailChimp.Net#189]
Is there a version compatible with .netcoreapp 1.0? I receive this error when trying to install the package:

`Package MailChimp.Net.V3 1.9.0 is not compatible with netcoreapp1.0 (.NETCoreApp,Version=v1.0). Package MailChimp.Net.V3 1.9.0 supports: net45 (.NETFramework,Version=v4.5)
    One or more packages are incompatible with .NETCoreApp,Version=v1.0.`

**Comment by brandonseydel** [comment]
I am going to be porting this over soon.  I was trying to sait for .netstandard 2.0, but the new timeline puts it too far in the future.

**Comment by brandonseydel** [comment]
Sames as #184
