### ISSUE TITLE
Issue in multie threaded enviroment

### ISSUE THREAD

**Issue by Adconsulting** [brandonseydel/MailChimp.Net#193]
when running the lib in a multie threaded system the 
`response.Content.ReadAsAsync<T>` 
does not fill in the top level properties of an object. 

i have run into this using your lib in combination with MEF.

**Comment by Adconsulting** [comment]
i was able to fix the issue using the NewtonSoft Json deserialization. 
I added the following to the BaseLogic.cs


        protected T GetResponse<T>(HttpResponseMessage response)
        {

            if (!_mailChimpConfiguration.UseNewtonSoft)
            {
                return response.Content.ReadAsAsync<T>().Result;
            }

            var content = response.Content.ReadAsStringAsync().Result;

            var result = JsonConvert.DeserializeObject<T>(content);

            return result;
        }

and replaced all calls with his method. 
this fixes the multie thread problem

if you like, i can commit my changes to a separate branch for reviewing

**Comment by brandonseydel** [comment]
Please do.
