### ISSUE TITLE
Unknown Error without any message using GetClickReportMemberAsync

### ISSUE THREAD

**Issue by lichcrise** [brandonseydel/MailChimp.Net#199]
Hi all

First of all, thank you very much for this awesome .NET Wrapper brandonseydel. Its perfect for my use.
In my project I get all the report data from a specific member. I handle this with GetClickReportMemberAsync and GetClickReportMembersAsync. The params are correct but the there is always coming up an error with no message. Its just: "Exception thrown: 'MailChimp.Net.Core.MailChimpException' in mscorlib.dll".
Do someone have any clue what the problem is? Or do someone had some similiar problems?
Please help me or tell me about you expirience.
Kind regards lichcrise

**Comment by kristho91** [comment]
Maybe it's some kind of the same error I keep getting (just on GetMember, though).
I have created a pull request with possibilities for more error logging (PR#268), but the implementation is a breaking change, and I can't figure out how to make it non-breaking.
