### ISSUE TITLE
Removing error messages from output

### ISSUE THREAD

**Issue by deluvas** [brandonseydel/MailChimp.Net#209]
When an error occurs during a request, a response message is printed to standard out. How can I disable that?

**Comment by deluvas** [comment]
It's been almost a month now and no answer, but I found this:

https://github.com/brandonseydel/MailChimp.Net/blob/master/MailChimp.Net/Core/MailChimpException.cs#L65

Yeah, apparently it's hard coded.

**Comment by brandonseydel** [comment]
Sorry Please change to debug and push back i will commit right away.


________________________________

**Comment by deluvas** [comment]
See PR
