### ISSUE TITLE
[question] Query Members by Interest Category Id, Interest Ids, and/or Interest Match

### ISSUE THREAD

**Issue by fireole** [brandonseydel/MailChimp.Net#216]
How can I query members only on interest_category_id, interest_ids, and/or interest_match?

In the MemberRequest, I only see a few objects that I can query on. 

MC Reference of query params:  [http://developer.mailchimp.com/documentation/mailchimp/reference/lists/members/#read-get_lists_list_id_members](url)

  var members = manager.Members.GetAllAsync(_listId, new MemberRequest
            {
                // ??   InterestCategoryId = 
                Limit = 50
            }).Result;

**Comment by justSteve** [comment]
I'm also looking for help with this process. It boils down to where/how do we define the querystring that returns the memberset with the given InterestCategory. This URL works against MC's API: https://us10.api.mailchimp.com/3.0/lists/35b03448/members?interest_category_id=ffdf234a&interest_ids=726181c3&interest_match=any 

How do we achieve the same with the lib?

**Comment by justSteve** [comment]
Turned out to be a simple matter of adding those 3 properties to the MemberRequest.cs. On the new build the given property names are available.
