### ISSUE TITLE
Unable to fetch a member by email

### ISSUE THREAD

**Issue by misbahyunus** [brandonseydel/MailChimp.Net#217]
I'm trying to fetch a subscriber by email but not being able to do so. I'm getting an API key missing error even though it's been supplied.
In my class, I have declared the MailChimp manager as class member : 
```c#
IMailChimpManager mailChimpManager = new MailChimpManager(GlobalSettings.ApiKey);
```

But when I call the following code-
```c#
var c = await this.mailChimpManager.Members.GetAsync(GlobalSettings.ListId, customer_email);
```

I'm getting the following error -- "Your request did not include an API key. Unable to find resource at [web address]".
In another method of the same class, I have code fetching all members in a list -
```c#
var result = await this.mailChimpManager.Members.GetAllAsync(GlobalSettings.ListId, new MailChimp.Net.Core.MemberRequest { Offset = x, Limit = 1000 }).ConfigureAwait(false);
```
and this works perfectly fine.
Any clues?

**Comment by brandonseydel** [comment]
I am starting to look into this.  I wrote a test and it indeed failed.
