### ISSUE TITLE
Merge_field ADDRESS not working

### ISSUE THREAD

**Issue by ShawTEK** [brandonseydel/MailChimp.Net#218]
When adding/Updating member physical address, I get this error:
_Errors: ADDRESS Please enter a complete address

Any ideas as to why this fails?

 
Fiddler:
{"email_address":"cbing@pharmeze.com","email_type":"html","interests":{},"ip_signup":"http://www.empty.net","_links":[],"member_rating":0,"merge_fields":{"FNAME":"Chandler","LNAME":"Bing","SOURCE":"MAR","ORGNAME":"PharmEase Pharmacy","ORGTYPE":"Pharmacy","ADDRESS":{"address1":"1234 E 10th Street","address2":"","city":"Idaho Falls","country":"USA","country_code":"","latitude":0,"longitude":0,"postal_code":"83406","province":"Idaho","province_code":"ID"}},"status":"subscribed","status_if_new":"pending","timestamp_signup":"2017-05-03T23:18:34","vip":false}

===============================================

c#
Address userAddress = new Address
            {
                Address1 =  user.Address1,
                Latitude = 0,
                Longitude = 0,
                Address2 = string.IsNullOrEmpty(user.Address2)?"":user.Address2,
                City = user.City,
                CountryCode = "",
                Country = "USA",
                PostalCode = user.ZipCode,
                Province = "Idaho", //user.State,
                ProvinceCode = "ID" //user.State
            };

            var member = new Member
            {
                EmailAddress = user.EmailAddress,
                Status = Status.Subscribed,
                EmailType = "html",
                IpSignup = "http://www.shawtek.net",
                TimestampSignup = DateTime.UtcNow.ToString("s"),
                MergeFields = new Dictionary<string, object>
                {
                    { "FNAME", user.FirstName }
                    ,{ "LNAME", user.LastName }
                    ,{ "SOURCE", "QuickMAR"}
                    ,{ "ORGNAME", user.OrganizationName}
                    ,{ "ORGTYPE", user.OrganizationType}
                    ,{ "ADDRESS", userAddress}
                }
            };

            return Manager.Members.AddOrUpdateAsync(mailList.Id, member).GetAwaiter().GetResult();

================================

Error:
Title: Invalid Resource
 Type: http://developer.mailchimp.com/documentation/mailchimp/guides/error-glossary/
 Status: 400
 + Detail: Your merge fields were invalid.
Errors: ADDRESS Please enter a complete address[16:24:46][MailChimpInterface_1]      ERRORS: Exception of type 'MailChimp.Net.Core.MailChimpException' was thrown. In StartProcessing();    at MailChimp.Net.Core.Helper.<EnsureSuccessMailChimpAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at MailChimp.Net.Logic.MemberLogic.<AddOrUpdateAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

**Comment by ShawTEK** [comment]
Update: After manually adding the address information in the MailChimp GUI, the error goes away, but, updates to the address do not happen. The return from the Members.AddOrUpdateAsync call brings back the old Address instead of the updated address.

**Comment by ShawTEK** [comment]
MailChimp support reports that this interface is using the wrong parameter names in the address structure.

**Comment by brandonseydel** [comment]
Address is used for customers only.  A merge field will need to abide by whatever object you are trying to store.  This will not be included in the library.  You will need to create a class that represents your object accordingly.

**Comment by ShawTEK** [comment]
Thanks for the clarification.
Where would someone use your MailChimp.Net.Models.Address class?

I am thinking that I need to create a new Address class that abides by the MC API for the client address structure found in their MergeFields spec. 
Thanks

**Comment by brandonseydel** [comment]
Yes you need to create your own class.  The address model is used in various parts related to ecommerce.

Sent from my iPhone

On May 9, 2017, at 9:17 PM, ShawTEK <notifications@github.com<mailto:notifications@github.com>> wrote:


Thanks for the clarification.
Where would someone use your MailChimp.Net.Models.Address class?

I am thinking that I need to create a new Address class that abides by the MC API for the client address structure found in their MergeFields spec.
Thanks
