### ISSUE TITLE
Cannot get a simple batch add to work

### ISSUE THREAD

**Issue by casti004** [brandonseydel/MailChimp.Net#220]
I've tried examples provided to perform a batch add as follows with no success. The code runs but there are no updates or indication that there is a failure. Are there any good documentation or examples for this process?

var users = new List<Member>();
MailChimpManager _mailChimpManager = new MailChimpManager();
_mailChimpManager.Configure(new MailChimpConfiguration { ApiKey = "XXX Our Key" });

var listId = "XXX Our Id";

 var member = new Member { EmailAddress = $"githubTestAccount@test.com", StatusIfNew = Status.Subscribed };

 member.MergeFields.Add("FNAME", "HOLY");
 member.MergeFields.Add("LNAME", "COW");

users.Add(member);

var batchRequest = new BatchRequest
            {
                Operations = users.Select(x => new Operation
                {
                    Method = "PUT",
                    Path = $"/lists/{listId}/members/{_mailChimpManager.Members.Hash(x.EmailAddress.ToLower())}",
                    Body = JsonConvert.SerializeObject(x)
                })
            };

var batch = _mailChimpManager.Batches.AddAsync(batchRequest).Result;

**Comment by brandonseydel** [comment]
It looks good let me see what mail chimp says.

**Comment by casti004** [comment]
I contacted mail chimp and they don't have a clue. When I run it and I check the batchResult.Status, it is always set to "pending" and never goes to a "finished" state.

**Comment by etaletovic** [comment]
I've ran into this issue myself. The issue is that when you serialize Member object all properties get serialized including those you don't set i.e. ClientType and their value gets serialized to null. Mailchimp rejects all requests with 400 code stating that it expects value string but it received null instead. I'll try to get this fixed and create a PR.

**Comment by etaletovic** [comment]
@casti004 you can solve the issue by writing your own custom contract resolver like this:
https://gist.github.com/etaletovic/997ce5b48181687fd320b291ee76a922

**Comment by casti004** [comment]
Hello,

I'm not sure I'm following the example correctly. There is a base class "DefaultContractResolver". Where is that derived from? Is that part of the MailChimp api? If so, where is it located?

I tried this as well with no luck from an example:

        private Operation GetAddOperation(string listId, Member mailChimpMember)
        {
            var subscriberHash = _mailChimpManager.Members.Hash(mailChimpMember.EmailAddress.ToLower());
            var jsonSerializerSettings = new JsonSerializerSettings { NullValueHandling = NullValueHandling.Ignore };

            return new Operation
            {
                Method = Method.PUT.ToString(),
                Path = $"lists/{listId}/members/{subscriberHash}",
                Body = JsonConvert.SerializeObject(subscriberHash, jsonSerializerSettings)
            };
        }

        public async Task<Batch> BatchAddUsersToList(IEnumerable<Member> members, string listId)
        {
            var result = new Batch();
            try
            {
                var addOperations = members.Select(x => GetAddOperation(listId, x));

                var batchRequest = new BatchRequest { Operations = addOperations };

                result = await this._mailChimpManager.Batches.AddAsync(batchRequest);
            }

            catch (MailChimpException ex)
            {
                // log exception
            }

            logger.Info("\r\nBatchAddUsersToList() method ran \r\n");

            return result;
        }

**Comment by casti004** [comment]
I got it working by making sure all of the member values are assigned to something:

       private static Member GetMailChimpMember(Member mbr)
        {
            return new Member
            {
                EmailAddress = mbr.EmailAddress,
                Status = mbr.Status,
                Stats = mbr.Stats,
                StatusIfNew = Status.Subscribed,
                UnsubscribeReason = mbr.UnsubscribeReason,
                TimestampOpt = mbr.TimestampOpt,
                EmailClient = mbr.EmailClient,
                EmailType = mbr.EmailType,
                IpOpt = mbr.IpOpt,
                IpSignup = mbr.IpSignup,
                Language = mbr.Language,
                LastChanged = mbr.LastChanged,
                LastNote = mbr.LastNote,
                Links = mbr.Links,
                Location = mbr.Location,
                MemberRating = mbr.MemberRating,
                MergeFields = mbr.MergeFields,
                TimestampSignup = mbr.TimestampSignup,
                Vip = mbr.Vip
            };
        }

**Comment by etaletovic** [comment]
Yes, you can do that as well. My example assumes you are using Json.NET for serialization.

**Comment by etaletovic** [comment]
@casti004 this worked for me as well. No need to fill in all values. I am using Json.NET for serialization.
https://gist.github.com/etaletovic/528d1f889be6a8731adbb6fd4f1f1ee4
