### ISSUE TITLE
Some vb code that may help someone...

### ISSUE THREAD

**Issue by hookbeak** [brandonseydel/MailChimp.Net#223]
I've been playing around with the wrapper a bit and thought i'd share some functions (vb)  i've written as these seem to answer questions a few people on here have had. They're rough - but work !
`
   ' ## GROUPS AND INTERESTS ####################################################################################################################

    Public Function RemoveSubscriberFromGroup(ListID, GroupCategoryName, GroupName, Email)

        Dim GroupCategoryID = GetGroupCategoryIDbyGroupCategoryName(ListID, GroupCategoryName)
        Dim GroupID = GetGroupIDbyGroupName(ListID, GroupCategoryName, GroupName)

        Try
            Dim mailChimp = New MailChimpManager()

            Dim member = New Member() With {.EmailAddress = Email, .Interests = New Dictionary(Of String, Boolean)() From {{GroupID, False}}}
            Dim transmitResult = mailChimp.Members.AddOrUpdateAsync(ListID, member)

            Return transmitResult.Result.ToString

        Catch ex As MailChimpException

            Return ex.ToString

        End Try

    End Function

    Public Function AssignSubscriberToGroup(ListID, GroupCategoryName, GroupName, Email)

        Dim GroupCategoryID = GetGroupCategoryIDbyGroupCategoryName(ListID, GroupCategoryName)
        Dim GroupID = GetGroupIDbyGroupName(ListID, GroupCategoryName, GroupName)

        Try
            Dim mailChimp = New MailChimpManager()

            Dim member = New Member() With {.EmailAddress = Email, .Interests = New Dictionary(Of String, Boolean)() From {{GroupID, True}}}
            Dim transmitResult = mailChimp.Members.AddOrUpdateAsync(ListID, member)

            Return transmitResult.Result.ToString

        Catch ex As MailChimpException

            Return ex.ToString

        End Try

    End Function

    Public Function CreateGroup(ListID, GroupCategoryName, NewGroupName)

        ' # Working 
        ' # Checks to see if group exists and then creates it if not

        Dim GroupCategoryID = GetGroupCategoryIDbyGroupCategoryName(ListID, GroupCategoryName)

        If DoesGroupExist(ListID, GroupCategoryName, NewGroupName) = False Then

            Dim mailChimp = New MailChimpManager()

            Dim member = New Interest() With {.ListId = ListID, .InterestCategoryId = GroupCategoryID, .Name = NewGroupName}

            Dim transmitResult = mailChimp.Interests.AddOrUpdateAsync(member)
            Return transmitResult.Result

        End If

    End Function

    Public Function GetGroupsCategory(ListID)

        ' WORKING
        ' Lists all group categories

        Dim mailChimp = New MailChimpManager()
        Dim Retval = ""
        Dim mailChimpListCollection As IEnumerable(Of MailChimp.Net.Models.InterestCategory) = mailChimp.InterestCategories.GetAllAsync(listId).Result

        For Each item In mailChimpListCollection

            Retval &= item.Title & " - " & item.Id & "<br>"

        Next

        Return Retval

    End Function

    Public Function GetGroups(ListID, GroupCategoryName)

        ' WORKING
        ' Lists all groups in a specified category

        Dim GroupCategoryID = GetGroupCategoryIDbyGroupCategoryName(ListID, GroupCategoryName)

        Dim mailChimp = New MailChimpManager()
        Dim Retval = ""
        Dim mailChimpListCollection As IEnumerable(Of MailChimp.Net.Models.Interest) = mailChimp.Interests.GetAllAsync(ListID, GroupCategoryID).Result

        For Each item In mailChimpListCollection

            Retval &= item.Name & "(" & item.Id & ")<br>"

        Next

        Return Retval

    End Function

    Public Function DoesGroupExist(listId, GroupCategoryName, GroupName) As Boolean

        ' WORKING
        ' checks if a group exists within a specified group category

        Dim GroupCategoryID = GetGroupCategoryIDbyGroupCategoryName(listId, GroupCategoryName)

        Dim mailChimp = New MailChimpManager()
        Dim mailChimpListCollection As IEnumerable(Of MailChimp.Net.Models.Interest) = mailChimp.Interests.GetAllAsync(listId, GroupCategoryID).Result

        For Each item In mailChimpListCollection

            If item.Name = GroupName Then
                Return True
            End If

        Next

        Return False

    End Function

    Public Function GetGroupIDbyGroupName(ListID, GroupCategoryName, NameofGroupToReturn)

        ' WORKING
        ' Gets Interest ID from Interest Name
        Dim GroupCategoryID = GetGroupCategoryIDbyGroupCategoryName(ListID, GroupCategoryName)

        Dim mailChimp = New MailChimpManager()
        Dim Retval = ""
        Dim mailChimpListCollection As IEnumerable(Of MailChimp.Net.Models.Interest) = mailChimp.Interests.GetAllAsync(ListID, GroupCategoryID).Result

        For Each item In mailChimpListCollection
            If NameofGroupToReturn = item.Name Then
                Return item.Id
            End If
        Next

    End Function

    Public Function GetGroupCategoryIDbyGroupCategoryName(ListID, GroupCategoryName)

        ' WORKING
        ' Returns ID of group category from Group Category name

        Dim mailChimp = New MailChimpManager()
        Dim Retval = ""
        Dim mailChimpListCollection As IEnumerable(Of MailChimp.Net.Models.InterestCategory) = mailChimp.InterestCategories.GetAllAsync(listId).Result

        For Each item In mailChimpListCollection
            If GroupCategoryName = item.Title Then
                Return item.Id
            End If
        Next

        Return Retval

    End Function

    ' ## GENERAL LIST & SUBSCRIBER ################################################################################################################

    Function GetLists()

        ' WORKING
        ' Returns all list names

        Dim Retval = ""
        Dim mailChimp = New MailChimpManager()
        Dim mailChimpListCollection As IEnumerable(Of MailChimp.Net.Models.List) = mailChimp.Lists.GetAllAsync(New ListRequest() With {.Limit = "50"}).Result

        For Each item In mailChimpListCollection
            Retval &= item.Name & "<br>"
        Next

        Return Retval

    End Function

    Function GetSubscribers(ListID)

        ' WORKING
        ' Gets all subscribers in a list

        Dim Retval = ""
        Dim mailChimp = New MailChimpManager()
        Dim mailChimpListCollection As IEnumerable(Of MailChimp.Net.Models.Member) = mailChimp.Members.GetAllAsync(ListID).Result

        For Each item In mailChimpListCollection
            Retval &= item.EmailAddress & "<br>"
        Next

        Return Retval

    End Function

    Function NewSubscriber(ListID, Email, isCustom)

        ' WORKING
        ' Adds a new subscriber

        Dim mailChimp = New MailChimpManager()
        Dim member = New Member() With {.EmailAddress = Email, .StatusIfNew = Status.Subscribed}
        member.MergeFields.Add("FNAME", "HOLY")
        member.MergeFields.Add("LNAME", "COW")
        member.MergeFields("CUSTOMMERGEFIELD") = isCustom

        Dim transmitResult = mailChimp.Members.AddOrUpdateAsync(ListID, member)
        Return transmitResult.Result.Status

    End Function

    Function UpdateSubscriber(ListID, Email, Firstname, Surname, isCustom)

        ' WORKING
        ' Updates a members details (error if member not found)

        Dim mailChimp = New MailChimpManager()
        Dim listMember = mailChimp.Members.GetAsync(ListID, Email).Result
        listMember.MergeFields("FNAME") = Firstname
        listMember.MergeFields("LNAME") = Surname
        listMember.MergeFields("CUSTOMMERGEFIELD") = isCustom

        Dim transmitResult = mailChimp.Members.AddOrUpdateAsync(ListID, listMember)

        Return transmitResult.Result.Status

    End Function

    ' ### SEGMENTS ################################################################################################################################

    Public Function GetSegmentIdBySegmentNameAsync(listId, interestName)

        ' WORKING
        ' Gets Interest ID from Interest Name

        Dim mailChimp = New MailChimpManager()

        Dim mailChimpListCollection As IEnumerable(Of MailChimp.Net.Models.ListSegment) = mailChimp.ListSegments.GetAllAsync(listId).Result
        For Each item In mailChimpListCollection
            If interestName = item.Name Then
                Return item.Id
            End If
        Next

    End Function

    Function GetSegments(ListID)

        ' WORKING
        ' lists segments for a selected list, plus member count

        Dim Retval = ""
        Dim mailChimp = New MailChimpManager()
        Dim mailChimpListCollection As IEnumerable(Of MailChimp.Net.Models.ListSegment) = mailChimp.ListSegments.GetAllAsync(ListID).Result
        For Each item In mailChimpListCollection
            Retval &= item.Id & " -" & item.Name & " (" & item.MemberCount & ")<br>"
        Next
        Return Retval

    End Function

`

**Comment by stuartp22** [comment]
Thanks for this.  It has helped me as my project is VB.net based.

Have you tried setting up batches with MailChimp.net in VB ?  I've tried converting the C# code to VB.net and to be honest am getting nowhere.  The problem seems to be setting an operation and then assigning it to a BatchRequest.

Would be grateful for any suggesions.

Thanks.

**Comment by hookbeak** [comment]
I'm stuck with batching too - i'll post my code if i get anywhere!

**Comment by stuartp22** [comment]
Thanks.  I'll do likewise!

The problem I think I'm having is that I can't seem to work out the VB. net equivalent of this construct:

`var batchRequest = new BatchRequest
            {
                Operations = users.Select(x => new Operation
                {
                    Method = "PUT",
                    Path = $"/lists/{listId}/members/{_mailChimpManager.Members.Hash(x.EmailAddress.ToLower())}",
                    Body = JsonConvert.SerializeObject(x)
                })
            };`

The code I've tried is

`Dim op As New Operation
        op.OperationId = "OP123"
        op.Method = "PUT"
        op.Path = "/stores/D4D01/products"
        op.Body = jsonProd

        Dim br As New BatchRequest

        br.Operations = op`

But this gives me an error of

> System.InvalidCastException: 'Unable to cast object of type 'MailChimp.Net.Core.Operation' to type 'System.Collections.Generic.IEnumerable`1[MailChimp.Net.Core.Operation]'.'

And I'm not really sure where to go from there.

I had thought of trying to get a C# example I found to work and then just building it as a DLL for my VB.net project.  Unfortunately it seems a bit incomplete (the JSON serialiser leaves a lot of null values which MailChimp doesn't like) and it doesn't help that my current working knowledge of C# is (I'm rather ashamed to say) pretty rudimentary at this point.

Happy to keep comparing notes and see if we can crack this?

**Comment by xt0rted** [comment]
It's been long enough that I don't remember how to write vb.net, but according to http://converter.telerik.com/ the equivalent of that c# code would be something like the following.
```vbnet
Dim batchRequest = New BatchRequest() With { _
	Key .Operations = users.[Select](Function(x) New Operation() With { _
		Key .Method = "PUT", _
		Key .Path = "/lists/{listId}/members/{_mailChimpManager.Members.Hash(x.EmailAddress.ToLower())}", _
		Key .Body = JsonConvert.SerializeObject(x) _
	}) _
}
```

**Comment by stuartp22** [comment]
I tried the Telerik converter also, but it doesn't seem to produce valid VB.net syntax in this case.  It fails at the first { bracket and the compiler does not like the 'Key' keyword.

I think the only way around this is to spend however long plugging gaps in my knowledge i.e. with C# and Linq, or else to leave this for now and as I only want MailChimp for remarketing emails at the moment, write something myself using Azure scheduler.  Problem is I'm up against a deadline so #2 is looking increasingly attractive right now.

I'm convinced its a problem with data typing (converting a MailChimp operation type to an IEnumerable) but the more I try with it the less progress I seem to make :(

**Comment by brandonseydel** [comment]
https://www.tangiblesoftwaresolutions.com/ will do it perfectly for you. (they accept new syntax)  They have a free trial.
