### ISSUE TITLE
How do I retreive ListActivities?

### ISSUE THREAD

**Issue by gewra** [brandonseydel/MailChimp.Net#226]
I'm struggling to find a way to retreive a lists activity.
I can't seem to find any references to the ListActivity class in the source as well, is it not implemented yet?

 I would assume fetching the activities via `_mailchimpManager.Activities.GetAllAsync("my-list-id")` would respond with an `IEnumerable<ListActivity>` but instead I recieve a list (with the appropriate amount of activities for the list) of "Activity":ies where all the properties is null.

**Comment by salesoutlook** [comment]
I am having a similar issue 
Await manager.Members.GetActivitiesAsync(Listid, MemberId)
I have a valid list id and member id but I do not get any results from getActivitiesAsync
My count shows zero but Mailchimp shows history.
