### ISSUE TITLE
Batch add/remove list members to static segment

### ISSUE THREAD

**Issue by sxbo672158** [brandonseydel/MailChimp.Net#231]
Per [Mailchimp's API documentation](http://developer.mailchimp.com/documentation/mailchimp/reference/lists/segments/#create-post_lists_list_id_segments_segment_id), there's a way to batch add/remove members to a segment. I can't find same functionality in this library. 

Is it implemented already?

**Comment by abnet3** [comment]
Did you solve this problem? I am facing this exact issue too.
