### ISSUE TITLE
Can't delete members that are unsubscribed or cleaned

### ISSUE THREAD

**Issue by casti004** [brandonseydel/MailChimp.Net#236]
We have a list that has hard bounced users that go to a cleaned status as well as those that have unsubscribed. We simply want to delete those members from the list.

I am trying the following, which can delete a subscribed member ok, but not cleaned or unsubscribed:
        
public async Task DeleteUserFromList(Member memberToDelete, string listId)
        {
            try
            {
                    await
                        this._mailChimpManager.Members.DeleteAsync(
                            listId,
                            memberToDelete.EmailAddress);
                }
            }
            catch (MailChimpException ex)
            {
                // log exception
            }
        }

**Comment by brandonseydel** [comment]
Can you write a test method or merge one into the solution?
