### ISSUE TITLE
Adding Products

### ISSUE THREAD

**Issue by stuartp22** [brandonseydel/MailChimp.Net#238]
Please can someone clarify how to add products to Mailchimp using MailChimp.net?

I have tried setting up as follows:

```
Product mcProd=new Product();
Variant mcVar = new Variant();

mcProd.Id = "C000755";
mcProd.Title = "Bin Bags";
mcVar.Id = "C000755";
mcVar.Title = "bin bags";
mcProd.Variants.Add(mcVar);
```
and get the message
> System.NullReferenceException: 'Object reference not set to an instance of an object.'

What have I missed ?

Thanks

**Comment by brandonseydel** [comment]
Variants is not initialized to an empty enumerable.

```csharp

mcProd.Variants = new List<Variant>{
mcVar
}
```
