### ISSUE TITLE
Updating Content HTML

### ISSUE THREAD

**Issue by philoushka** [brandonseydel/MailChimp.Net#239]
I've created campaigns successfully via the API, but now I'd like to replace some HTML. Turns out my users have typos, and we just want to do a string replace and update the unsent campaign's HTML. I used a custom template.

`await mailChimpManager.Content.AddOrUpdateAsync(campaignId, new ContentRequest { Html = html});`

This call succeeds. I then refresh the campaign URL in the browser, and voila, MailChimp appears to have taken the update.

However, if you then go into the MailChimp web UI, and edit that campaign, the changes made by the API have disappeared.

What can I do to make my campaign's HTML changes stick when using `mailChimpManager.Content.AddOrUpdateAsync()`?

**Comment by philoushka** [comment]
Has anyone successfully updated campaign HTML using MailChimp.Net?

**Comment by tombille** [comment]
@philoushka Any luck?
