### ISSUE TITLE
System.Net.Http.Formatting Error

### ISSUE THREAD

**Issue by brandonturpin** [brandonseydel/MailChimp.Net#241]
When trying to add an email to a list I am getting a thrown exception "System.Net.Http.Formatting" I have mailchimpexception catch as well but it skips and goes to the general exception.

The problem is System.Net.Http.Formatting as far as I have been able to tell is not available on ASP.Net Core?

**Comment by untipoahi** [comment]
Same issue here

**Comment by brandonturpin** [comment]
Hmm... I wish we were given some kind of response before there issue was closed!

**Comment by brandonseydel** [comment]
The previous version was not asp.net core capable, but now it is so it should resolve your issue.
