### ISSUE TITLE
Campaign Preview Text

### ISSUE THREAD

**Issue by philoushka** [brandonseydel/MailChimp.Net#242]
MailChimp has moved the campaign's preview text to be an attribute on the campaign settings.

I've sent an email question into the API Help team, asking when it'll be available via the MC API.

I'll update this issue once they confirm whether this property will be supported in the API.

![new placement preview text](https://user-images.githubusercontent.com/930731/28166786-26090c4a-678e-11e7-98e8-3e33cc8f9faa.jpg)

**Comment by gedumas** [comment]
@philoushka check out workaround by Litmus in the mean time: https://litmus.com/blog/the-ultimate-guide-to-preview-text-support

**Comment by thomasz-nyt** [comment]
Guys, I just found In MailChimp API playgroud, the Preview Text key is listed there, not in API documentation yet.

`"settings": {
		"subject_line": "",
		"preview_text": "",
		"title": "",
		"from_name": "",`

**Comment by philoushka** [comment]
The `preview_text` is available in the MailChimp 3.0 API.

https://developer.mailchimp.com/documentation/mailchimp/reference/campaigns/
