### ISSUE TITLE
Include extra MailChimpException informtion in the Data dictionary

### ISSUE THREAD

**Issue by xt0rted** [brandonseydel/MailChimp.Net#243]
When logging instances of [MailChimpException](https://github.com/brandonseydel/MailChimp.Net/blob/4155f19a061c0be47efaa40623a9f866a78ffe64/MailChimp.Net/Core/MailChimpException.cs) I'm not getting any of the extra response data included. If this information was part of the `Data` dictionary on the exception then services like [Raygun](https://raygun.com/), [StackExchange.Exceptional](https://github.com/NickCraver/StackExchange.Exceptional), and possibly Application Insights would include this as part of the logged exception.

Are you open to a PR that includes this information in the `Data` dictionary as well?

For now I've had to wrap my calls like so to get the information.
```csharp
private async Task AddOrUpdateMember(string listId, Member member)
{
    try
    {
        await _mailChimpManager.Members.AddOrUpdateAsync(listId, member);
    }
    catch (MailChimpException ex)
    {
        ex.Data["Type"] = ex.Type;
        ex.Data["Title"] = ex.Title;
        ex.Data["Status"] = ex.Status;
        ex.Data["Detail"] = ex.Detail;
        ex.Data["Instance"] = ex.Instance;
        ex.Data["Errors"] = ex.Errors;

        throw;
    }
}
```

**Comment by brandonseydel** [comment]
Yes please submit

Sent from my iPhone

On Jul 28, 2017, at 8:21 PM, Brian Surowiec <notifications@github.com<mailto:notifications@github.com>> wrote:


When logging instances of MailChimpException<https://github.com/brandonseydel/MailChimp.Net/blob/4155f19a061c0be47efaa40623a9f866a78ffe64/MailChimp.Net/Core/MailChimpException.cs> I'm not getting any of the extra response data included. If this information was part of the Data dictionary on the exception then services like Raygun<https://raygun.com/>, StackExchange.Exceptional<https://github.com/NickCraver/StackExchange.Exceptional>, and possibly Application Insights would include this as part of the logged exception.

Are you open to a PR that includes this information in the Data dictionary as well?

For now I've had to wrap my calls like so to get the information.

private async Task AddOrUpdateMember(string listId, Member member)
{
    try
    {
        await _mailChimpManager.Members.AddOrUpdateAsync(listId, member);
    }
    catch (MailChimpException ex)
    {
        ex.Data["Type"] = ex.Type;
        ex.Data["Title"] = ex.Title;
        ex.Data["Status"] = ex.Status;
        ex.Data["Detail"] = ex.Detail;
        ex.Data["Instance"] = ex.Instance;
        ex.Data["Errors"] = ex.Errors;

        throw;
    }
}
