### ISSUE TITLE
Trying to add members to list without sending confirmation email

### ISSUE THREAD

**Issue by adamCitrusLime** [brandonseydel/MailChimp.Net#251]
I've been using your API to integrate with our commerce platform. I'm trying to add a member to a list without sending a confirmation email to the user. From what I've seen, I need to set the status of the new member to Status.Subscribed. I've done this but I'm still seeing confirmation emails being sent to members.

Is there another setting I need to use to prevent this?

Thanks.

**Comment by schiari** [comment]
I have the same problem.
Did someone find a solution for this ?

**Comment by manicfiddler** [comment]
Are you using StatusIfNew?  That is the property to set the Status for new list members

**Comment by adamCitrusLime** [comment]
I've been using that property as well (I found another thread with same issue) and find if I use just that field or both at the same time. Then nothing happens.

**Comment by schiari** [comment]
I've tried with "StatusIfNew = Status.Subscribed" and it works fine: it doesn't send confirmation email.
However if a member is already Unsubscribed, the "StatusIfNew = Status.Subscribed" doesn't set the status back to Subscribed.
The solution I've found is: 
For subscribe use always both ".Status = Status.Subscribed, .StatusIfNew = Status.Subscribed"
For unsubscribe use only "Status = Status.Unsubscribed"
In this way it works fine: I can Subscribe without sending the confirmation email, then Unsubscribe and then Subscribe again without sending the confirmation email.
I can switch to Subscribe and Unsubscribe as many time as I want and it looks working fine.
Does anybody see any problem using it in this way ?

**Comment by adamCitrusLime** [comment]
My code seems to be working as required now.
My personal email wasn't getting pulled through, although I suspect this will be due to some validation on Mailchimp's end to prevent spamming the same emails to a list over and over again.

Thanks for the help.
