### ISSUE TITLE
Nuget install/update for version 3.0.0

### ISSUE THREAD

**Issue by terryapodaca** [brandonseydel/MailChimp.Net#252]
I was using an older version of this DLL in my ASP.NET MVC project and it worked great!!! We are in the process of upgrading the website and I can't upgrade or install your latest version 3.0.0 via the Nuget Package Manager. I get this error:

'MailChimp.Net.V3' already has a dependency defined for 'Microsoft.Extensions.Configuration.FileExtensions'.

![image](https://user-images.githubusercontent.com/518469/30393337-5a78b5fc-9885-11e7-9508-7eb046735ee7.png)

**Comment by terryapodaca** [comment]
Rider?

**Comment by brandonseydel** [comment]
The IDE from JetBrains.
________________________________

**Comment by terryapodaca** [comment]
No, MS Visual Studio, the full version, not VS Code.

**Comment by terryapodaca** [comment]
Any update on if/when this will be fixed?

**Comment by brandonseydel** [comment]
I cannot reproduce please zip up a sample or something so I can look.

**Comment by ctolkien** [comment]
@terryapodaca  - what version of VS are you using?

**Comment by terryapodaca** [comment]
@brandonseydel I attached the screenshot in the original post. I don't know what else to provide...other than...

@ctolkien this particular project is using VS 2012 (I know, a little old but still very widely used ATM).

**Comment by ctolkien** [comment]
VS 2012 Nuget does not support projects targeting NetStandard:
https://github.com/NuGet/Home/issues/3131

Looks like there are some workarounds posted in that thread to use the Package Manager console to install an explicit version.
