### ISSUE TITLE
Configuration doesn't work with Dependency Injection

### ISSUE THREAD

**Issue by juliavi** [brandonseydel/MailChimp.Net#253]
I've registered IMailChimpManager in the Startup class (MVC Core)
And tried to configure the Api key like someone suggested on another issue:
```
services.AddScoped<IMailChimpManager, MailChimpManager>();
serviceProvider.GetService<IMailChimpManager>().Configure(x => x.ApiKey = "MyKey");
```
 Then tried to add a member:
```
var member = new Member { EmailAddress = "email", StatusIfNew = Status.Subscribed };
await _mailChimpManager.Members.AddOrUpdateAsync(listId, member);
```
But I'm stil getting this error
'Invalid URI: The hostname could not be parsed.'
This means that I didn't configure the api-key correctly.
Any ideas how to do it with dependency injection in MVC Core?

**Comment by Jetski5822** [comment]
```c#
services.AddMailChimpClient((options) => {
	options.ApiKey = "MyKey";
)
```

**Comment by IT-VBFK** [comment]
> You should never need to register the dependencies like this, you can just use the convenience method like below.
> 
> ```cs
> services.AddMailChimpClient("MyKey");
> ```

Ähhmm.. I do.. because the extension `.AddMailChimpClient()` could not be found. 

Even if I add `using Mailchimp.Net;`

**Comment by irinamirici** [comment]
I have the same issue: `.AddMainChimpClient()` cannot be found even when I add `using MailChimp.Net;`
I think the problem is that the extension is available under this directive:
```
#if NET_CORE
```
And .NET 7 doesn't appear to be considered NET_CORE when the constant is defined:
```
    <PropertyGroup Condition="'$(TargetFramework)' == 'netstandard1.3' Or '$(TargetFramework)' == 'netstandard1.4' Or '$(TargetFramework)' == 'netstandard1.5' Or '$(TargetFramework)' == 'netstandard1.7' Or '$(TargetFramework)' == 'netstandard1.8' Or '$(TargetFramework)' == 'netstandard1.9' Or '$(TargetFramework)' == 'netstandard2.0' Or '$(TargetFramework)' == 'netcoreapp1.0' Or '$(TargetFramework)' == 'netcoreapp1.1' Or '$(TargetFramework)' == 'netcoreapp2.0' Or '$(TargetFramework)' == 'netcoreapp2.1' Or '$(TargetFramework)' == 'netcoreapp2.2'">
        <DefineConstants>NET_CORE</DefineConstants>
    </PropertyGroup>
```


The parameterless constructor is not available for DI.

How should we register `IMailChimpManager` in a DI container?  Thank you.
