### ISSUE TITLE
.GetTotalItems() doesn't report subscriber count correctly

### ISSUE THREAD

**Issue by eldavido** [brandonseydel/MailChimp.Net#256]
```
        public override void Run() {
            // Looks like .GetTotalItems(MailMailchimpListId, Status.Subscribed) has a bug?
            var countTask = _mcm.Members.GetTotalItems(MainMailchimpListId, Status.Subscribed);
            countTask.Wait();
            Console.WriteLine(countTask.Result);  // Prints "0"

            var allListTask = _mcm.Members.GetAllAsync(MainMailchimpListId);
            allListTask.Wait();
            var subscribedCount = allListTask.Result.Count(x => x.Status == Status.Subscribed);
            Console.WriteLine(subscribedCount);  // Prints "3"
        }
```

This outputs "0" then "3". Shouldn't these counts be the same?

I'm willing to fix this, just not right at this second...let me know if anyone else has a similar issue, or there's a known problem with the serialization of "Status.Subscribed" (my guess of the problem)?

**Comment by unrealjdv** [comment]
I have the same problem with GetAllAsync requests that specify any status in the MemberRequest.
This should return 2 but returns 0, if I omit the Status parameter the 2 pending records appear in the list:

`var pendingMembers = mcm.Members.GetAllAsync(listId, new MemberRequest { Limit = 100, Status = Status.Pending}).Result;`
