### ISSUE TITLE
Adding Status as Status.Subscribed still shows Pending in mailchimp

### ISSUE THREAD

**Issue by mandarsj** [brandonseydel/MailChimp.Net#257]
If I add new Member using Status=Status.Subscribed . the new member in mailchimp list still shows as status pending

**Comment by brandonseydel** [comment]
Please set the StatusIfNew property.  Don't ask why mailchimp did that.  I have had at least 50 issues involving this.

**Comment by mandarsj** [comment]
Thanks!

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
