### ISSUE TITLE
Creating and Sending Campaigns?

### ISSUE THREAD

**Issue by Chaddeus** [brandonseydel/MailChimp.Net#259]
Are there any examples of creating and sending campaigns using this library?

Thanks!

**Comment by brandonseydel** [comment]
https://github.com/brandonseydel/MailChimp.Net/blob/master/MailChimp.Net.Tests/CampaignTest.cs

**Comment by Chaddeus** [comment]
From what I've scrounged up from other libraries, it appears to be three steps:

1) Create the campaign

2) Add content to the campaign

3) Send the campaign

Using this C# library, I see how to new up a campaign and create it in MailChimp: `await _mailChimpManager.Campaigns.AddAsync(newCampaign);`

And sending it looks simple: `await _mailChimpManager.Campaigns.SendAsync(campaign.Id);`

But how do I add content to the campaign? I don't see a `campaign.Content` property.

**Comment by Chaddeus** [comment]
I think I may have found it. Is this the correct way to add content to a campaign?

```
await _mailChimpManager.Content.AddOrUpdateAsync(campaign.Id, new MailChimp.Net.Core.ContentRequest()
{
    Html = $""
});
```

**Comment by ninalamo** [comment]
Hi! I tried using SendAsync but my tests failed stating that the 

> email/message is currently being sent

. Can you advise on this? Thanks :)

**Comment by xavierpena** [comment]
I've finally found how to create and send a campaign.

Disclaimer: I am not 100% sure about how "template" works... I might update this post later.

This is the full script: 

	public static void CreateAndSendCampaign(string emailHtmlContent)
	{
		var mailChimpManager = new MailChimpManager(ApiKey);

		var lists = mailChimpManager.Lists.GetAllAsync().Result.ToList();
		var listId = lists.First().Id;

		var templates = mailChimpManager.Templates.GetAllAsync().Result.ToList();
		var templateId = templates.First().Id;

		// Add new campaign:
		var campaign = mailChimpManager.Campaigns.AddAsync(new Campaign
		{
			Settings = new Setting
			{
				ReplyTo = "replyto@email.com",
				FromName = "NameVisibleToRecipient",
				Title = $"Your campaign name (created on: {DateTime.Now})",
				SubjectLine = "The email subject",
				TemplateId = templateId
			},
			Recipients = new Recipient { ListId = listId },
			Type = CampaignType.Regular
		}).Result;

		// Add content:
		var content = mailChimpManager.Content.AddOrUpdateAsync(
				campaign.Id, 
				new ContentRequest() { Html = emailHtmlContent }
			).Result;
					
		// Send campaign:
		mailChimpManager.Campaigns.SendAsync(campaign.Id).Wait();
	}

**Comment by sureshkumar10** [comment]
Check this out - Full code and detailed explanation is given in this blog about creating Audience, Subscribers, sending Campaign with Email Template, and also generating reports by using MailChimp v3.0 API.  All code works very well. 

https://www.codeindotnet.com/how-to-integrate-mailchimp-v3-0-api-in-dotnet-core-c/

Thanks :)
