### ISSUE TITLE
Re-adding user from my database 

### ISSUE THREAD

**Issue by JonTanyag** [brandonseydel/MailChimp.Net#263]
Hi, if let's say I have a User database, and on my webapp I can delete a user account, what i did is whenever I delete an account i tagged that user on mailchimp as Unsubscribe but when I try to add that user again on my database, that user is still Unsubscribe on mailchimp, 
this is the behavior I encounter :
 - Delete from database
 - Unsubscribe on MailChimp
next process
 - Add the same user on my database
 - execute 
`    var member = new Member { EmailAddress = model.Email, StatusIfNew = Status.Subscribed };
     await this.mailChimpManager.Members.AddOrUpdateAsync(listId, member);`
 - No changes on MailChimp

Or is there a way to check if user is existing on the list in mailchimp?

Kindly advise on this

**Comment by justSteve** [comment]
A similar question. I'm moving members from one list to several smaller, new lists. I'm explicitly setting the status: 
                        newMember.Status = Status.Subscribed;

The status is instead 'Status.Pending'. If I run the import a 2nd time, status is updated correctly. Nothing in MC's docs suggests they'd be overriding things.
