### ISSUE TITLE
MailChimp.Net.V3.Core nuget package is outdated

### ISSUE THREAD

**Issue by GermanGlushkov** [brandonseydel/MailChimp.Net#264]
Hi, 
first of all  - appreciate your work very much. 
Would it be possible to publish updated MailChimp.Net.V3.Core nuget package? I'm using it in my .net 4.5.2 project because it works (if I build it from source code) and it doesn't require any dependencies (as opposed to MailChimp.Net.V3 nuget package which brings tons of dependent packages.
Thanks!

**Comment by ctolkien** [comment]
That package has been built by someone else. It may have started life from this project, but who knows what is in it:
![image](https://user-images.githubusercontent.com/515955/32682849-7744b82e-c6cb-11e7-926b-c9044d0f1e6a.png)

**Comment by brandonseydel** [comment]
A new release is going this weekend which fixes the dependency problem.

**Comment by ctolkien** [comment]
FYI @brandonseydel  - I have a fork which splits the project into two nuget packages - putting the ASP.Net Core DI/config functionality into it's own package `MailChimp.Net.AspNetCore` (so doesn't wear the additional dependencies when not running in that environment). 

Ready to PR if you want.

**Comment by brandonseydel** [comment]
I will have one package that works for both going out tomorrow.

**Comment by brandonseydel** [comment]
with no dependencies on the full framework side

**Comment by brandonseydel** [comment]
Please try out the latest prerelease.  Let me know how it goes.

**Comment by GermanGlushkov** [comment]
Thanks Brandon, pulled 3.1.1-alpha and in my case it works as expected
