### ISSUE TITLE
InterestsCategory ListId and Id always null valued

### ISSUE THREAD

**Issue by Hokenh** [brandonseydel/MailChimp.Net#27]
Calling MailChimpManager.InterestCategories.GetAllAsync with a valid ListId returns an IEnumerable<InterestCategory>, with null ListId and Id properties. Adding private setters on both properties solves this issue. Check PR #25

**Comment by brandonseydel** [comment]
9da9150ed0e17eebbd402c889c2efd3b0d5de659
