### ISSUE TITLE
Discount missing on order and line models

### ISSUE THREAD

**Issue by Viktor-G-Ignite** [brandonseydel/MailChimp.Net#279]
Hi,

Fields for discount is missing on the Order (discount_total) and Line (discount) model classes.
I tried to make my own fork to fix this issue but I'm having issues with the extra .net core dependencies (thay crash my project...) #270 . Are the changes for 3.1.1-alpha in github?

/Viktor

**Comment by NansenViktor** [comment]
Hi,

Order url (order_url) is also missing.

/Viktor
