### ISSUE TITLE
Exception Catching

### ISSUE THREAD

**Issue by cvillard** [brandonseydel/MailChimp.Net#282]
Is there a good example of catching exceptions? I noticed that I can use a try/catch but it doesnt seem to catch all exceptions. For instances when adding a new member I can use a try/catch with the catch being a MailChimpException however if say the API key is wrong, this never falls into the catch and an exception occurs that is not caught and therefore is not handled. Hopefully this makes sense and I am just missing something...

**Comment by seraphx2** [comment]
If you are saying there is a literal .NET Exception but MailChimpException is simply not catching it, that means it's probably a generic Exception.  Just add another catch under the MailChimpException to handle it.

```
try {

}
catch (MailChimpException ex)
{

}
catch (Exception ex)
{

}

**Comment by cvillard** [comment]
That did it, I am not quite sure was I was overthinking that... Thank you!

And yes, when your API key is wrong or your listId, it seems to throw a .NET Exception rather than a MailChimp Exception. I just wanted to make sure I am trapping anything that can happen for my log system
