### ISSUE TITLE
Trouble with Unschedule

### ISSUE THREAD

**Issue by Noctivagan** [brandonseydel/MailChimp.Net#290]
I want to change the schedule of a future campaign. According to MailChimp, I need to Unschedule before I can reschedule. A call to await manager.Campaigns.ExecuteCampaignActionAsync(Campaign.Id, CampaignAction.Unschedule); results in a Object reference not set to an instance of an object at MailChimp.Net.Logic.CampaignLogic.<ExecuteCampaignActionAsync>d__13.MoveNext()  . Is there something I am missing?

**Comment by peterdremstrup** [comment]
I just made a pull request (https://github.com/brandonseydel/MailChimp.Net/pull/306) to add the unschedule function to campaign logic, so you can use it like the schedule call:
```
await manager.Campaigns.UnscheduleAsync(Campaign.Id, null);
```
