### ISSUE TITLE
Cannot open in VS2015

### ISSUE THREAD

**Issue by jordanhammond** [brandonseydel/MailChimp.Net#292]
Is there any ability to support this?

I included the nuget release into a 4.6.1 project but it pulled 58 dependency packages.  This is not really a viable option, it's unclear why there would be any dependencies required for this.

**Comment by xt0rted** [comment]
Sounds like the same complaint I had in #270. Try installing the [3.1.1-alpha](https://www.nuget.org/packages/MailChimp.Net.V3/3.1.1-alpha) release. That removed the dependency on some .net core interfaces which aren't needed for non-core projects.
