### ISSUE TITLE
OAuth support

### ISSUE THREAD

**Issue by HakanL** [brandonseydel/MailChimp.Net#301]
Is OAuth supported? I can't seem to get it to work, it seems that the options class is hard coded to send ApiKey.

**Comment by gdycus** [comment]
I have the latest version of the library and when I pass datacenter and oauthtoken I get the following error every time. Thoughts?

Title: User action not permitted
Type: http://developer.mailchimp.com/documentation/mailchimp/guides/error-glossary/
Status: 403
Detail: User does not have access to the requested operation
Errors:
