### ISSUE TITLE
error

### ISSUE THREAD

**Issue by materdebater** [brandonseydel/MailChimp.Net#307]
hey Brandon, using nuget to install , im getting below error
Could not install package 'MailChimp.Net.V3 3.2.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.0,Profile=Client', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author. im on VS2010 with .net 4.5

**Comment by brandonseydel** [comment]
You need to update your .net framework version in your project fike

________________________________
