### ISSUE TITLE
Batch update list

### ISSUE THREAD

**Issue by larschanders** [brandonseydel/MailChimp.Net#31]
Hi,

Im trying to do a batch update of users in a list with the help of your wrapper but I quite don't understand how to do it. 

Any advice?

**Comment by mbuenoferrer** [comment]
I have also tried unsuccessfully understand how to use batch operations, any help? thanks

**Comment by brandonseydel** [comment]
@manicfiddler Can you help them out here I think you have used batches quite extensively.

**Comment by brandonseydel** [comment]
var batch = new BatchRequest{Operations = users.Select(x=> new Operation{ Method = "PUT", Path = "/lists/{listId}/members/{Hash(member.EmailAddress.ToLower())}", Body = JsonConvert.Serialize(x))};

**Comment by manicfiddler** [comment]
Yes that's about the size of it.  Make sure you are using the latest version of the wrapper as batch operations were not working at all before 1.4.2.

Make sure you use StatusIfNew on your members rather than Status to make sure you don't overwrite unsubscribes!

**Comment by jasenf** [comment]
I'm also lost on how to use batch operations.  I've coded the above suggestion, but can not find access to the .Batch interface from within the MailChimpManager.

**Comment by larschanders** [comment]
@jasenf: I had the same problem. Make sure to use MailChimpManager and not IMailChimpManager. With the latter you can't use Batches.

**Comment by brandonseydel** [comment]
Batches has been added to the latest version.

**Comment by gabrielrobert** [comment]
I'm still trying to batch add/update members, but it is not working as expected. Any thought on this?

```
using (var md5 = MD5.Create())
            {
                var batchRequest = Manager.Batches.AddAsync(new BatchRequest
                {
                    Operations = members.Select(x => new Operation
                    {
                        Method = "PUT",
                        Path = String.Format(
                            "/lists/{0}/members/{1}",
                            listId,
                            md5.GetHash(x.EmailAddress.ToLower())
                        ),
                        Body = JsonConvert.SerializeObject(x)
                    })
                });
            }
```

**Comment by brandonseydel** [comment]
Does it do nothing or does something happen unexpected?

Date: Mon, 15 Aug 2016 11:00:18 -0700

**Comment by larschanders** [comment]
I'm not sure you can create the MD5 like that. Look at my code below, it works fine.

`public async Task<Batch> DeleteUsers(IEnumerable<User> users)
        {
            var batchRequest = new BatchRequest
            {
                Operations = users.Select(user => new Operation
                {
                    Method = "DELETE",
                    Path = String.Format("/lists/{0}/members/{1}", _listId, CreateMD5(user.Email.ToLower()))
                })
            };

            var batch = await _mailChimpManager.Batches.AddAsync(batchRequest);
            return batch;
        }

        private string CreateMD5(string input)
        {
            using (System.Security.Cryptography.MD5 md5 = System.Security.Cryptography.MD5.Create())
            {
                byte[] inputBytes = Encoding.ASCII.GetBytes(input);
                byte[] hashBytes = md5.ComputeHash(inputBytes);

                StringBuilder sb = new StringBuilder();
                for (int i = 0; i < hashBytes.Length; i++)
                {
                    sb.Append(hashBytes[i].ToString("X2"));
                }
                return sb.ToString().ToLower();
            }
        }`
