### ISSUE TITLE
AddOrUpdateAsync with new required merge field - Question

### ISSUE THREAD

**Issue by AprilKulpa** [brandonseydel/MailChimp.Net#312]
Hi - 
I am really new to all this, so please forgive me if I am asking a dumb question.

I just added a new required merge field, so any new subscriber must click on a radio button indicating they've read our privacy policy.  The existing 235,000 folks don't have anything for this merge field.  

When I try to use AddOrUpdateAsync on an existing member, it is throwing an error that the merge field is invalid.  Is there any way to update existing member when you decide to add a new required merge field and you don't want to update that merge field?

**Comment by brandonseydel** [comment]
don't include it when updating?

**Comment by AprilKulpa** [comment]
Hi –
Thanx for responding!

It looks like a required field MUST be included in the API or it won’t work?!?!
Which is too bad, because when importing manually I don’t have to include it.
Is that something worth looking into for an update?

For now, we just made the field NOT required.

April L. Kulpa, CPA
Programming Services
The University of Connecticut Foundation, Inc.
2390 Alumni Drive
Storrs, CT 06269
• 860.486.0254 | • akulpa@foundation.uconn.edu<mailto:akulpa@foundation.uconn.edu>
[Description: Description: cid:image001.png@01CE937C.B8F7FA10]
Strengthening UConn One Relationship at a Time

**Comment by brandonseydel** [comment]
Yes we can retrieve the merge fields and diff them into one dictionary to add missing ones perhaps?
