### ISSUE TITLE
can not use FolderId with the function FileManagerFiles.AddAsync()

### ISSUE THREAD

**Issue by wahid248** [brandonseydel/MailChimp.Net#313]
Hello,

In the namespace "MailChimp.Net.Interfaces.IFileManagerFileLogic"
I am trying to use this function:

> `Task<FileManagerFile> AddAsync(string name, string folderId, Stream fileStream)`

Everything works fine but whenever I try to put a valid FolderId (string) it gives an error that FolderId is expected to be an integer but string is provided. The functions parameter is asking for string so I gave string. Here is the JSON of the complete error:

{
    "Message": "An error has occurred.",
    "ExceptionMessage": "Title: Invalid Resource\r\nType: http://developer.mailchimp.com/documentation/mailchimp/guides/error-glossary/\r\nStatus: 400\r\nDetail: The resource submitted could not be validated. For field-specific details, see the 'errors' array.\r\nErrors: folder_id Schema describes integer, string found instead\r\n",
    "ExceptionType": "MailChimp.Net.Core.MailChimpException",
    "StackTrace": "   at MailChimp.Net.Core.Helper.<EnsureSuccessMailChimpAsync>d__0.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at MailChimp.Net.Logic.FileManagerFileLogic.<AddAsync>d__5.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()\r\n   at API.Controllers.MailChimp.***.<AddFile>d__3.MoveNext() in ...\\API\\Controllers\\MailChimp\\***.cs:line 50"
}

**Comment by brandonseydel** [comment]
thanks for the find

**Comment by brandonseydel** [comment]
AddFileAsync is the new method other one still works
