### ISSUE TITLE
Get the Results of a Batch Operation

### ISSUE THREAD

**Issue by devdept** [brandonseydel/MailChimp.Net#316]
Hi There,

Can you please help me to get the result of a batch operation with MailChimp.NET as explained here?

http://developer.mailchimp.com/documentation/mailchimp/guides/how-to-use-batch-operations/#get-the-results-of-a-batch-operation

Thanks.

Alberto

**Comment by brandonseydel** [comment]
var batch = await this.MailChimpManager.Batches.AddAsync();
            var status = await this.MailChimpManager.Batches.GetBatchStatus(batch.Id);
