### ISSUE TITLE
Don't  work   update merge field  value

### ISSUE THREAD

**Issue by RudenkoDenis** [brandonseydel/MailChimp.Net#317]
Hi  everybody!
I try update merge fields value from example, but  return old values
var listId = "3243";
var member = new Member { EmailAddress = "test@gmail.com", StatusIfNew = Status.Subscribed };
member.MergeFields.Add("FNAME", "HOLY");
member.MergeFields.Add("LNAME", "COW");
await this.mailChimpManager.Members.AddOrUpdateAsync(listId, member);

 **I try from other example from other mailchimp wrapper, all is well**

         MyMergeVar myMergeVars = new MyMergeVar
            {
                FNAME = "HOLY",
                LNAME = "COW",
                PATRONID = "22173"
            var listId = "3243";
            EmailParameter email = new EmailParameter()
            {
                Email = "test@gmail.com"
            };
               mc.Subscribe(listId, email, myMergeVars, "html", false, true);

**who can tell what the problem is?**

**Comment by brandonseydel** [comment]
member = await this.mailChimpManager.Members.AddOrUpdateAsync(listId, member) will do or new object is needed.  maybe updated the exiting member is a good idea though....

**Comment by RudenkoDenis** [comment]
@brandonseydel, thanks for answer.
Yes,  new member  added,  but  MergeFields values  not set (null) I reserch by issues and found  https://github.com/brandonseydel/MailChimp.Net/issues/127, where  similar problem. In the end ticket, the guys helped to put in  Member result = Task.Run(() => api.Members.AddOrUpdateAsynclist(ID, mr)).Result; 
I try,  but  don't help me, member is adding, but  MergeFields is empty.
Perhaps you can suggest another solution to the problem?
