### ISSUE TITLE
AddOrUpdateAsync is tossing 'User already exists' error

### ISSUE THREAD

**Issue by justSteve** [brandonseydel/MailChimp.Net#322]
var addMember = await manager.Members.AddOrUpdateAsync(mcList.Id, newMember).ConfigureAwait(false);

I'm getting the following error returned:
{"Title: Member Exists\r\nType: http://developer.mailchimp.com/documentation/mailchimp/guides/error-glossary/\r\nStatus: 400\r\nDetail: [theemail] is already a list member. Use PUT to insert or update list members.\r\nErrors: \r\n"}                            

The method I'm calling implies I should be using it to update existing records -- am I supposed to be proceeding the statement with any sort of 'exists' test?

**Comment by DMMSoftware** [comment]
I ran into the same issue as justSteve yesterday.  It does not happen on every one.  It seems to fail on entries from that day through the API.  If I update an older subscriber with an address change or interest (group) that were imported through a file or copy/paste, then it works fine.

**Comment by DMMSoftware** [comment]
After further debugging I found an issue with the data, not the code.  I had to trim my email string.  The affected email address just happened to be new but also had a space at the end in our database.  Now things are working as intended.

**Comment by colinwphillips** [comment]
I am also having this issue. 
I create a user using `AddOrUpdateAsync` and subsequently update the user with order info, etc. and call `AddOrUpdateAsync` again and receive:
`is already a list member. Use PUT to insert or update list members`

**Comment by colinwphillips** [comment]
I am using .ToLower().Trim() on the submitted email address.

**Comment by DavidJohnWilliams** [comment]
The [documentation](https://developer.mailchimp.com/documentation/mailchimp/reference/lists/members/#) for adding members says 

> The MD5 hash of the lowercase version of the list member’s email address.

**Comment by colinwphillips** [comment]
@DavidJohnWilliams I believe you may have mis-read the documentation?

> **Response** body parameters: **id** | The MD5 hash of the lowercase version of the list member’s email address.

In either case, the email address is sent to MailChimp in plain text.

**Comment by colinwphillips** [comment]
Also from the same URL:
> Example **request**: curl --request POST \
--url 'https://usX.api.mailchimp.com/3.0/lists/57afe96172/members' \
--user 'anystring:apikey' \
--header 'content-type: application/json' \
--data '{"email_address":"**urist.mcvankab+3@freddiesjokes.com**", "status":"subscribed"}' \
--include

And:
> Example **response**: 
HTTP/1.1 200 OK
Server: nginx
Content-Type: application/json; charset=utf-8
Content-Length: 2468
Vary: Accept-Encoding
X-Request-Id: f6d49167-897e-48a3-83c6-e8e0eeef2b8b
Link: <https://api.mailchimp.com/schema/3.0/Lists/Members/Instance.json>; rel="describedBy"
Date: Wed, 16 Sep 2015 19:24:29 GMT
Connection: keep-alive
{
  "id": "**852aaa9532cb36adfb5e9fef7a4206a9**",
  "email_address": "**urist.mcvankab+3@freddiesjokes.com**",

**Comment by colinwphillips** [comment]
I also noticed the same behavior as @DMMSoftware 	where:

> It does not happen on every one. It seems to fail on entries from that day through the API. If I update an older subscriber with an address change or interest (group) that were imported through a file or copy/paste, then it works fine.

**Comment by DavidJohnWilliams** [comment]
I think an important thing to realise here is that while the `id` of a member and the `subscriber_hash` are the same thing; they will also change based on the email address as they are just the md5 hash of the email.

That means if you update a member's email then the id you get back will be different from the one you `PUT`. The next request would need to use the new id.

**Comment by colinwphillips** [comment]
@DavidJohnWilliams 	Then I'm not sure where you're going with this if you're referring to the ID column, this repository [appears to be already adhering](https://github.com/brandonseydel/MailChimp.Net/blob/f93d313fbd752cd743f3816b0f3d66149fee6f40/MailChimp.Net/Logic/MemberLogic.cs) to the documentation?
       

>  public async Task<Member> AddOrUpdateAsync(string listId, Member member)
>         {
>             using (var client = CreateMailClient($"{BaseUrl}/"))
>             {
>                 var memberId = member.Id ?? **Hash(member.EmailAddress.ToLower());**
>                 var response = await client.PutAsJsonAsync($"{listId}/members/{memberId}", member).ConfigureAwait(false);
>                 await response.EnsureSuccessMailChimpAsync().ConfigureAwait(false);
>                 return await response.Content.ReadAsAsync<Member>().ConfigureAwait(false);
>             }
>         }

**Comment by colinwphillips** [comment]
> That means if you update a member's email then the id you get back will be different from the one you `PUT`. The next request would need to use the new id.

I think the issue is instead that `AddOrUpdateAsync` is misleading, as in the expected behavior is to `Add` if user does not exist (**working**) however also that it will `Update` if the user already exists. Instead what I believe to be occurring is that the subsequent `Update` does not include the ID column (from the original `Add`) and therefore it does not `Update` but instead tries to `Add` since the `Id` column is blank.

The behavior should be modified such that it instead includes an `Exists` check which will retrieve the ID based on the `email_address` and utilize that `Id` for the `Update`.

**Comment by danroot** [comment]
For others with this issue, I had this occur when the email I was using had an extra space in it.  Code to repro:

  var someValueFromUserEntry = "someuser@addedaspace.com ";
   member.EmailAddress = someValueFromUserEntry;
   await client.AddOrUpdate(listId,member);
   await client.AddOrUpdate(listId,member);

fix is easy enough: member.EmailAddress = someValueFromUserEntry.Trim().  I would argue AddOrUpdate should go ahead and do this for us just to avoid the confusion, since it's already doing ToLower().
