### ISSUE TITLE
Convert to one httpclient per resource

### ISSUE THREAD

**Issue by brandonseydel** [brandonseydel/MailChimp.Net#323]
Should increase throughput of the API.

**Comment by janhansen** [comment]
By resource do you then mean the entire application?

Anyway! This article explains why HttpClient should be a Singleton: https://aspnetmonsters.com/2016/08/2016-08-27-httpclientwrong/

I realize this will mean touching all Logic-classes, removing using-constructs but I guess it will be worth it.

**Comment by brandonseydel** [comment]
Yea that’s why I made the help request awhile ago.


________________________________

**Comment by DavidRouyer** [comment]
Libraries like https://github.com/octokit/octokit.net supports HttpClient injection, so you can also use the new [HttpClientFactory](https://www.hanselman.com/blog/HttpClientFactoryForTypedHttpClientInstancesInASPNETCore21.aspx).

**Comment by janhansen** [comment]
Would it be acceptable to just implement a wrapper for HttpClient and return that from the call to CreateMailClient? Then the baseaddress could be saved in this wrapper and calls to GetAsync, PostAsync etc. would just call through to the Singleton HttpClient. It would make the change much smaller than retouching all logic-files...

**Comment by digbyswift** [comment]
I agree with @janhansen, there doesn't need to be any injection and the instance should not be disposed of after use. A singleton would be appropriate IMO. But this does need doing and throughput should be the least of the concerns (but that would be nice!) when considering it could easily be exhausting connection pools after a batch of requests.
