### ISSUE TITLE
Models.Campaign.Tracking.GoogleAnalytics (bool?) data type mismatch

### ISSUE THREAD

**Issue by manpreets** [brandonseydel/MailChimp.Net#33]
Hi Brandon,

There appears to be data mismatch for  Models.Campaign.Tracking.GoogleAnalytics (bool?) which is defined in V3 documentation(http://developer.mailchimp.com/documentation/mailchimp/reference/campaigns/) as a string.

I am receiving the following json error:

Could not convert string to boolean: UA-xxxxxxxx-xx. Path 'campaigns[0].tracking.google_analytics', line 1, position 1232.

**Comment by brandonseydel** [comment]
Fixed with CS 33de6ec07ffabb6c055024ff9ad063ea2a3c6a5b.
