### ISSUE TITLE
Add support to marketing permissions

### ISSUE THREAD

**Issue by domonkosgabor** [brandonseydel/MailChimp.Net#332]
Looks like MailChimp recently added support for their GPDR fields (marketing permissions) using their API, but MailChimp.Net not yet supports to pass the value of the marketing permissions (marketing_permissions) using the API.
SO discussion: [https://stackoverflow.com/questions/50114923/mailchimp-api-gdpr-fields/51957622#51957622](https://stackoverflow.com/questions/50114923/mailchimp-api-gdpr-fields/51957622#51957622)
MaliChimp API documentation: [https://developer.mailchimp.com/documentation/mailchimp/reference/lists/](https://developer.mailchimp.com/documentation/mailchimp/reference/lists/)

**Comment by HenkHaveANiceDay** [comment]
We also need these fields

**Comment by brandonseydel** [comment]
You can submit a PR or I can work on it this weekend

**Comment by domonkosgabor** [comment]
@brandonseydel It would be great!

**Comment by HenkHaveANiceDay** [comment]
That would be great.

**Comment by HenkHaveANiceDay** [comment]
Can you give an estimate for when this will be availeble?

**Comment by seanjeanc** [comment]
hi... thanks for the great work. Could you please let me know how to update marketing permissions in c#?  It would really help a lot of people...

So far I am able to Add/Update a contact using the merge fields as specified in your README file... but what about the GDPR fields? Hope you can give us a hint... according to the link in stackoverflow, each field has a unique ID right? How to check this and update the fields value? 

Thanks in advance brandon and the rest of the contributers.

**Comment by domonkosgabor** [comment]
The previous PR made by @ericthornton added the support to handle the value of the marketing_permissions Boolean parameter of a list.
When this has a value true, users can subscribe to this list with different marketing permissions.
The Marking Permissions array has marketing permissions with a Marketing Permission ID, a Marketing Permission Text and a Boolean, that shows whether this permission enabled for this user or not.

The issue is every permission of every list has different IDs and we have no idea about these IDs until there is at least one member on a list. And to subscribe a user to a GDPR list, we need to provide this ID.

For a possible workaround if there aren't any user on the list, we need to add a dummy member to a list first. Then now we will get the values of these IDs and can delete this dummy member.
Now with these values we can subscribe users to a GDPR compatible list. That is the logic that my PR contains. What do you think?
