### ISSUE TITLE
Best way to call methods from button click event without async keyword

### ISSUE THREAD

**Issue by kmehta12** [brandonseydel/MailChimp.Net#333]
@brandonseydel I would like to call these async methods from my existing sync methods.  

I am using .Wait() method to accomplish this. Many articles says that it can create deadlock. I haven't face this issue when I tried but wanted to check if this is the right way? If not what's the better way to call these async methods from sync method? Bellow is the code I am using in my sync method.

                var taskLists = _mamager.Lists.GetAllAsync();
                taskLists.Wait();
                var lists = taskLists.Result;

**Comment by brandonseydel** [comment]
You can just use result.  This framework is written in such a fashion that you shouldn't have deadlocks as it doesn't required the returning execution to be delegated onto the same caller thread.  i.e. - ConfigureAwait(false)
________________________________

**Comment by kmehta12** [comment]
Perfect. Thank you very much for the quick response.
Updated with following one line code.

var lists = _mamager.Lists.GetAllAsync().Result;

**Comment by keithstone97** [comment]
I'm having a similar issue, I just need to call them from a class. I'm using:

            //var model = await Manager.Lists.GetAllAsync(options).ConfigureAwait(false);
            var model = Manager.Lists.GetAllAsync(options);

            foreach (List mcl in model)
            {
                if (mcl.Name == listName)
                { mailChimpListId = mcl.Id; }
            }

but I'm getting an error on the foreach:

CS1579	foreach statement cannot operate on variables of type 'Task<IEnumerable<List>>' because 'Task<IEnumerable<List>>' does not contain a public instance definition for 'GetEnumerator'

**Comment by kmehta12** [comment]
use .Result at the end. 

var model = Manager.Lists.GetAllAsync(options).Result;

**Comment by keithstone97** [comment]
You're a gentlemen and a scholar..! Thanks!
