### ISSUE TITLE
Lists with more than 1000 members not pulling entire list

### ISSUE THREAD

**Issue by ScottHoff** [brandonseydel/MailChimp.Net#334]
Am I missing a config option somewhere?  

I would think the default would be to pull everything, based on the total_items from the MailChimp API.

**Comment by ScottHoff** [comment]
And when trying to paginate through ... the limit I set on a new MemberRequest object does not seem to be respected.  Both count and offset parameters are zero in the query that is sent.

My code:


          List<MailChimp.Net.Models.Member> members = new List<MailChimp.Net.Models.Member>();

            for(int i = 0; i <= memberCount; i+= 1000)
            {
                var request = new MailChimp.Net.Core.MemberRequest();
                memberRequest.Offset = i;
                memberRequest.Limit = 1000;
                var memberSection = mailChimpManager.Members.GetAllAsync(listId, request).Result;

                members.AddRange(memberSection);
            }



Sends the query:
https://us2.api.mailchimp.com/3.0/lists/<omitted>/members?vip_only=False&count=0&offset=0 

Same thing if I use GetResponseAsync with the MemberRequest object.

**Comment by brandonseydel** [comment]
Let me write a test case for this and figure it out for you.

**Comment by ScottHoff** [comment]
I'd love to contribute code or test, but wanted to be sure I wasn't missing something obvious. Also curious on Issue 323 how you'd go about it.
