### ISSUE TITLE
Batch update - Member Exists

### ISSUE THREAD

**Issue by RudenkoDenis** [brandonseydel/MailChimp.Net#336]
Hi all!
Im trying to do a batch update and update merge fields by exist member in list:

      var member = new Member()
            {
                EmailAddress = "den@email.ccc",
                Status = Status.Subscribed,
                StatusIfNew = Status.Subscribed,
                MergeFields = new Dictionary<string, object>()
                {
                    {"FNAME", "Dow"},
                    {"LNAME", "Johns"},
                    {"ZIPKEY", "2342"}
                }
            };
--------------------------------------------------------------------------
         var settings = new JsonSerializerSettings
                {
                    ContractResolver = new CustomContractResolver(new Dictionary<string, string>()
                    {
                        {"EmailAddress", "email_address"},
                        {"Status", "status"},
                        {"StatusIfNew", "status_if_new"},
                        {"MergeFields", "merge_fields"}
                    })
                };
-------------------------------------------------------------------------------
     var serializedMember = JsonConvert.SerializeObject(member, settings);
  
       var operation = new Operation()
                {
                    Method = Method.PUT.ToString(),
                    Path = $"/lists/{listId}/members/{member.EmailAddress}",
                    Body = serializedMember
                };
                return operation;

                var batchRequest = new BatchRequest();
                var operartions = new List<Operation>();
                
               var operation = AddOrUpdateMemberOperation(listid, member);
                operartions.Add(operation);
                batchRequest.Operations = operartions;

            var batch =  await  _mailChimpManager.Batches.AddAsync(batchRequest)

**AND get error, what's wrong?**
 I using PUT, email in  lower.

[{"status_code":400,"operation_id":"","response":"{\"type\":\"http:\/\/developer.mailchimp.com\/documentation\/mailchimp\/guides\/error-glossary\/\",\"title\":\"Member Exists\",\"status\":400,\"detail\":\"den@email.ccc is already a list member. Use PUT to insert or update list members.\",\"instance\":\"\"}"}]

**Comment by colinwphillips** [comment]
Possibly related to https://github.com/brandonseydel/MailChimp.Net/issues/322?

**Comment by DavidJohnWilliams** [comment]
It is indeed related, see my comment on #322

**Comment by DavidJohnWilliams** [comment]
Oh and FYI, you don't need that JsonSerializerSettings. The library already specifies JsonPropertyAttribute for all members. You do however need to specify `NullValueHandling = NullValueHandling.Ignore` or it will attempt to upload all the uninitialized values of your member which MailChimp then validates, returning an error.
