### ISSUE TITLE
Campaign.Recipient.SegmentOptions.Conditions.Value runtime type change

### ISSUE THREAD

**Issue by manpreets** [brandonseydel/MailChimp.Net#34]
The issue happens when you get a list of campaigns via` CampaignLogic.GetAll() `and the campaigns are having different `Segment Type` for a `Condition`

As explained in the API reference http://developer.mailchimp.com/documentation/mailchimp/reference/campaigns/# the `Type` of value property `Condition` is not fixed. 

In 'Mailhimp.Net.Models.Condition' `Value` type is `string` but in it's only determined at runtime what is the actual type for Condition.Value 

For e.g.
A campaign  returned via json as shown in the images attached below:

![image](https://cloud.githubusercontent.com/assets/1414668/15593825/eb9ed312-23f2-11e6-9d0d-d721662de535.png)

![image](https://cloud.githubusercontent.com/assets/1414668/15593851/3cab96a0-23f3-11e6-832c-7484ace0bdbb.png)

**Comment by manpreets** [comment]
@brandonseydel  The issue is resolved for me by changing Models.Condition.Value type to object as:

`        /// <summary>
        /// Gets or sets the value.
        /// </summary>
        [JsonProperty("value")]
        public object Value { get; set; }
`

**Comment by brandonseydel** [comment]
Fixed with d113d2474b3cbdc068ee21c9ea1ba73e81985002. Thanks!
