### ISSUE TITLE
Templates.GetAllAsync - Missing TemplateRequest Parameters

### ISSUE THREAD

**Issue by Telaran** [brandonseydel/MailChimp.Net#341]
Hi 

It seems the "TemplateRequest"-Class does not cover all parameters (maybe newly introduced by MailChimp).

- category (string)
- folder_id  (string)
- sort_field (string)

Should I'll try to make a pull request or is this issue enough for you to add them?

Thanks for your response.

**Comment by brandonseydel** [comment]
Pull request would be appreciated.  Test case if you could also ;)

**Comment by Telaran** [comment]
Okay, I'll create a PR. But it might take some time (maybe somewhere around 10th October 2018) .

Before I do start:
- DeleteAsync/UpdateAsync: TemplateId is string instead of int, should I'll fix it?
- As far as I do see: There is no TemplateTest at all -> Should I'll try to make a whole set of tests?

I just don't want to mess up anything, but also would try to contribute as best as possible.

**Comment by brandonseydel** [comment]
you can fix it, but you must create a new function for it without breaking past.
