### ISSUE TITLE
Validate Api Key

### ISSUE THREAD

**Issue by RudenkoDenis** [brandonseydel/MailChimp.Net#344]
Hi all!
How  I can check validate of api key?
In developer  documentation  I see end point Ping,
https://developer.mailchimp.com/documentation/mailchimp/reference/ping/
 but   in Mail Chimp 3.0 Wrapper dont  found
Tell me please, how  check validate api key?

**Comment by brandonseydel** [comment]
We can add this into the code stay tuned

**Comment by RudenkoDenis** [comment]
Please, add this in code.
Thanks!

**Comment by kirby14** [comment]
Is this already in the works by chance? Would be interested in having this added as well.

**Comment by RudenkoDenis** [comment]
@kirby14,  I will tell you  that support is bad here (@brandonseydel,...), they answer in half a year and often they don’t want to add or change at all 👎

**Comment by RudenkoDenis** [comment]
#358  also answered in three months with a question 👎

**Comment by mikehachen** [comment]
Did you pay anything for this wrapper? If not then I would stop to go on about @brandonseydel !! He does this in his spare time so please show some gratitude. If you need this endpoint desperately add it yourself to the code and submit a PR.

**Comment by RudenkoDenis** [comment]
I think that he could receive dividends from mailchimp company and be interested in timely support of the wrapper.

**Comment by mikehachen** [comment]
You didn't get the point. If you're not happy with this wrapper or how you receive support go on and create your own one. But stop grumble.

**Comment by brandonseydel** [comment]
Pushed out

**Comment by RudenkoDenis** [comment]
@brandonseydel , thanks! I am sorry  if what offended. You do a great thing!

**Comment by brandonseydel** [comment]
I gladly accept PR requests into this wrapper.  I think the code base is very approachable for everyone and they can add new endpoints and classes fairly easy.  Even if you just attach CS files to the issue I Can manually merge if there is a gap in the PR process.
