### ISSUE TITLE
Getting error "System.Threading.Tasks.TaskCanceledException: A task was canceled" for GetEmailActivitiesAsync

### ISSUE THREAD

**Issue by kmehta12** [brandonseydel/MailChimp.Net#347]
@brandonseydel 
Try to get report for the campaign using GetEmailActivitiesAsync. When it's campaign with couple of emails it's working fine but with about 2000 emails getting error "System.Threading.Tasks.TaskCanceledException: A task was canceled". Seems like it has to do with timeout but not sure how to handle this kind of high volume data response in sync method.

     var response = _driver.Reports.GetEmailActivitiesAsync(campaignID).Result;

also tried with wait.

     var taskResponse = _driver.Reports.GetEmailActivitiesAsync(campaignID);
     taskResponse.Wait();
     var response = taskResponse.Result;

**Comment by softeamdev** [comment]
Is there any solution?
