### ISSUE TITLE
ArgumentException when accessing MailChimpException.Data more than once

### ISSUE THREAD

**Issue by samueldjack** [brandonseydel/MailChimp.Net#348]
If I access MailChimpException.Data more than once, I get the error

    System.ArgumentException: Item has already been added. Key in dictionary: 'detail'  Key being added: 'detail'
     at System.Collections.ListDictionaryInternal.Add(Object key, Object value)
     at MailChimp.Net.Core.MailChimpException.get_Data()

Looking at the code [here](https://github.com/brandonseydel/MailChimp.Net/blob/46832dffaa62b01166954f57355b45274f46803d/MailChimp.Net/Core/MailChimpException.cs#L82) I can see that the Data getter attempts to add the values every time the getter is called:

        public override IDictionary Data
        {
            get
            {
                var data = base.Data;
                data.Add("detail", Detail);
                data.Add("title", Title);
                data.Add("type", Type);
                data.Add("status", Status);
                data.Add("instance", Instance);
                data.Add("errors", Errors);
                data.Add("rawhttpresponsemessage", RawHttpResponseMessage);
                return data;
            }
        }

Perhaps something like this would fix the problem:

         public override IDictionary Data
        {
            get
            {
                var data = base.Data;

                if (!data.ContainsKey("detail")) {
                    data.Add("detail", Detail);
                    data.Add("title", Title);
                    data.Add("type", Type);
                    data.Add("status", Status);
                    data.Add("instance", Instance);
                    data.Add("errors", Errors);
                    data.Add("rawhttpresponsemessage", RawHttpResponseMessage);
                }

                return data;
            }
        }

**Comment by brandonseydel** [comment]
We need to just make a local field and check if it has been instantiated.  You want to make a pull request for this?

if(_date != null){return _date;}

//normal logic with _date
_date = base.Data
