### ISSUE TITLE
Missing Response Body fields for some MailChimp endpoints

### ISSUE THREAD

**Issue by JamesKibirige** [brandonseydel/MailChimp.Net#349]
Campaigns: 
{
   recipients.list_name, 
   recipients.list_is_active,
   recipients.recipient_count
}

The missing fields here will need to go into the model: Recipients.cs 

AutomationEmails: {web_id}

Please see MailChimp Api documentation that details the field list for these End points:

- https://developer.mailchimp.com/documentation/mailchimp/reference/campaigns/
- https://developer.mailchimp.com/documentation/mailchimp/reference/automations/emails/#read-get_automations_workflow_id_emails

**Comment by brandonseydel** [comment]
Please add and PR for it
