### ISSUE TITLE
Recently started getting timestamp_signup error when adding a member

### ISSUE THREAD

**Issue by guslandt** [brandonseydel/MailChimp.Net#350]
Recently I've started getting a "This value is not a valid datetime." error saying the timestamp_signup is not a valid datetime. This is in C# code that hasn't changed in over a year:

`var member = new Member {
                    EmailAddress = email,
                    StatusIfNew = Status.Subscribed,
                    EmailType = "html",
                    IpOpt = userIPAddress,
                    TimestampSignup = DateTime.UtcNow.ToString("s")
                };

var result = await mailChimpManager.Members.AddOrUpdateAsync(_ListId, member);`

I've tried a dozen variations of sending a datetime and continue to get the same error.

**Comment by WaChris** [comment]
I have now (since 1 Week) the same problem ("timestamp_signup" -> this value is not a valid datetime).
This is my C#-Code:

var member = new Member  {
                                         EmailAddress = emailAdress,
                                         Status = Status.Subscribed,
                                         StatusIfNew = Status.Subscribed,
                                         EmailType = "html",
                                         TimestampSignup = DateTime.UtcNow.ToString("s") 
                        };

**Comment by EricLott** [comment]
Getting same error, was working before with no changes on my end.

**Comment by m-reinke** [comment]
Had the same. 
Changed timestamp format to:
member.TimestampSignup = DateTime.UtcNow.ToString("yyyy-MM-dd hh:mm:ss");
See also
[StackOverflow](https://stackoverflow.com/questions/35875377/what-is-the-right-syntax-for-timeframe-in-mailchimp-api-3-0)

**Comment by brandonseydel** [comment]
I should add this by default to just pass datetime object and format correctly.  So we don't have to worry about formatting would someone want to PR this.

**Comment by brandonseydel** [comment]
Does someone want to make a jsonformatter for this to apply to this property and others as we see fit?

**Comment by ronaldbarendse** [comment]
Same here! For now, we'll update our own implementations to change the format, but what's to say MailChimp doesn't revert back to the ISO 8601 format? If they do, they should at least allow the custom `yyyy-MM-dd hh:mm:ss` format...

I couldn't find a public issue tracker or status page for MailChimp, but I submitted my feedback on https://mailchimp.com/contact/feedback/ (referring to this issue).

To remove this issue for the implementers, I would indeed recommend adding `DateTime` properties to the models, e.g. `TimestampSignupUtc`. Using `JsonFormatter`s would be the cleanest method, but would break backwards compatibilty (and you don't want to manually keep the string/DateTime fields in sync after JSON conversion).

Maybe something like this suffices (most of the logic could be put in helper methods of course):
```c#
[JsonIgnore]
public DateTime? TimestampSignupUtc
{
	get
	{
		if (DateTime.TryParseExact(this.TimestampSignup, new[] { "o", "s", "yyyy-MM-dd hh:mm:ss" }, null, DateTimeStyles.AdjustToUniversal | DateTimeStyles.AssumeUniversal, out DateTime result))
		{
			return result;
		}
	
		return null;
	}
	set
	{
		this.TimestampSignup = value?.ToString("yyyy-MM-dd hh:mm:ss");
	}
}
```

**Comment by ronaldbarendse** [comment]
@brandonseydel Would adding the above `TimestampSignupUtc` property still add value?
