### ISSUE TITLE
Support for adding Tags to Members

### ISSUE THREAD

**Issue by LindaMohacsi** [brandonseydel/MailChimp.Net#351]
Hi, can we be expecting support for adding tags to members in Members.AddOrUpdateAsync?
Currently the Tag data is not added even though it is present in the Member object sent to the method.

**Comment by Tiger333** [comment]
Just noticed this myself when running tests.
This would be fantastic functionality to add.

**Comment by brandonseydel** [comment]
Pull request?

**Comment by brandonseydel** [comment]
Almost there waiting for some changes
