### ISSUE TITLE
Remove / Update Tags from member

### ISSUE THREAD

**Issue by Maverick1387** [brandonseydel/MailChimp.Net#359]
Hi.
The last commit (#352) enables tags with new members, but if we want to edit/ update the tag-list, it won't work. 
We'll need   POST /lists/{list_id}/members/{subscriber_hash}/tags 

Regards Ingo

**Comment by GregObleshchuk** [comment]
Hi ,
I have fixed this piece of code by adding a call to /lists/{list_id}/members/{subscriber_hash}/tags with a new tag collections.  Not the prettiest piece of code but it works.
  
Not really sure how to get the code up .  Can some help?
cheers
Greg

**Comment by fatihyildizhan** [comment]
@GregObleshchuk how can I implement your solution?

**Comment by JoshuaSimsHTB** [comment]
I am also looking into implementing this functionality.

**Comment by brandonseydel** [comment]
I can add it this weekend.  I have a list of features going.

**Comment by mm-mihailn** [comment]
I implemented a quick solution and attached the modified/added sources here.
What I did was to introduce a new method for adding a tag(this method handles both add and remove actions - depends on a status field that is passed) and added new tag Models according to the docs.
Hope this helps.
[TagsPatch.zip](https://github.com/brandonseydel/MailChimp.Net/files/2797254/TagsPatch.zip)

**Comment by burlandm** [comment]
I have the same requirement to update tags and I'm disappointed that it doesn't appear to work.

**Comment by andyjonesx** [comment]
Has there been any progress getting this in? It seems a few people have done work to get it fixed but it isn't yet in the trunk. Just wondering the status before I try myself.

**Comment by andyjonesx** [comment]
I've added a pull request for this: https://github.com/brandonseydel/MailChimp.Net/pull/390
