### ISSUE TITLE
Add user Status.Subscribed

### ISSUE THREAD

**Issue by millenniumy2k** [brandonseydel/MailChimp.Net#361]
Hi
I have a problem with bees. This script:
var member = new Member { EmailAddress = f.Email, Status = Status.Subscribed };
​
member.MergeFields.Add("RAGSOCIALE", f.RagSociale);​
member.MergeFields.Add("LINK", f.Link);​
​
mailChimpManager.Members.AddOrUpdateAsync(listId, member);
The new user is added, but comes the confirmation email subsccription... why?

**Comment by Palec** [comment]
**StatusIfNew = Status.Subscribed**

`await _mailChimpManager.Members.AddOrUpdateAsync(list.Id, new Member
                    {
                        EmailAddress = subscriber.Email,
                        Status = Status.Subscribed,
                        StatusIfNew = Status.Subscribed
                    }).ConfigureAwait(false);`

**Comment by brandonseydel** [comment]
As suggested need to use the statusifnew.  Don’t blame me for that terrible api that is mail chimp.
