### ISSUE TITLE
MailChimp Account Issue

### ISSUE THREAD

**Issue by fatihyildizhan** [brandonseydel/MailChimp.Net#363]
Hello, my mailchimp account is suspended. They don't say the exact reason. Do you know something about this topic?

This is the text:
Our automated abuse-prevention system, Omnivore, has detected an action or content in your account that may be in violation of our Acceptable Use Policy.

For more information on these violations, please review our Acceptable Use Policy.

**Comment by Telaran** [comment]
As MailChimp explain about their [Omnivore ](https://mailchimp.com/help/about-omnivore/): _The quality of your list is not "good enough"._

This can happen due two main reasons

- You don't remove any "unsubscribed users" from your list
- You don't remove any bounced e-mails from your list

Another reason you hopefully don't do

- You use a list which was "somehow" collected and contains people which never expect to receive an email from your service (which would cause in a high unsubscribe rate which could also cause a warning  from MailChimp)

So if you add too many new list with a high amount of "already unsubscribed" or "bounced" user in it,  it can end in an account suspension. Do you handle these events (i.E. WebHook or Scheduled Check of List)?

In that case you have to re-validate why your internal list is inaccurate and you have to explain MailChimp what you do to change this situation. After this they should reopen your account.
