### ISSUE TITLE
Possible to set the HTTP request timeout?

### ISSUE THREAD

**Issue by ThomasArdal** [brandonseydel/MailChimp.Net#369]
Is it possible to set the HTTP request timeout on Mailchimp API calls through MailChimp.NET?

**Comment by brandonseydel** [comment]
Not currently, but an entire revamp on the httpclient instantiation is coming.  This will give some additional flexibility in this instance.

**Comment by tomidix** [comment]
@brandonseydel Is this anywhere near production?

**Comment by ThomasArdal** [comment]
@brandonseydel Was the client revamped in a way where this is now possible?
