### ISSUE TITLE
How do you use pagination? eg: ?list=xxxxxx&offset=100&count=100

### ISSUE THREAD

**Issue by vsmash** [brandonseydel/MailChimp.Net#373]
I can't seem to see an example or an option for pagination in downloading members from a list.

**Comment by brandonseydel** [comment]
https://github.com/brandonseydel/MailChimp.Net/blob/7b9e36c0d50fda8f820b4574b75f448495fdb67c/MailChimp.Net/Logic/MemberLogic.cs#L307

The member request has offset limit on it.
