### ISSUE TITLE
HttpClient using application JSON serialization settings

### ISSUE THREAD

**Issue by digbyswift** [brandonseydel/MailChimp.Net#374]
I have a .Net 4.6.2 web application that uses both MVC and WebAPI and both have global JsonSerializationSettings configured to format as camelcase and this causes the MailChimp API to return errors.

When the BaseLogic.CreateMailClient() is called, it instantiates a HttpClient. Each subsequent call to client.PutAsJsonAsync() uses the application's global JsonSerializationSettings which formats the Json and cause issues posting/putting data to MailChimp.

According to MailChimps technical team, the merge field names are case sensitive and so if the JsonSerializationSettings are set to use camelcase, then MailChimp will throw back an error stating that the merge field doesn't exist.

In classes like MemberLogic, can you use client.PutAsync() with a formatter parameter setting default JsonSettings instead of PutAsJsonAsync()?

**Comment by brandonseydel** [comment]
I will need to go through and switch everything over.  I already am refactoring out to use minimal httpclients so I will do it then.
