### ISSUE TITLE
ListSegmentLogic: AddMemberAsync "A Static Segment with an id of...does not exist for this list"

### ISSUE THREAD

**Issue by JoshuaSimsHTB** [brandonseydel/MailChimp.Net#377]
The AddMemberAsync method of the ListSegmentLogic class continues to throw a MailChimpException, describing the issue as "A Static Segment with an id of [segment ID value passed to AddMemberAsync] does not exist for this list."

**Comment by stodolos** [comment]
I am coming across this same issue.

**Comment by stodolos** [comment]
So, I got on with support, and the reason I was getting this error was b/c I was trying to add someone to a "saved"/dynamic list (which was driven off of conditions).  It wasn't a static list (which I wasn't aware).  The error is misleading, and I left that feedback, but the cause of the error was my own.
