### ISSUE TITLE
Ping is Missing

### ISSUE THREAD

**Issue by Macy-Soft** [brandonseydel/MailChimp.Net#381]
As You can see under https://developer.mailchimp.com/documentation/mailchimp/reference/ping/, there is this Call. Could this not be supplemented yet?

**Comment by brandonseydel** [comment]
Yes would you like to take this on?

**Comment by Macy-Soft** [comment]
Yeah, I'm going to give it a go. What do I have to do?

**Comment by brandonseydel** [comment]
It’s in now
