### ISSUE TITLE
Expose field_warnings / field_errors arrays for Lists.BatchAsync()

### ISSUE THREAD

**Issue by alcoheca** [brandonseydel/MailChimp.Net#384]
Hi

The following call is failing for me. `memberBatchList` is a combination of new and existing subscribers to the list.

```
BatchList memberBatchList = new BatchList {
    Members = subscribers,
    UpdateExisting = false 
};
```

```
BatchListResponse resp = _mailChimp.Lists.BatchAsync(memberBatchList, this.mailChimpListId).Result;
```

`resp.Errors` contains an `ErrorResponse` for each provided `Member`. The `Error` property is "The resource submitted could not be validated. For field-specific details, see the 'errors' array."

I've seen this before with different libraries, usually it's a required merge field that is not present. Mailchimp passes these back via the `field_errors` array.

The docs say:

"**InvalidResource**
The resource submitted could not be validated.

For field-specific details, see field_warnings or field_errors objects. This error means that the object submitted to a POST or PATCH request failed to validate against JSON schema, and could relate to campaign, interest group, merge field, or any other available object."

Is it possible to expose these via this library?

**Comment by alcoheca** [comment]
I'm building the `Member` objects as simple as possible.

```
Member member = new Member {
    EmailType = "HTML",
    EmailAddress = customer.Email,
    Status = Status.Subscribed,
    StatusIfNew = Status.Subscribed
};
```

**Comment by brandonseydel** [comment]
That should be there.  Are you catching MailChimpException and reading the errors array?

**Comment by alcoheca** [comment]
There's no exception thrown - I wouldn't expect there to be one?

I'm reading the BatchListResponse returned from the call and checking the ErrorCount and Errors array.

![Screen Shot 2019-04-04 at 00 31 23](https://user-images.githubusercontent.com/546879/55519851-7eca6f80-5671-11e9-9e3c-30ae0e0a7955.png)

**Comment by brandonseydel** [comment]
Sorry - Misread let me look into this more.

**Comment by alcoheca** [comment]
I take it there's no way to flick a switch / drill down somewhere and get access to the raw response from the HTTP request?

I'm looking through the code right now to see if that's possible

**Comment by alcoheca** [comment]
I built this library locally and there's no extra info coming back from MailChimp in the raw json response. Just the fields you already populate.

So back to the drawing board for me. Closing as I don't think this is an issue for you.

**Comment by brandonseydel** [comment]
Thank you for the research.
