### ISSUE TITLE
Fix needed in StringEnumDescriptionConverter

### ISSUE THREAD

**Issue by manicfiddler** [brandonseydel/MailChimp.Net#39]
The recent change of Campaign.Type from string to enum has broken the campaign update code as a Null value exception is thrown:

StringEnumDescriptionConverter.WriteJson needs

 var type = value.GetType();
var name = Enum.GetName(type, value);
**if (name != null)
{**
    var description = type.GetField(name) // I prefer to get attributes this way
        .GetCustomAttributes(false)
        .OfType<DescriptionAttribute>()
        .Select(x => x.Description)
        .SingleOrDefault();
    writer.WriteValue(description ?? name);
**}**

I would submit a pull request but my master branch is in such a mess it's probably less work for you to do it and me to delete my fork and start again.  Sorry :)

**Comment by brandonseydel** [comment]
OK I will get this in right away thank you.

**Comment by brandonseydel** [comment]
What is the actual underlying issue with this?  Are we missing a mapping for a campaign type?

**Comment by manicfiddler** [comment]
When Type was a string, leaving it null meant it was ignored.  Now that it is an enum it is going through the StringEnumDescriptionConverter but as it defaults at a value of 0 then Enum.GetName(type, value) is returning null which bombs out the next line.  Putting this in would mean that the 0 effectively gets ignored which is back to the old behaviour but keeps the benefits of the enum

**Comment by brandonseydel** [comment]
A nullable enum gotcha this has been rolled out already.
