### ISSUE TITLE
Pass "since" Parameter to "email-activity"-report

### ISSUE THREAD

**Issue by michaelrall** [brandonseydel/MailChimp.Net#391]
It seems to me, that parameter / request-class is missing for this method. How can I pass this parameter to "Reports.GetEmailActivitiesAsync(...)" using the class "QueryableBaseRequest"? Should I just extend the class and add the needed Parameter-Propierties?

kind regards

**Comment by brandonseydel** [comment]
public class EmailActivityRequest : QueryableBaseRequest{

}

**Comment by michaelrall** [comment]
Allright, worked like a charm :-)
