### ISSUE TITLE
Nuget Package version=4.0.0.0 not up-to-date

### ISSUE THREAD

**Issue by snormand** [brandonseydel/MailChimp.Net#392]
The current Nuget Package MailChimp.Net version=4.0.0.0 doesn't contains MemberLogic functions "AddTagsAsync" and "GetGoalsAsync".

Simply package and push a new version of the Nuget.

Thanks!!

**Comment by brandonseydel** [comment]
I will bump it this weekend.

**Comment by brandonseydel** [comment]
Done
