### ISSUE TITLE
member Tag management is still not working 

### ISSUE THREAD

**Issue by GregObleshchuk** [brandonseydel/MailChimp.Net#398]
Hi ,
I just tried the to update the tags on an email address and it is still not working .  The membertag structure seems to be wrong as well
https://developer.mailchimp.com/documentation/mailchimp/reference/lists/members/tags/#create-post_lists_list_id_members_subscriber_hash_tags

Has anyone got this working

**Comment by glen-dale** [comment]
Hi,
I also cannot get this to work when attempting to update tags for a list member. Tried various versions including the latest nuget package.

I really need to get this working ...

**Comment by rpenha** [comment]
Same issue here. Is there some workaround?

**Comment by brandonseydel** [comment]
Let me take a look real quick

**Comment by jimmyjudas** [comment]
This is working fine for me. To add a tag to a member:

```
Tags tags = new Tags();
tags.MemberTags.Add(new Tag() { Name = tagName, Status = "active" });
await mailChimpManager.Members.AddTagsAsync(listId, emailAddress, tags);
```

To remove, do the same as above but instead use "inactive" as the Status.

Admittedly, it is a bit strange that `Tags.MemberTags` is a `List<Tag>` rather than a `List<MemberTag>`

**Comment by krisBroekstra1** [comment]
> This is working fine for me. To add a tag to a member:
> 
> ```
> Tags tags = new Tags();
> tags.MemberTags.Add(new Tag() { Name = tagName, Status = "active" });
> await mailChimpManager.Members.AddTagsAsync(listId, emailAddress, tags);
> ```
> 
> To remove, do the same as above but instead use "inactive" as the Status.
> 
> Admittedly, it is a bit strange that `Tags.MemberTags` is a `List<Tag>` rather than a `List<MemberTag>`

This method is working for me, thanks!
