### ISSUE TITLE
ShippingTotal is missing in Ecommerce Store Order

### ISSUE THREAD

**Issue by Sumomannen** [brandonseydel/MailChimp.Net#40]
Hi

I'm converting to MailChimp v.3 with this great API and use Ecommerce Store with orders and products. I just started mapping things over and saw that shipping_total, tracking_code, shipping_address and billing_address is missing in the Order class.

**Comment by brandonseydel** [comment]
Ok I will get this in and roll out a nuget within the hour.  Thanks.

**Comment by Sumomannen** [comment]
Thanks.. Works perfect!

A small thing when you have time is to change Price in product and variant to double/number instead of int.

**Comment by brandonseydel** [comment]
Ok that will be going out with your latest fixes.
