### ISSUE TITLE
MemberRequest seems to be ignored

### ISSUE THREAD

**Issue by MrGrabazu** [brandonseydel/MailChimp.Net#409]
Hi, I wrote this code in order to test the wrapper before using it.
```c#
var manager = new MailChimpManager("my_api_key");
var lists = await manager.Lists.GetAllAsync();
var members = new List<Member>();
var request = new MemberRequest {
    Limit = 100
};
foreach (var list in lists)
{
    members.AddRange(await manager.Members.GetAllAsync(list.Id, request));
}
```
And each execution of `GetAllAsync` return only 10 members and not more.
I check what url is called with fiddler to see the query string and there was only `vip_only=false` in it. Even if I don't specify a MemberRequest I have only 10 members, and not 1000 like it should be because in source the default `Limit` is equals to 1000.

I can't find in sources where the issue may come from. Am I the only who have this issue ?

Thanks !

**Comment by brandonseydel** [comment]
What version are you on?

**Comment by MrGrabazu** [comment]
I have installed the nuget MailChimp.Net.V3.Core v1.11.0.

**Comment by MrGrabazu** [comment]
After your question I checked the nuget and realize that I need to get MailChimp.Net.V3 and not the Core one... And it works great ! 

Thank you.
