### ISSUE TITLE
Missing web_id field from Members class

### ISSUE THREAD

**Issue by Diesel1017** [brandonseydel/MailChimp.Net#410]
Hi,

when i get the **Members** list or just one Member, from Response body parameters is missing the: **web_id** field!

Whiteout this i can't open the member in the browser.

(The ID used in the Mailchimp web application. View this member in your Mailchimp account at https://{dc}.admin.mailchimp.com/lists/members/view?id={web_id}.)

Mailchimp API
(https://developer.mailchimp.com/documentation/mailchimp/reference/lists/members)

There are other ways to open a Member in browser?
Thanks!

**Comment by brandonseydel** [comment]
Merged
