### ISSUE TITLE
Lists with more than 1000 members not pulling entire list

### ISSUE THREAD

**Issue by tomidix** [brandonseydel/MailChimp.Net#414]
Let me write a test case for this and figure it out for you.

_Originally posted by @brandonseydel in https://github.com/brandonseydel/MailChimp.Net/issues/334#issuecomment-421112184_

Seems that I can't find an example for this.. 
I think either the naming of GetAll is not suitable for current method (its just get without a memberID parameter) or implementation has a bug where not all members are acquired..

**Comment by brandonseydel** [comment]
did you pass in the queryablerequest to allow more or adjust the default options?

**Comment by justSteve** [comment]
> did you pass in the queryablerequest to allow more or adjust the default options?

Could you point to sample of how this is done?

**Comment by hinsona** [comment]
Something like this might work.

`var Members = await _mcm.Members.GetAllAsync(listId, new MemberRequest { Limit = await mcm.Members.GetTotalItems(listId, null) });`

**Comment by hinsona** [comment]
> > did you pass in the queryablerequest to allow more or adjust the default options?
> 
> Could you point to sample of how this is done?

Something like this might work.

`var Members = await _mcm.Members.GetAllAsync(listId, new MemberRequest { Limit = await mcm.Members.GetTotalItems(listId, null) });`

**Comment by guipower** [comment]
Tried with Limit as below, still only getting 1,000 members. Is there a fix or working code for this?

            int totalMembers = Convert.ToInt32(mailChimpManager.Members.GetTotalItems(mailChimpListId, null).Result);
            var listMembers = await mailChimpManager.Members.GetAllAsync(listId, new MemberRequest
            {
                Limit = totalMembers
            })

**Comment by hinsona** [comment]
> Tried with Limit as below, still only getting 1,000 members. Is there a fix or working code for this?
> 
> ```
>         int totalMembers = Convert.ToInt32(mailChimpManager.Members.GetTotalItems(mailChimpListId, null).Result);
>         var listMembers = await mailChimpManager.Members.GetAllAsync(listId, new MemberRequest
>         {
>             Limit = totalMembers
>         })
> ```

Are the values of mailChimpListId and listId in your example different? The example I posted on Oct 10 works for me. I use this exact call in my code when batch unsubscribing members.

`static async Task<BatchRequest> GetUnsubscribeAllBatchRequestAsync(string listId)
{
    var MembersToUnsubscribe = await _mcm.Members.GetAllAsync(listId, new MemberRequest { Limit = await _mcm.Members.GetTotalItems(listId, null) });
    var unsubscribeOperations = MembersToUnsubscribe.Select(x => GetUnsubscribeOperation(listId, x));
    return new BatchRequest { Operations = unsubscribeOperations };
}`

**Comment by Martijn-vd-H** [comment]
The MailChimp API has a maximum limit of 1000. So you're bound to that. You have to paginate through the results using the offset. See the page from the API reference for more info. https://mailchimp.com/developer/guides/get-started-with-mailchimp-api-3/#Parameters

**Comment by NathanielArmer** [comment]
This seems to be a badly named method.  I'm happy to be paging... but can't see a method to do that in this library.

**Comment by jimmyjudas** [comment]
I realise this was closed a while ago, but for future reference you can do paging using the `Offset` property on `MemberRequest`:

```
List<Member> allContacts = new List<Member>();
IEnumerable<Member> pagedContacts;

int mailChimpLimit = 1000; //MailChimp only allows us to fetch this many records at a time
int currentOffset = 0;
do
{
    pagedContacts = await mailChimpManager.Members.GetAllAsync(listId, new MemberRequest { Offset = currentOffset, Limit = mailChimpLimit });
    allContacts.AddRange(pagedContacts);
    currentOffset += mailChimpLimit;
} while (pagedContacts.Count() == mailChimpLimit);

return allContacts;
```

I'll happily raise a PR to add this to the repo, but somehow didn't seem right adding a "get all ignoring paging" method (as above) into the codebase. Maybe I can add a method that simplifies the paging concept, or just add the code above to the readme as an advanced example...
