### ISSUE TITLE
"[email] was permanently deleted and cannot be re-imported. The contact must re-subscribe to get back on the list."

### ISSUE THREAD

**Issue by jwbats** [brandonseydel/MailChimp.Net#416]
I've permanently deleted a contact from my mail list. When I try to readd that contact using Members.AddOrUpdateAsync(), I will get the error:

"[email] was permanently deleted and cannot be re-imported. The contact must re-subscribe to get back on the list."

How can I use this wrapper to resubscribe somebody, to ensure the addition of a member always works correctly?

The first time around, I was able to add a member and set him to 'subscribed' right away. How is it possible that MC lets you add a contact like that before having deleted him, but not after?

Best way to deal with this?

**Comment by brandonseydel** [comment]
I wrote a test case for this.  

```c#



        [Fact]
        public async Task Should_Delete_And_ReSubscribe()
        {
            var member = await this.Add_User_To_List();
            member = await this.MailChimpManager.Members.AddOrUpdateAsync(TestList.Id, member);
            await this.MailChimpManager.Members.DeleteAsync(TestList.Id, member.EmailAddress);
            member.Status = Status.Subscribed;
            member = await this.MailChimpManager.Members.AddOrUpdateAsync(TestList.Id, member);
            Assert.True(member.Status == Status.Subscribed);
        }


```

**Comment by mmDevel** [comment]
Hi @brandonseydel 
Your solution does not describe how should we fix the issue, I tried your implementation.

I do not mind sending to the customer again their form, but how should they do it?

How should we proceed?
It is not me who want the customer to get subscribed it is them, who want to get subscribed again.
Please share with us the steps, because I tried looking into it, but I haven't found anything useful, how to deal with this issue.

**Comment by abdelmeenam** [comment]
HI @mmDevel 
After checking Mailchimp behavior and documentation, there is no supported way to re-subscribe a permanently deleted (forgotten) contact via API or manual admin actions.

The only valid option is for the user to re-subscribe themselves through a Mailchimp hosted signup form, which records fresh consent (double opt-in if enabled).
Admin add, import, or API calls will always be rejected for this case.
