### ISSUE TITLE
Requested value 'archived' was not found.

### ISSUE THREAD

**Issue by des2k7** [brandonseydel/MailChimp.Net#417]
Using v4.1.0

This throws an exception:

> var memberships = await mcManager.Members.SearchAsync(new MemberSearchRequest()
>                 {
>                     Query = email
>                 });

My code was working fine until i archived a subscriber on some audience/list. Im guessing you're missing some code to map this status.

I saw a similar issue (#91) where you didnt have an enum for a transactional subscriber. Im guessing this is something similar where you dont have an enum translation for an archived subscriber

Thanks for the wonderful library!

Stacktrace:

> bij System.Enum.EnumResult.SetFailure(ParseFailureKind failure, String failureMessageID, Object failureMessageFormatArgument)
>    bij System.Enum.TryParseEnum(Type enumType, String value, Boolean ignoreCase, EnumResult& parseResult)
>    bij System.Enum.Parse(Type enumType, String value, Boolean ignoreCase)
>    bij MailChimp.Net.Core.StringEnumDescriptionConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
>    bij Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
>    bij Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
>    bij Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
>    bij Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
>    bij Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
>    bij Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
>    bij Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
>    bij Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
>    bij Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
>    bij Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
>    bij Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
>    bij Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
>    bij Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
>    bij Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
>    bij Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
>    bij Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
>    bij Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
>    bij Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
>    bij Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
>    bij Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
>    bij Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value)
>    bij MailChimp.Net.HttpContentExtensions.<ReadAsAsync>d__0`1.MoveNext()
> --- Einde van stacktracering vanaf vorige locatie waar uitzondering is opgetreden ---
>    bij System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    bij System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    bij MailChimp.Net.Logic.MemberLogic.<SearchAsync>d__3.MoveNext()
> --- Einde van stacktracering vanaf vorige locatie waar uitzondering is opgetreden ---
>    bij System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    bij System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    bij System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
>    bij BPM.Services.NewsLetter.MailChimpNewsLetterService.<GetNewsLettersForMember>d__6.MoveNext() in C:\Users\timde\source\repos\SD Schrijnwerkerij\BPM.Services\NewsLetter\MailChimpNewsLetterService.cs:regel 183

**Comment by educosta** [comment]
Same error here. Member status enum not contains archived item

**Comment by brandonseydel** [comment]
They allow users to be archived and you can archive inside mail chimp but their API doesn't recognize as valid status.  It however will return archive as a status.  Need to open a ticket with mailchimp.

**Comment by brandonseydel** [comment]
![image](https://user-images.githubusercontent.com/5033585/62542249-0ba05800-b821-11e9-8ecb-019f08f217b6.png)

**Comment by brandonseydel** [comment]
I am talking with their dev team to try and convince them to not only allow delete to archive, but also just update the status.  If they don't accept that as an option I want them to provide better error messages to users as the most intuitive way to archive a member is to archive them, not to delete them.

**Comment by brandonseydel** [comment]
Once that archived status is added to the member then I will start getting issues for not being able to update the member to archived *face palm*

**Comment by des2k7** [comment]
lol brandon.. so their UI is allowing archiving of subscribers, but their API doesnt reflect that? :D

It breaks the entire application once 1 member is archived. Perhaps translate the value to something unknown for now so it doesnt crash?

**Comment by brandonseydel** [comment]
I will just add it since an attempt to update the status with it isn’t as bad as not being able to read a list.

**Comment by ColinRaaijmakers** [comment]
Still having this issue. Can you add the status, so this problem can be fixed?

Best regards.
Colin Raaijmakers

**Comment by brandonseydel** [comment]
4.2.1 has it.
