### ISSUE TITLE
Lists with more than 1000 segments not pulling entire segment list

### ISSUE THREAD

**Issue by laszlo-szatmari-insimu** [brandonseydel/MailChimp.Net#428]
ListSegmentLogic.GetAllAsync returns maximum 1000 segments. There is no paging implemented. GET /lists/{list_id}/segments limits maximum count to 1000 (https://mailchimp.com/developer/reference/lists/list-segments/#get_/lists/-list_id-/segments). Offset should be used.

**Comment by brandonseydel** [comment]
You want to get 1k it length =1k offset 1k rinse repeat?

**Comment by laszlo-szatmari-insimu** [comment]
Yes, eventually I found the way to do that, but then it is not GetAll, but GetSome :)

**Comment by brandonseydel** [comment]
You want to PR that for me?  I was just asking if that implementation is what you were after.
