### ISSUE TITLE
Create campaign with specific recipients based on tag

### ISSUE THREAD

**Issue by dkisic10** [brandonseydel/MailChimp.Net#429]
I would like to create campaign and add only contacts with tag "TestTag" as recipients. What am I missing?

```
await mailChimpManager.Campaigns.AddAsync(new Campaign
        {
            Settings = new Setting
            {
                ReplyTo = "test@test.com",
                Title = "Test campaign",
                FromName = "test@test.com",
                SubjectLine = "Test campaign",
            },
            Type = CampaignType.Regular,
            Recipients = Recipient
            {
                ListId = "hf9402ot31",
                SegmentOptions = new SegmentOptions
                {
                    Match = Match.All,
                    Conditions = new List<Condition> { new Condition { Type = ConditionType.StaticSegment, Value = "TestTag", Field = "Tags" } }
                }
            }
        });
```

**Comment by bryanp10** [comment]
If you have a static segment, does that mean it's already created?  Wouldn't you just add the segment ID to your segment options?

**Comment by ommen-microflown** [comment]
for everybody like me who also could not find this easy
this works for getting the Segment ID for a tag:

string listID = list.Id;
int segmentID = 0;
var segmentAwaitable = _mailChimpManager.ListSegments.GetAllAsync(listID).ConfigureAwait(false);
var segment = segmentAwaitable.GetAwaiter().GetResult();
 foreach (var seg in segment)
         {
                string segmentNameTmp = seg.Name;
                int segmentIdTmp = seg.Id;
                if (segmentNameTmp.Equals("Tag"))
                {
                    segmentID = (segmentIdTmp);
                }
Which you can then use in setting the recipient:

Recipient test = new Recipient();
var campaign = _mailChimpManager.Campaigns.AddAsync(new Campaign
               {
                    Settings = _campaignSettings,
                    Recipients = new Recipient
                    {
                        ListId = listID,
                        SegmentOptions = new SegmentOptions
                        {
                            SavedSegmentId = segmentID,
                        }
                    },
                    Type = CampaignType.Regular
                }).Result;

**Comment by BartWesthoff-HRO** [comment]
where do you put the tagname? is it "tag"?

**Comment by ommen-microflown** [comment]
yes the "Tag" in the code below is where you put in the Tag you wan to send the mail to.
if (segmentNameTmp.Equals("Tag"))

**Comment by ommen-microflown** [comment]
Just to be sure this working code from the Mailchimp class I created:

public static void CreateAndSendCampaign(string html, string listName, bool Test)
{
            var listsAwaitable = _mailChimpManager.Lists.GetAllAsync().ConfigureAwait(false);
            var list = listsAwaitable.GetAwaiter().GetResult().FirstOrDefault(l =>
                            l.Name.Equals(listName, StringComparison.CurrentCultureIgnoreCase));
            string listID = list.Id;
            int segmentID = 0;
            var segmentAwaitable = _mailChimpManager.ListSegments.GetAllAsync(listID).ConfigureAwait(false);
            var segment = segmentAwaitable.GetAwaiter().GetResult();
            string TagsToSendTo = "";
            if (Test)
            {
                TagsToSendTo = Properties.Settings.Default.TestTag;
            }
            else
            {
                TagsToSendTo = Properties.Settings.Default.Tags;
            }
            if (TagsToSendTo.Contains(","))
            {
                string[] TagsToSendToList = TagsToSendTo.Split(",".ToCharArray());
                foreach (string Tag in TagsToSendToList)
                {
                    foreach (var seg in segment)
                    {
                        string segmentNameTmp = seg.Name;
                        int segmentIdTmp = seg.Id;
                        if (segmentNameTmp.Equals(Tag))
                        {
                            segmentID = (segmentIdTmp);
                            sendMailing(html, listID, segmentID);
                        }
                    }
                }
            }
            else
            {
                foreach (var seg in segment)
                {
                    string segmentNameTmp = seg.Name;
                    int segmentIdTmp = seg.Id;
                    if (segmentNameTmp.Equals(TagsToSendTo))
                    {
                        segmentID = (segmentIdTmp);
                        sendMailing(html, listID, segmentID);
                    }
                }
            }
            if (segmentID == 0)
            {
                sendMailing(html, listID, segmentID);
            }

**Comment by JuditNavarro** [comment]
Hello @ommen-microflown,
First at all, thank you for try to complete with your code the question of this issue. Could you explain a bit about the Properties.Settings.Default.TestTag and Properties.Settings.Default.Tags, please? I don't understand well from where it comes those parts...

**Comment by ommen-microflown** [comment]
Those are just Strings in the SettingsFile of the project. I have two, one for sending a test mailing (a day before the real thing), and one for sending my mailing. You could basically replace them with a (comma seperated) string. If there is no comma and the string is tag1 the mail is sent to tag1. If there is a comma (like tag1,tag2,tag3), the string gets split and the mailing is sent to tag1 tag2 and tag3.

Hope that makes sense.

**Comment by JuditNavarro** [comment]
ook, thanks for the explanation :)
