### ISSUE TITLE
EcommerceProduct things missing and Update should be removed

### ISSUE THREAD

**Issue by Sumomannen** [brandonseydel/MailChimp.Net#43]
Hi

Task<Product> UpdateAsync(string productId, Product product); 
in EcommerceProductLogic can be removed. There is no update method for product only for variants. I chatted with the mailchimp support and the will probably at it.. but for now we have to remove product and add it again if we do changes on a product, like titel or vendor.

I can't see where I can reach IECommerceProductVarianceLogic, so I can change, add, delete variants from product.

**Comment by brandonseydel** [comment]
Good catch it was missing off the interface..
```CSharp
await this._mailChimpManager.ECommerceStores.Products("storeId").Variances("productId")
```

**Comment by brandonseydel** [comment]
```CSharp
        public async Task<Product> UpdateAsync(string productId, Product product)
        {
            //We need to delete and then readd in order to update...
            await this.DeleteAsync(productId).ConfigureAwait(false);
            return await this.AddAsync(product).ConfigureAwait(false);
        }

```

Are you ok with this until they release update functionality?

**Comment by Sumomannen** [comment]
Yes sounds perfect. Great support and Quick fixes.
