### ISSUE TITLE
AutomationStatus enum needs entry for "archived"

### ISSUE THREAD

**Issue by dllmr** [brandonseydel/MailChimp.Net#438]
When getting all automations, an exception is thrown if the returned data includes any archived automations. This appears to be because there is no matching entry in the AutomationStatus enum.

(A workaround for now is to retrieve automations one by one, catch the exception locally, and build up the list using returned data where no exception is thrown. Doesn't work if you actually want the archived automations though.)

**Comment by skini82** [comment]
Same issue here.
