### ISSUE TITLE
Retrieveing a member that does not exists throws error

### ISSUE THREAD

**Issue by ErikaR** [brandonseydel/MailChimp.Net#44]
Using the following method:

**Task<Member> GetAsync(string listId, string emailAddress, BaseRequest request = null)** 

throws an exception if the member does not exist. Would expect it to return null as the api itself should return 404.

**Comment by brandonseydel** [comment]
I will have this fixed and push out a nuget within the hour.  Thanks

**Comment by ErikaR** [comment]
Great. Thanks!

**Comment by kipusoep** [comment]
We ran into the exact same issue:

> Unexpected character encountered while parsing value: <. Path '', line 0, position 0.

I would expect the API wrapper to be able to handle the 404 Not Found response from Mailchimp and return a nice result or custom exception if the member doesn't exist.
Throwing a parse exception is not done imo.

**Comment by kipusoep** [comment]
:+1:

**Comment by Jetski5822** [comment]
Hey - just came across this, its kind of annoying an exception in throw, especially if you just want to check if the user exists on a list... I end up having to do this...

```
        public async Task<bool> Exists(
            string listId,
            string emailAddress)
        {
            try
            {
                var member = await _api.Members.GetAsync(listId, emailAddress);
            }
            catch (MailChimpNotFoundException)
            {
                return false;
            }
            return true;
        }
```

which kind of says I now have exception driven development :( - Not sure what the alternative is here, maybe remove the error? or provide an extension method that wraps this up without throwing the exception internally hence saving on the over head of an exception being throw.

What do you think? Shall I do a PR for it?

**Comment by brandonseydel** [comment]
Yea you can.  Just make ExistsAsync() and internally configureawait(false) on the getasync.  Thanks

**Comment by Jetski5822** [comment]
As a PR? or should I just do it in my project?

**Comment by brandonseydel** [comment]
You can submit a PR.
