### ISSUE TITLE
adding a member with status pending is added with status subscribed instead

### ISSUE THREAD

**Issue by kogalino** [brandonseydel/MailChimp.Net#45]
Hi,
not sure if this is an issue with your API or MailChimp's API.

When I add a new member with status set to pending, that member is added as subscribed.

`var member = new Member { EmailAddress = email, Status = Status.Pending };
member.MergeFields = new Dictionary<string, string>();
member.MergeFields.Add("FNAME", "koga-test");
var result = await manager.Members.AddOrUpdateAsync(listId, member);`

The result returns a member with subscribed status, but status pending is expected.

**Comment by brandonseydel** [comment]
If they are new members then the statusifnew is used.  This will get this working for as I confirmed with tests that this is true. 

Thanks.

**Comment by kogalino** [comment]
Thank you.
