### ISSUE TITLE
Campaign to contacts with specific tags?

### ISSUE THREAD

**Issue by markbenson1** [brandonseydel/MailChimp.Net#455]
Hello,

Thank you for all your work on this. 

How do I send a campaign to contacts with specific tags? I am unable to find any example on this.

Thanks again!

**Comment by rohitprk** [comment]
I am also trying to add condition for sending campaign to contact with specific tags. I added condition but not sure what Operator should  I use, as I haven't found any operator with 'contact is tagged'. Can anyone suggest?
Sample code is like below:
recipient.SegmentOptions = new SegmentOptions
{
     Match = Match.Any,
     Conditions = new List<Condition>
    {
	 new Condition { Field = "Tags", Operator = Operator.Contains, Value = Tag""}
    }
};

**Comment by rohitprk** [comment]
So I got it working. Tags are treated as segment, weird.
First get all the segment for all list then get segment id from the segments(I got it by selecting segment having same name as Tags). Then use below condition in segmentOptions:
**conditions.Add(new Condition { Field = "static_segment", Value = segmentId, Operator = Operator.StaticIs, Type=ConditionType.StaticSegment});**
This will select recipient for specific tag.

**Comment by BartWesthoff-HRO** [comment]
> So I got it working. Tags are treated as segment, weird.
> First get all the segment for specific list using listId then get segment id from the segments(I got it by selecting segment having same name as Tags). Then use below condition in segmentOptions:
> **conditions.Add(new Condition { Field = "static_segment", Value = segmentId, Operator = Operator.StaticIs, Type=ConditionType.StaticSegment});**
> This will select recipient for specific tag.

hello, can you please be a bit more clear in what you have done there?

**Comment by jemayn** [comment]
Just came upon this issue while needing similar functionality - for anyone else finding this I'll expand a bit on the answer above. I loop through my tag ids (in the var segmentIds) and add a condition for each of them allowing my target audience to be based on several different tags:

```
if (segmentIds.FirstOrDefault() != 0)
{
    var conditions = new List<Condition>();

    foreach (var segmentId in segmentIds)
    {
        conditions.Add(new Condition
        {
            Field = "static_segment",
            Value = segmentId,
            Operator = Operator.StaticIs,
            Type = ConditionType.StaticSegment
        });
    }
    
    newCampaign.Recipients.SegmentOptions = new SegmentOptions
    {
        Conditions = conditions
    };
}
```
