### ISSUE TITLE
Issue in production whereas works well in development mode

### ISSUE THREAD

**Issue by Nafhaa** [brandonseydel/MailChimp.Net#477]
Creating list/audience works fine on development mode
whereas gives error on production

![image](https://user-images.githubusercontent.com/58759165/84382224-fe55b600-ac07-11ea-8d16-9ccb78daa78c.png)

**Comment by brandonseydel** [comment]
im guessing it is an api key issue is the settings in the appsettings or configuration or set manually

**Comment by Nafhaa** [comment]
@brandonseydel thanks for revert, but same api key is used in development it works fine but when published gives above error

**Comment by Nafhaa** [comment]
@brandonseydel can you please suggest what work around can be done

**Comment by brandonseydel** [comment]
you have a repro or zip or something i can look at?

**Comment by Nafhaa** [comment]
public async Task<ActionResult> CreateList(ModelList Lmodel)
        {
            var list = new List
            {
                Name = Lmodel.Name,
                Contact = new Contact
                {
                    Company = Lmodel.Company,
                    Address1 = Lmodel.Address1,
                    Address2 = Lmodel.Address2,
                    City = Lmodel.City,
                    State = Lmodel.State,
                    Zip = Lmodel.Zip,
                    Country = Lmodel.ListCountry,
                    Phone = Lmodel.Phone
                },
                PermissionReminder = Lmodel.PermissionReminder,
                CampaignDefaults = new CampaignDefaults
                {
                    FromEmail = Lmodel.FromEmail,
                    FromName = Lmodel.FromName,
                    Subject = "Email message from dynamically created List",
                    Language = "en"
                },
                EmailTypeOption = true,
                NotifyOnSubscribe = Lmodel.NotifyOnSubscribe,
                NotifyOnUnsubscribe = Lmodel.NotifyOnUnsubscribe
            };
            try
            {
                if (ModelState.IsValid)
                {
                    var model = await Manager.Lists.AddOrUpdateAsync(list);
                    TempData["message"] = "List added successfully";
                    return RedirectToAction("GetList");
                }
                return View(MVC.Views.Default.MailChimp.Views.CreateList, Lmodel);
                //return View(Lmodel);            

            }
            catch (MailChimpException mce)
            {
                TempData["Errormessage"] = mce.Errors.FirstOrDefault().Message.ToString();
                return View(MVC.Views.Default.MailChimp.Views.CreateList, Lmodel);
                //return new HttpStatusCodeResult(HttpStatusCode.BadGateway, mce.Message);
            }
            catch (Exception ex)
            {
                TempData["Errormessage"] = ex.Message;
                return View(MVC.Views.Default.MailChimp.Views.CreateList, Lmodel);
                //return new HttpStatusCodeResult(HttpStatusCode.ServiceUnavailable, ex.Message);
            }
        }


This my code

**Comment by Nafhaa** [comment]
Please let me know if you need any other information
