### ISSUE TITLE
Members.AddOrUpdateAsync

### ISSUE THREAD

**Issue by Neimantas** [brandonseydel/MailChimp.Net#497]
It seems that the mailchimp changed the signature.

Tested using:
var member = new Member { EmailAddress = $"lol@lol.lt", StatusIfNew = Status.Subscribed };
            member.MergeFields.Add("FNAME", "HOLY");
            member.MergeFields.Add("LNAME", "COW");
            var test4 = _mailChimpManager.Members.AddOrUpdateAsync(dto.ListId, member).Result;

Inner Exception 1:
MailChimpNotFoundException: Unable to find the resource at https://us19.api.mailchimp.com/3.0/lists/373266/members/d6733fcc716a5434f8ae35da3accbfe3 

Other methods, for example checking if user exist works perfectly.

**Comment by gtmadev** [comment]
Why is this closed with no explanation? I am also seeing this same issue. Was it resolved??? Would the OP care to say why he closed it or how this was resolved???
