### ISSUE TITLE
Error deserializing member with Notes

### ISSUE THREAD

**Issue by ThomasMldr** [brandonseydel/MailChimp.Net#5]
I'm trying to get a member (through `Members.GetAsync(listId, emailAddress)`) from mailchimp to which I've written a note manually on the mailchimp site, and then I get this error:

`Cannot deserialize the current JSON object (e.g. {"name":"value"}) into type 'System.Collections.Generic.IEnumerable'1[System.Object]' because the type requires a JSON array (e.g. [1,2,3]) to deserialize correctly.
To fix this error either change the JSON to a JSON array (e.g. [1,2,3]) or change the deserialized type so that it is a normal .NET type (e.g. not a primitive type like integer, not a collection type like an array or List<T>) that can be deserialized from a JSON object. JsonObjectAttribute can also be added to the type to force it to deserialize from a JSON object.
Path 'last_note.note_id', line 1, position 579.`

Any thoughts?

**Comment by ThomasMldr** [comment]
Okay so I found that `last_note` is not a list of notes but just a single note , so obviously it can't deserialize to an IEnumerable<object>.
Here's what came back with my member:
`   "last_note":{  
      "note_id":281,
      "created_at":"2016-04-15T07:10:07+00:00",
      "created_by":"58898545",
      "note":"test123"
   },`
Also `last_note` doesn't correspond to a regular note as it's id is labeled with `note_id` instead of just `id`, so that could cause some problems as well..
As I was going through the code, I also noticed in the NoteLogic that sometimes you did:
`using (var client = this.CreateMailClient("lists"))`
instead of `using (var client = this.CreateMailClient("lists/"))` with the trailing slash, that caused a lot of frustration over some 404's before I noticed the problem :sweat_smile:

**Comment by ThomasMldr** [comment]
Submitted pull request that changes Notes to LastNote here: https://github.com/brandonseydel/MailChimp.Net/pull/6

**Comment by brandonseydel** [comment]
Merged pull request #6 into Mail chimp.  Will be deploying an updated nuget package in an hour or so.

**Comment by brandonseydel** [comment]
@ThomasMldr A lot of the times the / isn't needed hopefully this is a one off thing.  I will try to go through and find any that actually need it.  Help would be appreciated :)
