### ISSUE TITLE
ListSegmentLogic AddMemberAsync Is Failing

### ISSUE THREAD

**Issue by richardburns** [brandonseydel/MailChimp.Net#50]
I believe the URLs are slightly off here as according to the documentation it should be:

POST /lists/{list_id}/segments/{segment_id}/members

But it looks like the code is missing the /members

**Comment by richardburns** [comment]
If you append "/members" to the segmentId string you pass into AddMemberAsync then a 200 OK is returned but the user is not added to the segment

**Comment by brandonseydel** [comment]
I fixed the missing :/members

**Comment by richardburns** [comment]
Do you know when you will update the NuGet package?

Many thanks

**Comment by brandonseydel** [comment]
I am updating it right now.  Thanks.
