### ISSUE TITLE
Exception: Invalid resource

### ISSUE THREAD

**Issue by Kla3mus** [brandonseydel/MailChimp.Net#500]
Hi!

I'm using your Library, Version 4.2.1 from Nuget, in a very simple way:

IMailChimpManager mcm = new MailChimpManager(MailChimpApiKey);
await mcm.Members.AddOrUpdateAsync(MailChimpListId, new Member																							 {																								 
    EmailAddress = model.Email, 																								 
    Status = Status.Subscribed																							 });

The last three days or so I get a weird exception when _AddOrUpdateAsync()_ executes. -> "_Invalid Resource_"
There is a collection called Errors, where there is one element of type _MailChimpError_, that has a field; "_MMERGE3_" and a Message; "_Please enter a value_"

The message of the exception is:
_Title: Invalid Resource
Type: http://developer.mailchimp.com/documentation/mailchimp/guides/error-glossary/
Status: 400
Detail: Your merge fields were invalid.
Errors: MMERGE3 Please enter a value_

Before these three-four days everything has been working perfectly.

Is there an update coming, am I doing something wrong, should I change something?

**Comment by mikehachen** [comment]
Pretty sure, MERGE3 field is a mandatory field, so you have to provide a value for the field. You can check this online in your MC account.

**Comment by Kla3mus** [comment]
Hmm.. 

As far as I can see, there is no MMERGE3 Property in the Member class. I have a property called MergeFields, that is a dictionary, but I don't understand why a field that is not specified in the Member class should be mandatory? 

Where in the MC account can i find if a field is mandatory? (I have just done the integration, not an avid user of MC in general. Sorry)

**Comment by mikehachen** [comment]
Merge fields are custome fields. Every mailchimp customer can/will have different fields. Thats why they can't be membes... You'll find the merge fields in the settings of the corresponding mailchimp list (or audience list, I think they now call it audience list)...

**Comment by Kla3mus** [comment]
Thank you so much. I found it. 

Audience -> All Contacts -> Settings -> Audience fields and *|MERGE|* tags

Here they have a column called Required? with a checkbox in, that they had selected. :)

Your help is much appreciated!
