### ISSUE TITLE
CreateList Help

### ISSUE THREAD

**Issue by AJGarrett** [brandonseydel/MailChimp.Net#51]
I'm writing here more for help than declaring this an issue as I'm pretty sure this is more related to my lack of experience with async methods.

I am moving my organization to MC, and trying to create a wrapper class in my business logic to pass other business objects into it, and then utilize your methods.     I have been able to run GetAll() methods and return data from MailChimp, but have not been able to create lists or members.   

Here's a sample of my code:

```
public class myChimp
{
       private MailChimp.Net.MailChimpManager account { get; set; }

        public AIAChimp() 
        {
            account = new MailChimp.Net.MailChimpManager("defaultAPIKey");
        }
        public AIAChimp(string apiKey)
        {
            account = new MailChimp.Net.MailChimpManager(apiKey);
        }
        
        public async System.Threading.Tasks.Task<IEnumerable<MailChimp.Net.Models.List>> GetLists()
        {
            var listCollection = await account.Lists.GetAllAsync().ConfigureAwait(false);
            

            return listCollection;
        }

        public async System.Threading.Tasks.Task<MailChimp.Net.Models.List> CreateList(string listName)
        {
            var list = new MailChimp.Net.Models.List { Name = listName, 
                    PermissionReminder = "default", 
                    CampaignDefaults = { FromEmail = "test@test.com", 
                    FromName = "myCompany" }, Contact = { Company = "myCompany" } };

            return await account.Lists.AddOrUpdateAsync(list).ConfigureAwait(false);
            
        }
}
```

So with that, when I run these commands, the first works, and these second one throws an error at t2.Wait(), site a null value:

 ```
myChimp c = new myChimp();
            System.Threading.Tasks.Task<IEnumerable<MailChimp.Net.Models.List>> t = c.GetLists();
            t.Wait();
            foreach (MailChimp.Net.Models.List list in t.Result)
            {
                id = list.Id;
                Console.WriteLine(list.Name + " - " + list.DateCreated + " - " + list.Id + " - " + list.Stats.MemberCount);
            }

            System.Threading.Tasks.Task<MailChimp.Net.Models.List> t2 = c.CreateList("All US Staff");
            t2.Wait();
           Console.WriteLine(t1.Result.Id);
           
```

Right now, I am using a Free Account.    I can also see errors in the API Status of my account for /PUT stating "The requested resource could not be found."

**Comment by brandonseydel** [comment]
```CSharp
var c = new myChimp();
var t = await c.GetLists();

foreach(var list in t){
  id = list.Id;
  Console.WriteLine(list.Name + " - " + list.DateCreated + " - " + list.Id + " - " + list.Stats.MemberCount);
}

var t2 = await c.CreateList("All US Staff");
Console.WriteLine(t1.Id);
```

**Comment by AJGarrett** [comment]
Brandon, Thanks - 

question, the second code block is static

```
static void Main()
{
           System.Threading.Tasks.Task<MailChimp.Net.Models.List> t2 = c.CreateList("All US Staff");
           t2.Wait();
           Console.WriteLine(t2.Result.Id);
}
```

so I can't add await.   (again, likely my ignorance here)

the t.Wait() worked in a static block.

**Comment by brandonseydel** [comment]
```CSharp
var id = Task.Run(async () => { 
var list = await c.CreateList("All US Staff");
return list.Id;
}).Result;
Console.WriteLine(id);
```
BTW this is all in editor ;)

**Comment by brandonseydel** [comment]
Do you want me to close this or do you have additional questios?

**Comment by AJGarrett** [comment]
So I still get this: {"Object reference not set to an instance of an object."} when running that code.

Am I missing a required parameter when passing a new list to MC?

I'm sure this is my issue, just stuck.   I missed the documentation.   Being that this is sort of irrelevant to the function of the project, if you want to close I'm okay with that

**Comment by AJGarrett** [comment]
I found my issue.   I wasn't passing all the required fields for creating a list.
