### ISSUE TITLE
1.5.4 package seems to be breaking things

### ISSUE THREAD

**Issue by Jetski5822** [brandonseydel/MailChimp.Net#52]
The 1.5.4 package doesnt seem to be working for me, when working with lists. 

Not sure why yet, but if I downgrade back to 1.5.3 all my tests go green again. Will investigate, but thought I d give you a heads up.

**Comment by Jetski5822** [comment]
Okay, I had logic around 404's, that logic changed with this commit https://github.com/brandonseydel/MailChimp.Net/commit/34675a08386eecf377df79bc4c5f88e15d2078a7

**Comment by brandonseydel** [comment]
I tried to be more descriptive when a 404 happened.  I should have included that in the release notes...
