### ISSUE TITLE
member doesnot show up in mailchimp

### ISSUE THREAD

**Issue by arham-anees** [brandonseydel/MailChimp.Net#520]
I'm using mailChimp for first. I'm adding members via API but it doesnot show up in my mailchimp audience list.
the problem is that I tested it on my local machine, it added users to my list but when I deployed it to server it has not added even a single member.
but when I try to get users via API i get users correctly. I add tags too and that are correct too.
my problem is that is there any hidden list where these users show up but I have used list ID of my main list(only one I have).
tried re-deploying but still the same issue

` IMailChimpManager manager = GetMailChimpManager();
        Member member = new Member()
        {
          EmailAddress = email,
          Status = Status.Subscribed
        };
        member = manager.Members.AddOrUpdateAsync(listId, member).ConfigureAwait(false).GetAwaiter().GetResult();
        var confirmMember = manager.Members.GetAsync(listId, email).ConfigureAwait(false).GetAwaiter().GetResult();
        if (confirmMember == null) return new Result { StatusCode = 417, Message = "Operation failed" };
        var result = AddTag(email, "Day 1");
        if(result.StatusCode==200)
        return new Result() { StatusCode = 200, Message = "Member added successfully", Data=member};
        else return new Result() { StatusCode = 200, Message = "Member added successfully but failed to add tag", Data = member };`

Is there anyone who has faced the same problem?

I'm using
targetFramework 4.7.2
Webforms project

**Comment by mikehachen** [comment]
Mailchimp automatically sends an email to new recipients that have been added via API. In this email, the new users must confirm that they may be added. As long as this confirmation has not been made, the users will not be displayed online.

**Comment by arham-anees** [comment]
@mikehachen thanks for your timely response. One thing i want to confirm according to our scenario, we need to save user's email and then send them transactional mails.
what status do you suggest to avoid user confirmation?

**Comment by mikehachen** [comment]
There is no way to prevent this automatic email. As soon as a new user is added via API, this email will be sent. The only way to prevent this email is to manually import the new users via Mailchimp website.

**Comment by arham-anees** [comment]
@mikehachen thanks for response.
saved my night
