### ISSUE TITLE
Batch subscribe parameters skip_merge_validation and skip_duplicate_check not supported

### ISSUE THREAD

**Issue by bencurthoys** [brandonseydel/MailChimp.Net#523]
The batch subscribe / unsubscribe endpoint supports query string parameters "skip_merge_validation" and "skip_duplicate_check", 
https://mailchimp.com/developer/api/marketing/lists/batch-subscribe-or-unsubscribe/

but these don't seem to be accessible in the logic:

     public async Task<BatchListResponse> BatchAsync(BatchList batchList, string listId)
        {
            using (var client = CreateMailClient($"lists/{listId}"))
            {
                var response = await client.PostAsJsonAsync(string.Empty, batchList).ConfigureAwait(false);

                await response.EnsureSuccessMailChimpAsync().ConfigureAwait(false);
                return await response.Content.ReadAsAsync<BatchListResponse>().ConfigureAwait(false);
            }
        }

**Comment by gdycus** [comment]
I could also use support for "skip_merge_validation". Although I need the support added to Members.AddOrUpdateAsync(). Thanks!

**Comment by villamike** [comment]
Agree with @gdycus - seems like a critical path for allowing users to fully manage updating Member.Status when using Members.AddOrUpdateAsync()
