### ISSUE TITLE
Microsoft.Extensions.Http 5.0.0 update?

### ISSUE THREAD

**Issue by matthewrwilliams** [brandonseydel/MailChimp.Net#524]
@dependabot-preview has committed this change to update from 3.1.8 to 5.0.0.  Is there any update on when this will be merged?  We've tried downgrading, but this requires multiple downgrades related to this package and makes it difficult to maintain a larger codebase.

Open commit. 
 https://github.com/brandonseydel/MailChimp.Net/pull/514/commits/9cfe5978124a81988140e90528e7321d6918dd7b

Thank you!

**Comment by ronaldbarendse** [comment]
This library isn't preventing you from upgrading `Microsoft.Extensions.Http` to version 5.0.0, right? IMHO MailChimp.NET should target the lowest possible version, so it's compatible with the widest range of projects (that might have other dependencies that can't be updated): https://softwareengineering.stackexchange.com/questions/336279/policies-on-nuget-dependencies-versions-when-developing-a-library.

**Comment by brandonseydel** [comment]
Let me look into this some.
