### ISSUE TITLE
Can't access subscription status for archived members

### ISSUE THREAD

**Issue by jeremy-lafond** [brandonseydel/MailChimp.Net#529]
I currently archive my inactive contacts. I wish to unarchive them if they become active once again. However, some of these contacts are unsubscribed. From what I can see, when I archive a contact the member status becomes "Archived" therefore I do not see any way for me to know if the user is actually subscribed or unsubscribed to my emails (Email Marketing Column). 

Therefore I was wondering if there is a way to see if an archived user is subscribed or unsubscribed to my emails so I can manage my contacts more efficiently.

**Comment by Aaronontheweb** [comment]
Having this issue too

**Comment by follesoe** [comment]
Same, need a way to list all contacts, including archived contacts.
