### ISSUE TITLE
Null pointer exception: request parameter

### ISSUE THREAD

**Issue by REDECODE** [brandonseydel/MailChimp.Net#53]
Hi,
in many (but not all) Logic.cs files, for example ActivityLogic.cs, the GetAllAsync() has the parameter request = null if not passed. 
But few line below its used with request.ToQueryString() that throw an null pointer exception.

It's correct this behaviour or I missing something?

Thanks

**Comment by REDECODE** [comment]
Oh I see.. or I change that line in **request?.ToQueryString()** or I need to pass the request parameter valorized.
But please as a basic rule don't create an optional parameter if you need to valorize it

Thanks, and waiting for a new update i start the changes in my repository

**Comment by brandonseydel** [comment]
Those have been missed!  I will comb through all of the code and make sure that there isn't any of that and will push an update today.  Thanks.

**Comment by brandonseydel** [comment]
All fixed next release
