### ISSUE TITLE
Can't Get Members From Segments

### ISSUE THREAD

**Issue by michaeldinsightly** [brandonseydel/MailChimp.Net#54]
Hello,

I'm trying to get members that belong to a ListSegment. I can get members from Lists perfectly fine, but when making the ListSegments.GetMemberResponseAsync(listId, segmentId) call, the result always has a count of 0. Same thing happens with GetAllMembersAsync().

When making the same GET call with PostMan, the proper members are returned.

Do you have any insight into why this is?

Thanks,
Michael

**Comment by brandonseydel** [comment]
I need more info or a test case in order to fix this issue

**Comment by michaeldinsightly** [comment]
Hey Brandon,

We resolved the issue by updating the package version that we were using. You can close this ticket.
