### ISSUE TITLE
Enhancement: Member Events API

### ISSUE THREAD

**Issue by Aaronontheweb** [brandonseydel/MailChimp.Net#543]
https://mailchimp.com/developer/marketing/api/list-member-events/ - this would be really useful for us!

**Comment by Aaronontheweb** [comment]
P.S. Just had my company @petabridge sign up for a small sponsorship for you - we love MailChimp .NET and are working on using it in some more internal line of business applications for helping us manage our email marketing internally.

**Comment by brandonseydel** [comment]
@bjkippax PR would be great!

**Comment by bjkippax** [comment]
@brandonseydel Bump.

**Comment by bjkippax** [comment]
@brandonseydel bump again?

**Comment by bjkippax** [comment]
@brandonseydel a bit disappointed this was closed. There are unanswered questions and we’re still very keen to implement this. Unfortunately I cannot create a PR without permissions and the unit/integration tests fail too.

**Comment by Aaronontheweb** [comment]
Do you have a link to the PR?

**Comment by brandonseydel** [comment]
@bjkippax Brining this one back.

**Comment by alexariza95** [comment]
is there now any option to trigger events with this library?

**Comment by bjkippax** [comment]
@brandonseydel sorry to sound like a broken record but I still cannot publish branches to the repo.

![image](https://user-images.githubusercontent.com/36036691/169658221-94b14d38-a1d1-4f4b-954a-06713b2204ac.png)
![image](https://user-images.githubusercontent.com/36036691/169658260-a6d0162d-9d3d-4763-8cc0-c14fe9853e38.png)
![image](https://user-images.githubusercontent.com/36036691/169658279-4a7557d3-5dc7-4902-9a1b-788b748eeec9.png)

**Comment by brandonseydel** [comment]
> @brandonseydel sorry to sound like a broken record but I still cannot publish branches to the repo.
> 
> ![image](https://user-images.githubusercontent.com/36036691/169658221-94b14d38-a1d1-4f4b-954a-06713b2204ac.png) ![image](https://user-images.githubusercontent.com/36036691/169658260-a6d0162d-9d3d-4763-8cc0-c14fe9853e38.png) ![image](https://user-images.githubusercontent.com/36036691/169658279-4a7557d3-5dc7-4902-9a1b-788b748eeec9.png)

You need to fork the repo make your changes and then PR then with github.
