### ISSUE TITLE
Add member to list fails when adding merge fields

### ISSUE THREAD

**Issue by bjarnef** [brandonseydel/MailChimp.Net#55]
I have used the example "Adding User To List" from readme.

```
public async Task<Member> AddMemberToList()
{
    var listId = "TestListId";
    var member = new Member { EmailAddress = $"githubTestAccount@test.com", Status = Status.Subscribed };
    member.MergeFields.Add("FNAME", "HOLY");
    member.MergeFields.Add("LNAME", "COW");
    var result = await this.mailChimpManager.Members.AddOrUpdateAsync(listId, member);
    return result;
}
```

but when I request this method, it fails when I include the merge fields.
```
var t = helper.AddMemberToList();
t.Wait();
```

![image](https://cloud.githubusercontent.com/assets/2919859/16521007/403d4e28-3f94-11e6-8e8e-33750e068da8.png)

For the list I have also ensure it has the fields "FNAME" and "LNAME".

Why does the part fails?

Furthermore I have previous used this Mailchimp API wrapper https://github.com/danesparza/MailChimp.NET where it has option for the Double Opt-in Process: http://kb.mailchimp.com/lists/signup-forms/the-double-opt-in-process .. e.g. send a confirmation e-mail where it first added the member to the list when its has been confirmed in the email ... and you could also specify it should send an "welcome" email. How to do these things with this Mailchimp wrapper?

**Comment by bjarnef** [comment]
It seems it is because `MergeFields` property on member is null?

If I create a new dictionary before adding the fields, then it is working:
```
member.MergeFields = new Dictionary<string, string>();
member.MergeFields.Add("FNAME", "HOLY");
member.MergeFields.Add("LNAME", "COW");
```

and in my view I have:
```
var t = helper.AddMemberToList();
t.ConfigureAwait(false);
```

**Comment by brandonseydel** [comment]
fixed in latest
