### ISSUE TITLE
HttpClient doesn't handle compression

### ISSUE THREAD

**Issue by kbolton** [brandonseydel/MailChimp.Net#56]
I added a HttpClientHandler to the HttpClient in BaseLogic.CreateMailClient(string resource) and my network traffic size improved by at least 5x. That is - it was at least 5 time smaller.

`            HttpClientHandler handler = new HttpClientHandler();
            if (handler.SupportsAutomaticDecompression)
                handler.AutomaticDecompression = System.Net.DecompressionMethods.GZip | System.Net.DecompressionMethods.Deflate;
            var client = new HttpClient(handler)
                             {
                                 BaseAddress =
                                     new Uri($"https://{this.DataCenter}.api.mailchimp.com/3.0/{resource}")
                             };            
`

See the "Using automatic decompression with HttpClient" section of https://blogs.msdn.microsoft.com/dotnet/2013/06/06/portable-compression-and-httpclient-working-together/.

**Comment by brandonseydel** [comment]
Enabled next release

**Comment by kbolton** [comment]
Fantastic!

------ Original Message ------
