### ISSUE TITLE
How can we create a template ?

### ISSUE THREAD

**Issue by roopeshkurian** [brandonseydel/MailChimp.Net#57]
In older versions we can create template like this

MailChimp.Templates.TemplateAddResult result = mailChimpManager.AddTemplate(mailTemplates.TemplateName, mailTemplates.HTMLContent);

Can someone help me?

**Comment by brandonseydel** [comment]
You will need to get latest 
then
```CSharp
await _mailChimpManager.Templates.CreateAsync("name", "folderId", "html");
```

**Comment by roopeshkurian** [comment]
Thank you so much. It worked..
