### ISSUE TITLE
Model Enhancements PR

### ISSUE THREAD

**Issue by TonyValenti** [brandonseydel/MailChimp.Net#572]
I'd like to make a few enhancements if the PR would be accepted:

1. I'd like to create a base "Model" class that all Models inherit from.
2. I'll move the ```Id``` property into the model class.
3. I will decorate the models with a ```DebuggerDisplayAttribute``` that makes it easy to inspect the objects in VS.

Would a PR that does the above be accepted?

**Comment by TonyValenti** [comment]
@brandonseydel  ?

**Comment by brandonseydel** [comment]
Sounds good to me.  Go ahead with the PR.

**Comment by TonyValenti** [comment]
@brandonseydel Currently there are only two .NET versions that are supported: .NET 4.8 and .NET 6.0.  Do you have any objection if I drop support for the other versions as well?

**Comment by TonyValenti** [comment]
Actually, per this link:
https://docs.microsoft.com/en-us/lifecycle/products/microsoft-net-framework

It looks like 4.6.2-4.8 are still supported.  Because of that, I'll just drop 4.5 support.

**Comment by TonyValenti** [comment]
@brandonseydel .  I just submitted a PR.
