### ISSUE TITLE
MailChimpManager.Lists.BatchAsync fails when a merge field of type Address is defined

### ISSUE THREAD

**Issue by jargeek** [brandonseydel/MailChimp.Net#574]
Hi guys!

Thanks for your great work with this library.

When I call `MailChimpManager.Lists.BatchAsync` method it fails when deserialze the response if a merge field of type Address is defined in the list.

**Repro steps:**

1. Define a merge field of type address

![image](https://user-images.githubusercontent.com/7682139/172073493-b2b38747-d8f1-42cc-9f39-a38b516dd05e.png)

2. Prepare a request and call the  `MailChimpManager.Lists.BatchAsync` method.
3. It fails with the following error: 

> "Unexpected character encountered while parsing value: {. Path 'updated_members[0].merge_fields.ADDRESS', line 1, position 251."

This is an example of the JSON response:

```JSON
{
    "new_members": [],
    "updated_members": [
    {
        "id": "c6e1d4ccb8ef0bf17541fe46530849b7",
        "email_address": "Jojomclean67@icloud.com",
        "unique_email_id": "d79422687a",
        "email_type": "html",
        "status": "subscribed",
        "merge_fields": {
            "FNAME": "User First Name",
           "LNAME": "User Last Name",
           "ADDRESS": {
               "addr1": "215 Street1",
               "addr2": "",
               "city": "Modesto",
               "state": "CA",
               "zip": "95350",
               "country": "US"
        }
    }
}
```

Seems like the issue is that Address property is defined as string in [MergeFields](https://github.com/brandonseydel/MailChimp.Net/blob/master/MailChimp.Net/Core/Responses/MergeFields.cs#L14) class.

**Comment by betterunite** [comment]
This is still an issue for us... Is there a resolution or an approach to circumvent it?  Thank you.
