### ISSUE TITLE
New Member is not added

### ISSUE THREAD

**Issue by Shkryabminer** [brandonseydel/MailChimp.Net#585]
Hello, everyone.
I try to add new Member with AddOrUpdateAsync(id, member) and after it I try to get new member, but it's null. Code example is here:
private async Task AddEmailToMailchimp(AppUser user)
        {
            if (string.IsNullOrWhiteSpace(user.Email)) return;
            var lists = await _mailChimpManager.Lists.GetAllAsync();
            var enumerable = lists.ToList();
            if (!enumerable.Any())
                return;
            var id = enumerable.FirstOrDefault().Id;

            await _mailChimpManager.Members.AddOrUpdateAsync(id, new Member
            {
                EmailAddress = user.Email,
                StatusIfNew = Status.Subscribed,
                Status = Status.Subscribed
            });

            var currentUser =await GetExistingMember(user.Email);
            var em = currentUser?.EmailAddress;// breackpiont for check data
        }

        private async Task<Member> GetExistingMember(string email)
        {
            Member member = null;

            if (!string.IsNullOrWhiteSpace(email))
            {
                var lists = await _mailChimpManager.Lists.GetAllAsync();
                var enumerable = lists.ToList();
                if (enumerable.Any())
                {
                    var id = enumerable.FirstOrDefault().Id;
                    var members = _mailChimpManager.Members;

                    var listMembers = await members.GetAllAsync(id).ConfigureAwait(false);
                    var currentMember = listMembers.Where(m => m.EmailAddress == email).FirstOrDefault();
                    member = currentMember;//null
                }
            }
            return member;
        }
ListId is matched, I checked all input data

**Comment by Shkryabminer** [comment]
Can somebody help me?

**Comment by manzanotti** [comment]
How many lists do you have?

Looking at this line:

```var currentMember = listMembers.Where(m => m.EmailAddress == email).FirstOrDefault();```

if you have more than one list, and the member isn't in the last list you enumerate over, then you are setting member to null.

Try using:

```var list = await _mailChimpManager.Members.GetAsync(listId, emailAddress);```

to see if the user has been added to that specific list.
