### ISSUE TITLE
Add additional parameters to CampaignRequest

### ISSUE THREAD

**Issue by gdau** [brandonseydel/MailChimp.Net#59]
Hi,

Would it be possible to add additional filter parameters to the CampaignRequest object?

All the valid parameters are available here: http://developer.mailchimp.com/documentation/mailchimp/reference/campaigns/#read-get_campaigns

and I currently rely on some of the date fields such as "since_send_time" and "since_create_time".

Thanks!

Gav

**Comment by brandonseydel** [comment]
Closed with #60
