### ISSUE TITLE
MailChimp error since v5.4 "Status is required when using since_last_campaign filter." 

### ISSUE THREAD

**Issue by saxx** [brandonseydel/MailChimp.Net#596]
I'm loading all members of a list with

````
var members = (await mc.Members.GetAllAsync(list.Id)).ToList();
````

This worked fine in v5.3.1. After update to v5.4.0 I found that the same code returns 

````
MailChimp.Net.Core.MailChimpException
Title: Invalid Resource
Type: https://mailchimp.com/developer/marketing/docs/errors/
Status: 400
Instance: <--->
Detail: Status is required when using since_last_campaign filter.
Errors: 
Request URI:https://us5.api.mailchimp.com/3.0/lists/<--->/members?vip_only=False&since_last_campaign=False&count=0&offset=0
````

I assume this is because of this commit, where the since_last_campaign parameter has been added: https://github.com/brandonseydel/MailChimp.Net/commit/603ad4467902dbddefadd82b779bcca5854b3eaf

Maybe it would be useful to make the `SinceLastCampaign` property nullable, and only send it to MailChimp if it actually has a value set? What do you think? I'm happy to do a PR, but I'm not sure what's the best solution for the library would be (most consistent with other functionality)?

**Comment by brandonseydel** [comment]
I am nulling it out thank you!
