### ISSUE TITLE
Can't get total_items when using calls such as GetSentToRecipientsAsync

### ISSUE THREAD

**Issue by gdau** [brandonseydel/MailChimp.Net#61]
Since calls such as GetSentToRecipientsAsync return the IEnumerable of the sent_to directly (without a wrapping object), there are fields such as "total_items" available in the response which are not available (this is the total number of items retrieved regardless of pagination parameters). Exposing these returned parameters would be useful when you are trying to page through a long list of recipients.

In the case above, there is already a SentToResponse (although this does not currently contain the "total_items" return value) but this is discarded inside the API. I would suggest adding the extra return values and returning the SentToResponse from the api call rather than returning sendToResponse.Recipients.

The documentation for this call can be seen here:

http://developer.mailchimp.com/documentation/mailchimp/reference/reports/sent-to/

**Comment by brandonseydel** [comment]
Missed this one I have one that wraps and one that unwraps normally based on the consumer need.  This will go out in the next 5 mins.
