### ISSUE TITLE
ListEvent's Properties property should be public

### ISSUE THREAD

**Issue by mcetkovsky** [brandonseydel/MailChimp.Net#613]
```
[JsonProperty("properties")]
IDictionary<string, object> Properties { get; set; }
```

According to [Mailchimp docs](https://mailchimp.com/developer/marketing/api/list-member-events/add-event/), the `Properties` property might contain an optional list of properties.

PS: This is a duplicate of [603](https://github.com/brandonseydel/MailChimp.Net/issues/603) as the original issue was closed by a bot due to no response from the package owner.

**Comment by brandonseydel** [comment]
Fixed
