### ISSUE TITLE
TLS version

### ISSUE THREAD

**Issue by AmrTealeb** [brandonseydel/MailChimp.Net#617]
Does this NuGet package use TLS v1.2 or lower version?
because i can see this announcement on mailchimp site
[https://mailchimp.com/developer/release-notes/scheduled/](https://mailchimp.com/developer/release-notes/scheduled/)

**Comment by AmrTealeb** [comment]
I am using the package with dot net core 3.1

**Comment by brandonseydel** [comment]
You set this in the framework not in the client.  A quick search will show you the details although I suspect you already are using 1.2
