### ISSUE TITLE
System.Net.Http.HttpRequestException: 'No such host is known. (us13.api.mailchimp.com:443)'

### ISSUE THREAD

**Issue by clinttreadway** [brandonseydel/MailChimp.Net#622]
I want to start by saying his library works great for setting up a connection to MailChimp!

I have setup a basic call to my MailChimp account to retrieve subscriber data based on email addresses.  I am using the GetAsync method like so:

**var response = await mailChimpManager.Members.GetAsync(listId, email);**

When I make that call, I am receiving the following exception:

**System.Net.Http.HttpRequestException: 'No such host is known. (us13.api.mailchimp.com:443)'**

I do not believe this issue is due to the library, but I am wondering if anyone has run into this issue before?

**Comment by bencurthoys** [comment]
![image](https://github.com/brandonseydel/MailChimp.Net/assets/4848856/d0de30e4-41be-4bc9-acf5-39ea49891ca9)

That hostname definitely exists. I'd suggest checking whether you could ping it from your development machine or server, and if not, checking your network setup.
