### ISSUE TITLE
.NET framework compatibility

### ISSUE THREAD

**Issue by danbramall** [brandonseydel/MailChimp.Net#624]
I have been asked to assess the viability of integrating this package into an old website running .NET 4.7.2 with no .NET Core capability. Would this package be compatible?

Many thanks

**Comment by mtomas-mpm** [comment]
Sure! As specified in [NuGet package](https://www.nuget.org/packages/MailChimp.Net.V3/) it works on .Net Framework 4.5+

**Comment by danbramall** [comment]
Ah, I missed that! Thanks for confirming :)
