### ISSUE TITLE
JsonReaderException

### ISSUE THREAD

**Issue by pockhiss** [brandonseydel/MailChimp.Net#628]
I get the following exception:
Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0. atNewtonsoft.Json.JsonTextReader.ParseValue() atNewtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter) atNewtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent) atNewtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType) atNewtonsoft.Json.JsonSerializer.Deserialize[T](JsonReader reader) atMailChimp.Net.Core.Helper.Deserialize[T](Stream stream) atMailChimp.Net.Core.Helper.d__0.MoveNext() --- End of stack trace f

To debug, is there a way I can get the offending json?

**Comment by IT-VBFK** [comment]
The cause of such an exception is in the most cases, that "some API" expects a json string but got some HTTP code back.
e.g. if you get an 404 HTTP page back.
