### ISSUE TITLE
Carts GetAllAsync

### ISSUE THREAD

**Issue by SergeyKotyushkin** [brandonseydel/MailChimp.Net#64]
Hello!

I have one ECommerceStores.Cart that was created by ECommerceStores.Carts("storeid").AddAsync(mcCart).
When I try ECommerceStores.Carts("storeid").GetAsync("id") then it works right.
But when I try ECommerceStores.Carts("some_storeid").GetAllAsync() then it does not work. I am getting error: "Error converting value {null} to type 'System.DateTime'. Path 'carts[0].created_at'".

Thanks

**Comment by brandonseydel** [comment]
Closed with 6594a40cc76a7363e60f6de67fe6d3fd6ffc5d70

**Comment by SergeyKotyushkin** [comment]
Hi,

Same with UpdatedAt now

**Comment by brandonseydel** [comment]
Checked in and fixed.  I cleaned up a lot of dates and of course missed that one.  I also released a new nuget package.

**Comment by SergeyKotyushkin** [comment]
Thanks!
