### ISSUE TITLE
Campaign Creation and Upload email template

### ISSUE THREAD

**Issue by roopeshkurian** [brandonseydel/MailChimp.Net#66]
Hello

I am trying to run a campaign. For that I am setting a template to campaign . But my campaign id is bigger than normal integer. So its giving

System.OverflowException: Value was either too large or too small for an Int16. Value was either too large or too small for an Int16.

 ContentTemplate template = new ContentTemplate()
                {
                    id = "128697"  //Put your template id that you want to use
                };

Can you please check it for me?

Thanks and Regards
Roopesh

**Comment by brandonseydel** [comment]
Where are you doing this.  I don't see a type ContentTemplate anywhere.

**Comment by roopeshkurian** [comment]
Hi, Sorry , i was referring some other wrapper for similar function.  Can you please give your method?

**Comment by brandonseydel** [comment]
_mailChimpManager.Content.[AddOrUpdateAsync](https://github.com/brandonseydel/MailChimp.Net/blob/master/MailChimp.Net/Logic/ContentLogic.cs#L54)(campaignId, [contentRequest](https://github.com/brandonseydel/MailChimp.Net/blob/master/MailChimp.Net/Core/Requests/ContentRequest.cs#L18))

**Comment by roopeshkurian** [comment]
I have a saved templates id. How can i use already saved template with this method? or do you have any other method to use campaign id and template id ?

**Comment by brandonseydel** [comment]
You just add contentRequest and set the template with the id of the template you already inserted

**Comment by roopeshkurian** [comment]
Hi 
I tried to do as you said 

  MailChimp.Net.MailChimpManager _mailChimpManager = new MailChimpManager();
                    MailChimp.Net.Core.ContentRequest contentRequest = new MailChimp.Net.Core.ContentRequest();
                    var temp = await _mailChimpManager.Templates.GetAsync(model.TemplateId);

But when i execute the last line I am getting the following error.  I dont know what  I am doing wrong. Can you please help me?

Type provided must be an Enum.
Parameter name: enumType

**Comment by brandonseydel** [comment]
Have you gotten latest looks like a fix went for this 4 days ago

**Comment by roopeshkurian** [comment]
I will update and get back to you. Thank you for the prompt response.

**Comment by roopeshkurian** [comment]
Yes, you are right. Latest version solved most of the issues. But I got one more error while executing the campaign.

    MailChimp.Net.MailChimpManager _mailChimpManager = new MailChimpManager();
                    MailChimp.Net.Core.ContentRequest contentRequest = new MailChimp.Net.Core.ContentRequest();
                    contentRequest.Template  = await _mailChimpManager.Templates.GetAsync(model.TemplateId);
                    var setContentStatus = await _mailChimpManager.Content.AddOrUpdateAsync(model.CampaignId, contentRequest);
                    await _mailChimpManager.Campaigns.SendAsync(model.CampaignId);


Your Campaign is not ready to send. 

How to change the status to ready?

**Comment by kiquenet** [comment]
Good patterns and practices about SendAsync ? how get Errors , error handling ?
