### ISSUE TITLE
Issues about Conversation

### ISSUE THREAD

**Issue by tamlong0205** [brandonseydel/MailChimp.Net#70]
I have a problem when I get all message of a conversation by conversationId=b2f3134856. This conversation has only a message from subscriber.
This is my code:
```
line 1: IMailChimpManager mcManager = new MailChimpManager();
line 2: var messages = await mcManager.Messages.GetAllAsync("b2f3134856").ConfigureAwait(false);
```
The "messages" response at line 2 have Count=10 (message). I see that all message is from another conversation which from another deleted campaign. Anything wrong from MailChimp response; anyone faced with the same problem can help me to solve it.
Thanks,

**Comment by brandonseydel** [comment]
I cannot seem to get this to replicate?
