### ISSUE TITLE
Handling errors from Mailchimp

### ISSUE THREAD

**Issue by carpics** [brandonseydel/MailChimp.Net#76]
I am having issue to get this working in my Web project. 

I cannot catch Exception from methods in case Mailchimp API returns error for example 400 Bad Request.

When I run this in Console APP, I am able to catch Exception and the error is written in the console. 
But when I run this in Web project and this error is returned from Mailchimp API the code just stuck, and I don't catch any Exception.

Does anyone have the same issue?

**Comment by brandonseydel** [comment]
I cannot replicate?  Maybe there is something else that is swallowing the exception?

**Comment by carpics** [comment]
Ok I am calling method:
public async Task<Member> AddOrUpdateAsync(string listId, Member member)

from Member logic. But I am calling it from synchronous method like:

public bool ListSubscribe(string email, string listId, string apiKey)
{
        try
        {
           var api = new MailChimpManager(apiKey);
           var profile = new Member();
           profile.EmailAddress = emailAddress;
           Member member = api.Members.AddOrUpdateAsync(listId, profile).Result;
        }
        catch(Exception ex)
        {
             throw;
        }
         
         return member != null;
}

When mailchimp returns error 400, for example in case when I send wrong data for merge field, the code just deadlocks and nothing catch block doesn't catch the exception. 

Currently I don't have this issue with any other method. With all other methods from which I need repsonse I am using .Result, and it is working fine. Regarding a lot of articles to avoid deadlocks, .ConfigureAwait(false) should be used, and I can see that you are using it in method AddOrUpdateAsync() but still my code deadlocks in case exception. 

Do you have any idea. I need this resolved soon

**Comment by brandonseydel** [comment]
I will test this later this evening and push out a new release.  There must be a configureawait missing somewhere down the line.

**Comment by SushiGuy** [comment]
@carpics new to all this myself, but deadlock sounds like it may be a common async / await / task issue. This StackOverflow post talks about [using Task.Run to safely get the Result](http://stackoverflow.com/a/32429753/757931). Just throwing out some ideas. :smile:

**Comment by trevorloader** [comment]
I'm having a similar issue trying to use this from a web project.

**Comment by brandonseydel** [comment]
It is trying to dispatch back onto the main thread when the exception is thrown....try this

Task.Run(async () =>{

try{
await member.addorupdateasync()
}
catch()



}).Wait();

**Comment by trevorloader** [comment]
Perfect...I'm now capturing the exception. Thanks!

**Comment by eganlohman** [comment]
I'm getting the following exception message every time I try to add a new member to my list:

{"Exception of type 'MailChimp.Net.Core.MailChimpException' was thrown."} - pretty unhelpful.

The weird thing is, I can query my list for members, I just can't seem to add them.  Anyone else encountered something like this?

var mailChimpManager = new MailChimpManager(apiKey);

            var listId = "b2028360a0";

            var model = await mailChimpManager.Members.GetAllAsync(listId, new MemberRequest
            {
                Limit = 100,
                Status = Status.Subscribed
            });  // That works - model has a list of my existing members

var member = new Member();
            member.EmailAddress = "a-real-email-address@gmail.com";

            Task.Run(async () =>
            {
                try
                {
                    await mailChimpManager.Members.AddOrUpdateAsync(listId, member);
                }
                catch (MailChimpException mce)
                {
                    var message = mce.Message;  // Exception of type 'MailChimp.Net.Core.MailChimpException' was thrown.
                }
            }).Wait();

**Comment by SushiGuy** [comment]
Digging deeper in the MailChimpException usually provides the answers you're looking for.
Try this:
`
try {
    await mailChimpManager.Members.AddOrUpdateAsync(listId, member);
}
catch (MailChimpException ex) {
    string exMessage = (GetMailChimpErrorMessage(ex));
}
// ...
private string GetMailChimpErrorMessage(MailChimpException ex) {
    string retMsg = "";
    if (ex.Errors != null) {
        foreach (MailChimpException.Error err in ex.Errors) {
            retMsg += err.Message + " -- ";
        }
    }
    else if (ex.Detail != null) {
        retMsg = ex.Detail;
    }
    else if (ex.InnerException != null) {
        retMsg = ex.InnerException.Message;
    }
    else {
        retMsg = ex.Message;
    }
    return retMsg;
}
`

**Comment by eganlohman** [comment]
Wow.  That was boneheaded of me.  Thanks @SushiGuy - the Errors revealed that I need to set both Status and StatusIfNew.  

Thanks man!

**Comment by carpics** [comment]
@brandonseydel 

Thanks for suggestion. I am already using that logic with Task.Run() as only solution I found.

Anyway I am wondering why only this one dispatch back onto the main thread when the exception is thrown. I don't have this issue with any other methods when exception is thrown.

As per this great [article](http://blog.stephencleary.com/2012/07/dont-block-on-async-code.html) it should work with ConfigureAwait(false).

@SushiGuy 
Thanks for advice, but I would really like to avoid using Task.Run(). In the SO question which linked in your comment, accepted answer is the one which links to blog post which I linked above in comment. 

It explains that this should work fine with using ConfigureAwait(false). And it is working fine with all other methods in library, but just in this methods it deadlocks when exception is thrown.

**Comment by vanilaicy** [comment]
Hello, 

I'm trying to fix one bug. If a visitor unsubcribed a newsletter, then later they want to re-subscribe again, then the page crash "Exception of type 'MailChimp.Net.Core.MailChimpException' was thrown."

is it possible to re-subscribe without doing by manual?

Here this my method. Anyone could give me advice how to solve this problem? Thanks
`
if (ModelState.IsValid)
            {
                try
                {
                    var modelThanks = LoadModelWithState<StartPageViewModel>("Index") ??
                                      CreateViewModel<StartPageViewModel>(currentPage);

                    //Added string apikey and listId to mailChimp epi's properties
                    var apiKey = modelThanks.Settings.Web.MailChimpApiKey;
                    var listId = modelThanks.Settings.Web.MailChimpListId;

                    if (string.IsNullOrEmpty(apiKey) || string.IsNullOrEmpty(listId))
                        throw new Exception("no mailchimp config!!!");


                    IMailChimpManager mailChimpManager = new MailChimpManager(apiKey);
                    // Use the Status property if updating an existing member
                    var member = new Member {EmailAddress = mailchimpinput, StatusIfNew = Status.Subscribed};

                    await mailChimpManager.Members.AddOrUpdateAsync(listId, member);

                    // redirect to tacksida
                    return Redirect(modelThanks.Settings.Web.MailChimpThankyouPage.GetAbsoluteUrl());
                }
                catch (Exception ex)
                {
                    throw ex;
                }
            }

            var modelNew = LoadModelWithState<StartPageViewModel>("Index") ??
                           CreateViewModel<StartPageViewModel>(currentPage);

            return View("Index", modelNew);`
