### ISSUE TITLE
Unable to find campaign content

### ISSUE THREAD

**Issue by CraigInTheCity** [brandonseydel/MailChimp.Net#78]
Hello,

Thank you for all your work on this. I am unable to find where the content for a campaign is located. Can you please help?

Thanks again!

**Comment by brandonseydel** [comment]
I think it is just mailChimpManager.Content

**Comment by CraigInTheCity** [comment]
Thank you, sincerely, for your response! I did see that, but I figure I’m missing something because one cannot simply:
MailChimp.Net.Models.Content cont = new MailChimp.Net.Models.Content();
cont = mcManager.Content.GetAsync(campaign.Id);

I’m missing the part where I can obtain said content. Please forgive my boneheadedness if I’m completely overlooking something obvious.

**Comment by madsbuch** [comment]
It seems like this part is not properly implemented. Just yesterday the MailChimp.Net/Models/ContentTemplate.cs file was added. But it does not seem like it is added to the project.

In my case this is the reason why a can't add content from a template. So far only plaint_text and html content can be set. This is evident from the file MailChimp.Net/Core/Requests/ContentRequest.cs

I hope this issue can be resolved in near future.

**Comment by brandonseydel** [comment]
This will be coming today.  Thanks.
