### ISSUE TITLE
Getting Results from GetAllAsync

### ISSUE THREAD

**Issue by ishfuseini** [brandonseydel/MailChimp.Net#79]
I'm having a bit of trouble getting the results from the GetAllAsync call.

When I run the code

`
  var getSubs = subManager.Members.GetAllAsync(listid).ConfigureAwait(false);
  Console.WriteLine(getSubs);
  Console.ReadLine();
`

I just get a blank screen. How can I get the results into a Members object?

**Comment by brandonseydel** [comment]
You need to serialize it to the screen if you want to see.  You can use a json or xml

**Comment by roopeshkurian** [comment]
![png](https://cloud.githubusercontent.com/assets/15811922/17962092/cde8bc68-6acc-11e6-8f66-729f7e1e4eab.png)


I am always getting WaitingForAnApproval for every item.   But all email id's recieved mail campaign. 

Can you please tell me why its showing like that?

**Comment by brandonseydel** [comment]
I cannot tell how you are writing this but you will need to await the task in order to get the result that id is the task id. var members = mangaer.GetAllAsync().Result will also work.

**Comment by roopeshkurian** [comment]
Thanks  :)

It worked :)
