### ISSUE TITLE
Member's Status changed to "Subscribed" when sending new instance of Member to MemberLogic.AddOrUpdateAsync method

### ISSUE THREAD

**Issue by MatiasALopez** [brandonseydel/MailChimp.Net#80]
Hello!

I'm trying to add or update a member. For that I'm creating a new Member instance and calling the method "MemberLogic.AddOrUpdateAsync". When updating some members with the status "Unsubscribed" I've found that their status was changed to "Subscribed".

I've found that the Member's Status property is of type Status (which is an Enum). The problem is that it doesn't allow a null value nor a "None"/"NotSpecified" value, so the default value will be the first value ("Subscribed"). I've cloned your repo and add that value to the Enum and it worked as expected: if the Status is None, the member's status it's not updated.

Could you please add that "None" value (or equivalent) to the Status Enum? 
If this doesn't make sense to you, please let me know your thoughts.

Thanks!

**Comment by MatiasALopez** [comment]
To clarify, this is the value I've added to the Status Enum:
`[Description("")]
None,`

**Comment by brandonseydel** [comment]
Yes I will do this later this evening.  I am planning on pushing out a nuget package this evening.

Thanks.

**Comment by MatiasALopez** [comment]
Awesome!

Thank you!
