### ISSUE TITLE
QUESTION: Batch unsubscribe?

### ISSUE THREAD

**Issue by devuxer** [brandonseydel/MailChimp.Net#81]
Is there any way to unsubscribe a bunch of members from a list in one shot with this library? If so, how?

I looked at BatchLogic.cs, but it seems like this is expecting me to work with raw HTML requests, which made me think that wasn't the right path. I also looked at the tests, but I gather from https://github.com/brandonseydel/MailChimp.Net/issues/8 that this is a work in progress.

Thanks!

**Comment by devuxer** [comment]
Here's what I have at the moment:

```C#
public async void UpdateListAsync(string listId, IEnumerable<Member> members)
{
    var mailChimpMembersToRemove = await _mailChimp.Members.GetAllAsync(listId);
    foreach (var mailChimpMember in mailChimpMembersToRemove)
        await _mailChimp.Members.DeleteAsync(listId, mailChimpMember.EmailAddress);
    var mailChimpMemberToAdd = members.Select(GetMailChimpMember);
    foreach (var mailChimpMember in mailChimpMemberToAdd)
        await _mailChimp.Members.AddOrUpdateAsync(listId, mailChimpMember);
}
```

I fear this will take a lot longer than performing a single batch operation, but if this is actually efficient, please let me know.

**Comment by brandonseydel** [comment]
```CSharp
var membersToUnsubscribe = new List<Member>();
var listId = "asdfasfds";

await this._mailChimpManager.Batches.AddAsync(new Core.BatchRequest
{
    Operations = membersToUnsubscribe.Select(x =>

        new Operation
        {
            Method = $"{listId}/members/{this.Hash(x.EmailAddress.ToLower())}",
            Params = "",
            Body = JsonConvert.SerializeObject(x)
        })                
});

```

**Comment by devuxer** [comment]
@brandonseydel, thank for the speedy reply! Sounds like I really do need to use a raw HTTP request.

Could you clarify one thing? What is `this.Hash()`? It looks like something that would properly encode the email address so it works in a URL, but my `this` definitely doesn't have a `Hash` method.

**Comment by brandonseydel** [comment]
_mailChimpManager.Members.Hash("stuff@stuff.com")

Date: Mon, 22 Aug 2016 11:16:17 -0700

**Comment by devuxer** [comment]
Thanks again, Brandon. Your code helped me get further, though I did need to make a few modifications to get it to work:

1. For `Operation`, I needed to move what you had for `Method` into `Path`, and set `Method` to `"POST"` or `"DELETE"`.
2. I needed to add "lists/" to the beginning of `Path`.
3. For unsubscribes (DELETEs), I needed to eliminate `Body`, and for subscribes (POSTs), I needed to delete the hashed email address from `Path`.

I also noticed a couple potential issues with MailChimp.NET that I can file separate bug reports for if you like:

1. For list members, `GetAllAsync` doesn't actually "get all"--it only gets the first 10 subscribers of a list. The only way to actually get all the members is to set `Limit` to the number of members in the list (or an arbitrarily large number). 
2. For `MemberLastNote`, the constructor should have `CreatedAt = new DateTime()`.
3. For `MailChimpMember`, a whole bunch of defaults need to be set in the constructor (see below).

Anyway, for anyone trying to do something similar, here's the code I have at the moment:

```C#
// replaces all subscribers in a list with a totally new group of subscribers

public async Task UpdateListAsync(string listId, IEnumerable<Member> members)
{
    var unsubscribeBatchRequest = await GetUnsubscribeBatchRequestAsync(listId);
    await _mailChimp.Batches.AddAsync(unsubscribeBatchRequest);
    var subscribeBatchRequest = GetSubscribeBatchRequest(listId, members);
    await _mailChimp.Batches.AddAsync(subscribeBatchRequest);
}

private async Task<BatchRequest> GetUnsubscribeBatchRequestAsync(string listId)
{
    var memberCount = await _mailChimp.Members.GetTotalItems(listId, null);
    var mailChimpMembersToUnsubscribe = await _mailChimp.Members.GetAllAsync(listId, new MemberRequest { Limit = memberCount });
    var unsubscribeOperations = mailChimpMembersToUnsubscribe.Select(x => GetUnsubscribeOperation(listId, x));
    return new BatchRequest { Operations = unsubscribeOperations };
}

private Operation GetUnsubscribeOperation(string listId, MailChimpMember mailChimpMember)
{
    var subscriberHash = _mailChimp.Members.Hash(mailChimpMember.EmailAddress.ToLower());
    return new Operation
    {
        Method = Method.DELETE.ToString(),
        Path = $"lists/{listId}/members/{subscriberHash}"
    };
}

private static BatchRequest GetSubscribeBatchRequest(string listId, IEnumerable<Member> members)
{
    var subscribeOperations = members.Select(x => GetSubscribeOperation(listId, x));
    return new BatchRequest { Operations = subscribeOperations };
}

private static Operation GetSubscribeOperation(string listId, Member member)
{
    var mailChimpMember = GetMailChimpMember(member);
    return new Operation
    {
        Method = Method.POST.ToString(),
        Path = $"lists/{listId}/members",
        Body = JsonConvert.SerializeObject(mailChimpMember)
    };
}

private static MailChimpMember GetMailChimpMember(Member member)
{
    var mergeFields = GetMergeFields(member);
    return new MailChimpMember
    {
        EmailAddress = member.EmailAddress,
        MergeFields = mergeFields,
        EmailClient = string.Empty,
        EmailType = string.Empty,
        Id = string.Empty,
        IpOpt = string.Empty,
        IpSignup = string.Empty,
        Language = string.Empty,
        LastChanged = string.Empty,
        ListId = string.Empty,
        Location = new Location(),
        LastNote = new MemberLastNote { CreatedAt = new DateTime() },
        Stats = new MemberStats(),
        TimestampOpt = string.Empty,
        TimestampSignup = string.Empty,
        UniqueEmailId = string.Empty
    };
}

private static Dictionary<string, string> GetMergeFields(Member member)
{
    return new Dictionary<string, string>
    {
        ["FNAME"] = member.FriendlyFirstName,
        ["LNAME"] = member.LastName
    };
}
```

**Comment by brandonseydel** [comment]
For initialization issues you need to set parameters when serializing. You can check my custom serializers for PatchAsJson etc....same thing for member note.  The get all I am deliberating now on how to handle. (more place than one).  I also think creating my own batching mechanism would be of great use to the community.

**Comment by devuxer** [comment]
I'm not sure what you're referring to with your custom serializers, but I was able to get it to work using by simply instructing JSON.NET to ignore null values.

This simplified my code to just this:

```c#
private static Operation GetSubscribeOperation(string listId, Member member)
{
    var mailChimpMember = GetMailChimpMember(member);
    var jsonSerializerSettings = new JsonSerializerSettings { NullValueHandling = NullValueHandling.Ignore };
    return new Operation
    {
        Method = Method.POST.ToString(),
        Path = $"lists/{listId}/members",
        Body = JsonConvert.SerializeObject(mailChimpMember, jsonSerializerSettings)
    };
}

private static MailChimpMember GetMailChimpMember(Member member)
{
    var mergeFields = GetMergeFields(member);
    return new MailChimpMember
    {
        EmailAddress = member.EmailAddress,
        MergeFields = mergeFields,
    };
}
```

So I think this will do for now, but I would definitely love to see a batching mechanism added to this library. (Let me know if you'd like any further input on how that might work.)

BTW, one big gotcha that people should be aware of is that there seems to be a serious delay between the time a list is manipulated and the time the results of changes actually show up in the MailChimp web interface. I assume this is some sort of "eventual consistency", but I don't think it used to be this way with MailChimp API 2.X.

**Comment by devdept** [comment]
Hi devuxer & brandonseydel,

I'm in contact with MailChimp support from a long time because of the "exceeds MailChimp's 10 connection limit". I am totally surprised to see that this library doesn't support the ability to fill a MailChimp list with existing customers. This is the first thing that any company with a customer base needs to do.

So here are my questions:

1) Do you confirm that this library is safe for updating only one MailChimp contact at time? If yes, please specify it somewhere.
2) Would you mind adding the final source code for filling a MailChimp list with thousands of contacts without the "exceeds MailChimp's 10 connection limit" issue?
3) Can you please add this feature as soon as possible?

Thanks.

Alberto

**Comment by devdept** [comment]
Just wanted to thank devuxer for the pasted code. It has really saved my day.

**Comment by fireole** [comment]
@devdept I think your point about "the first thing" any company with customer needs to do is fill a list is off point.  This is probably a one time thing if you needed to do that.   If it is a big concern, then use file csv file and import into the mailchimp list.  

You can't assume for any company, and yours is not a use case of mine, ever!

**Comment by devdept** [comment]
As a programmer I didn't think about CSV export/import, in any case it's a good solution. Thanks for your comment!
