### ISSUE TITLE
Missing Methods

### ISSUE THREAD

**Issue by enkodellc** [brandonseydel/MailChimp.Net#82]
I am testing out your wrapper versus https://github.com/shahriarhossain/MailChimp.Api.Net hoping that yours is more refined but I am already running into similar issues just as I did with his, though your does seem to be a bit more refined it is by far 100% complete as described on the readme. I tried to do 4 calls and 3/4 of my first calls had issues. I have all these done in the other wrapper so I guess I will continue to develop on that.

1. It is my fault but I cannot seem to build your wrapper with VS2012. I tried updating the c# language pack for version 6 but it still fails. Not a big issue but I cannot contribute if I cannot run it, any ideas? 
2. Are you missing the Templates.DeleteAsync? I know the other wrapper was missing a lot of calls and I added a bunch but if your wrapper has the same issues I will stick with fixing his.
3. Templates.UpdateAsync seems to be missing as well?
4. TemplateFolder.AddAsync  this differs from the MailChimp API, why do you have folderId as a request parameter?

**Comment by enkodellc** [comment]
Another issue: TemplateFolders path should be **"template-folders/"** not **"templates-folders/"**  

I can submit a PR for this as it is a simple typo. I will try getting it to build but I don't feel comfortable submitting PR's if I cannot compile and test the code.

**Comment by brandonseydel** [comment]
Resolved all of these issues with c16ed8dee5d60a98c2c0866978092f5e863e186f

**Comment by enkodellc** [comment]
Thanks @brandonseydel . I tried installing VS2015 community and that was being stubborn with the install path.  I don't mind submitting PR's for these fixes but it has been an ultra hassle since I don't have VS2015. When will these changes be reflected in the NuGet Package?

**Comment by brandonseydel** [comment]
I will be releasing a new Nuget package this morning
