### ISSUE TITLE
1.7.0 issue with Members.AddOrUpdateAsync

### ISSUE THREAD

**Issue by lindows-xx** [brandonseydel/MailChimp.Net#85]
on 1.6.7 this was working,

now after updating to 1.7.0 i get the following error when trying to add customers to a list
"Exception of type 'MailChimp.Net.Core.MailChimpException' was thrown."

**Comment by jgerschk** [comment]
I had the same issues with the 1.7.0, had to revert back.  From what I can tell it's a JSON formatting issues in the API here....

**Comment by brandonseydel** [comment]
I see the status is complaining about the none status hotfix 1.7.1 in 5 min

**Comment by jgerschk** [comment]
Thanks @brandonseydel
