### ISSUE TITLE
Using Members.AddOrUpdateAsync, still having double opt-in

### ISSUE THREAD

**Issue by Lexa1983** [brandonseydel/MailChimp.Net#86]
Hi,
Please tell me
how can I add a member to a list with single opt-in (i.e. no confirm subscription mail will send).

Thanks.

**Comment by brandonseydel** [comment]
Can you look into the statusifnew property on the member you are adding

**Comment by JakubOleksy** [comment]
It looks like something weird is happening with this. When I use the StatusIfNew property (to Subscribed) it doesn't notify via email, but it also doesn't update the List on MailChimp. On the second identical call, it does.

**Comment by codecadwallader** [comment]
I saw this issue as well, and can confirm that setting the StatusIfNew property as well avoided the confirmation e-mail.  Perhaps this is something that could be added to the README as another example for clarity?

Thanks for this great tool, very helpful. :)

**Comment by codecadwallader** [comment]
Also, I did see there's a few minutes latency between when the API call is made and when the MailChimp subscriber list updates.. so I suspect that's what the other user was seeing when the second call seemed to "kick in".  To anyone else, simply try making the call and wait ~5 minutes to confirm within MailChimp.

**Comment by t00thy** [comment]
Well I tried it and there is 5-10 minutes delay between subscribing and viewing subscriber on web page.

**Comment by czaari** [comment]
solution found. updating straight away if use status.subscribed in both properties "status and statusifnew" as such:
var member = new Member { EmailAddress = "chakib.zaari@majerconsulting.com", Status = Status.Subscribed,StatusIfNew=Status.Subscribed };

**Comment by nicholastic** [comment]
I've tested this and haven't had any problems. Use Status if the member already exists, and StatusIfNew if the member does not exist. Everything updates immediately. If you use Status and the member does not exist, the member will be sent the confirmation opt-in email.
