### ISSUE TITLE
"Could not load file or assembly 'Newtonsoft.Json, Version=8.0.0.0"

### ISSUE THREAD

**Issue by andyjonesx** [brandonseydel/MailChimp.Net#87]
I am getting this error when trying to do `CampaignFolders.AddAsync()`. I have version 9.0 installed for the application.

**Comment by linh-tran-mobosurvey** [comment]
I'm having a similar runtime issue "Could not load file or assembly 'Newtonsoft.Json, Version=6.0.0.0". I have version 9.0 installed.

**Comment by andyjonesx** [comment]
Additionally... I did a search all through my code for a mention of 8.0.0.0 but I couldn't see. I'm still not 100% sure it isn't my own issue, though.

**Comment by linh-tran-mobosurvey** [comment]
I did the same for 'Newtonsoft.Json, Version=6.0.0.0' and found nothing.

**Comment by brandonseydel** [comment]
Can you add the binding redirect to your configuration.  

  <runtime>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="Newtonsoft.Json" publicKeyToken="30ad4fe6b2a6aeed" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-9.0.0.0" newVersion="9.0.0.0" />
      </dependentAssembly>
    </assemblyBinding>
  </runtime>


web api tries to look for 6 and there must be something in andys project looking for 8

**Comment by linh-tran-mobosurvey** [comment]
I already had the binding redirect in my config and got the error.

Perhaps I'm doing something wrong in my code?

var tempMailChimpMgr = new MailChimpManager("username");
var mailChimpListsAwaitable = tempMailChimpMgr.Lists.GetAllAsync().ConfigureAwait(false);

// THIS IS WHERE I GET THE RUNTIME ERROR                
var mailChimpLists = mailChimpListsAwaitable.GetAwaiter().GetResult().AsEnumerable().Where(l => !l.Name.Equals("My list name", StringComparison.CurrentCultureIgnoreCase));

**Comment by brandonseydel** [comment]
Make sure the binding redirect is pointing to 9.  It should never throw an error for 8 if you have that binding redirect in place correctly.

**Comment by linh-tran-mobosurvey** [comment]
The bindings in all my configs were all pointing to 9 and is exactly how you have it above.

**Comment by brandonseydel** [comment]
Can you paste your config please?

**Comment by linh-tran-mobosurvey** [comment]
<runtime xmlns="">
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="Newtonsoft.Json" publicKeyToken="30ad4fe6b2a6aeed" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-9.0.0.0" newVersion="9.0.0.0" />
      </dependentAssembly>
    </assemblyBinding>
  </runtime>

**Comment by brandonseydel** [comment]
Can you paste your entire config

**Comment by linh-tran-mobosurvey** [comment]
`<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <configSections>
    <sectionGroup name="applicationSettings" type="System.Configuration.ApplicationSettingsGroup, System, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089">
      <section name="MyCompany.CRM.Properties.Settings" type="System.Configuration.ClientSettingsSection, System, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e0893" requirePermission="false" />
    </sectionGroup>
  </configSections>
  <system.serviceModel>
	<bindings>
	  <customBinding>
		<binding name="SoapBinding" closeTimeout="00:30:00" openTimeout="00:30:00" receiveTimeout="00:30:00" sendTimeout="00:30:00">
		  <security authenticationMode="UserNameOverTransport">
			<secureConversationBootstrap />
		  </security>
		  <textMessageEncoding messageVersion="Soap11WSAddressingAugust2004" />
		  <httpsTransport maxReceivedMessageSize="655360000" />
		</binding>
	  </customBinding>
	</bindings>
	<client>
	  <endpoint address="https://webservice.exacttarget.com/Service.asmx" binding="customBinding" bindingConfiguration="SoapBinding" contract="ExactTargetClient.Soap" name="Soap" />
	</client>
  </system.serviceModel>
  <applicationSettings>
    <MyCompany.CRM.Properties.Settings>
      <setting name="MyCompany_CRM_DotMailerApi_API" serializeAs="String">
        <value>http://apiconnector.com/API.asmx</value>
      </setting>
      <setting name="MyCompany_CRM_SatuitReportsService_ReportingService2005" serializeAs="String">
        <value>http://MyCompany:8080/ReportServer/ReportService2005.asmx</value>
      </setting>
      <setting name="MyCompany_CRM_SatuitReportsExecution_ReportExecutionService" serializeAs="String">
        <value>http://MyCompany:8080/ReportServer/ReportExecution2005.asmx</value>
      </setting>
      <setting name="MyCompany_CRM_com_bronto_api4_BrontoSoapApiImplService" serializeAs="String">
        <value>https://api.bronto.com/v4</value>
      </setting>
    </MyCompany.CRM.Properties.Settings>
  </applicationSettings>
<startup><supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.5" /></startup>
  <runtime>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="Newtonsoft.Json" publicKeyToken="30ad4fe6b2a6aeed" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-9.0.0.0" newVersion="9.0.0.0" />
      </dependentAssembly>
    </assemblyBinding>
  </runtime>

</configuration>
`

**Comment by linh-tran-mobosurvey** [comment]
I have found the issue. It was because my site is very old (.net 2.0) and the web.config first line: 
<configuration xmlns="http://schemas.microsoft.com/.NetConfiguration/v2.0">
I just had to remove: xmlns="http://schemas.microsoft.com/.NetConfiguration/v2.0"

and now it works.

Sorry for the bother but hopefully this will assist others experiencing similar issues.
