### ISSUE TITLE
No option "AddToList"

### ISSUE THREAD

**Issue by carpics** [brandonseydel/MailChimp.Net#89]
There is no method "AddToList" which would POST to endpoint "/lists". 
There is only "AddOrUpdateAsync()" which PATCH to endpoint "/lists/{list_id}"

What is the difference? The difference is that with endpoint "/list" you have option to choose either to send or not confirmation email for new subscriber.

The MC API docummentations says that if you want to send confirmation email for new Member, you should set field Status=Pending for new member. Or if you don't want to send confirmation email you set field Status=Subscribed.

This doesn't work with  AddOrUpdateAsync(). If I set Status=Pending, confirmation email is never sent and Member is not subscribed to list

**Comment by brandonseydel** [comment]
Try statusifnew

**Comment by carpics** [comment]
There is no statusifnew in Enum Status:

public enum Status
{
     Subscribed = 0,
     Unsubscribed = 1,
     Cleaned = 2,
     Pending = 3
}

**Comment by brandonseydel** [comment]
It should be a property on the member

**Comment by dougvdotcom** [comment]
@carpics: @brandonseydel is saying that if you use the Member.StatusIfNew property to set the member to Pending, she will be added to the list in Pending status; but if you set Member.Status to Pending for a new Member, MailChimp ignores that and adds the user as Subscribed.

```
public async Task Create()
{
	var member = new Member
	{
		EmailAddress = "someone@aserver.com",
		StatusIfNew = Status.Pending,
		TimestampSignup = DateTime.UtcNow.ToString("s"),
		MergeFields = new Dictionary<string, string>
		{
			{ "FNAME", "Someone" },
			{ "LNAME", "New" }
		}
	};

	await Manager.Members.AddOrUpdateAsync("MY_LIST_ID", member);
}
```
