### ISSUE TITLE
Requested value 'transactional' was not found

### ISSUE THREAD

**Issue by SushiGuy** [brandonseydel/MailChimp.Net#91]
Great project! Really enjoying the package. Seeing this error in production and test. Thoughts?

> System.AggregateException[0].InnerException.Message = "Requested value 'transactional' was not found."

Happens sometimes with this code (seeing in Production logs):
`obj = mailChimpManager.Members.GetAsync(gListId, email).Result;`

But seemingly always with this code (recreatable in Test):
`IEnumerable<Member> objs = _repo.mailChimpManager.Members.GetAllAsync(TestListId, new MemberRequest { Limit = 200 }).Result;`

**Comment by brandonseydel** [comment]
Hmm I'll investigate this

**Comment by Jetski5822** [comment]
Getting this too.... not sure why

**Comment by andysangyee** [comment]
When you add a customer through eCommerce then it also adds a member to the list with status of 'transactional'. I think you just need to translate this status name to a new enum value in your MailChimp.Net.Models.Status enumeration when you are fetching any member(s).
This fix would be useful to me too. 

MailChimp.Net.V3 is great, please keep up the good work! :)
