### ISSUE TITLE
Adding a member to a list always goes on as Pending not Subscribed

### ISSUE THREAD

**Issue by philipburrell** [brandonseydel/MailChimp.Net#92]
Using 
await  mailChimpManager.Members.AddOrUpdateAsync(
                           createdList.Id,
                           new MailChimp.Net.Models.Member { EmailAddress = emailto, Status = MailChimp.Net.Models.Status.Subscribed }).ConfigureAwait(false);

**Comment by brandonseydel** [comment]
The property is statusifnew....I have no idea why mail chimp did this?  It has caused many people headache.  Can you try this and let me know if it works ok.
