### ISSUE TITLE
Link to dashboard

### ISSUE THREAD

**Issue by Bupyc2000** [brandonseydel/MailChimp.Net#94]
When you get Campaign. In request header you can get dashbord url:
`HTTP/1.1 200 OK
Server: nginx
Content-Type: application/json; charset=utf-8
Content-Length: 1657
Vary: Accept-Encoding
X-Request-Id: 6442eb20-6117-460c-95f2-3c05cdf3fb72
Link: <https://api.mailchimp.com/schema/3.0/Campaigns/Instance.json>; rel="describedBy", <https://usX.admin.mailchimp.com/campaigns/show?id=2181921>; rel="dashboard"
Date: Tue, 15 Sep 2015 18:05:24 GMT
Connection: keep-alive`

Can I get this url or just webId(2181921)?

**Comment by brandonseydel** [comment]
I am working on this as I am typing (letting tests run ;))
