### ISSUE TITLE
Using with Parallel scenario

### ISSUE THREAD

**Issue by ab798** [brandonseydel/MailChimp.Net#97]
I use "Mail Chimp 3.0 Wrapper" in parallel scenario - it means that I connect to several MailChimp accounts (with different API keys) at the same time. As result, sometimes the error "MailChimp.Net.Core.MailChimpNotFoundException" occurs. I was searching the reason of this exception for a long time.
Eventually I find that field _apiKey and property ApiKey is static (see line 19 and 42 in MailManagerBase.cs file).
Would you like to remove "static" keyword and make these field and property as Instance?
Thank you in advance.

**Comment by brandonseydel** [comment]
Closed with cccdea0b3f0446284daa39db1471b40a80e17b36
